"""Translate _art_b7_1_orig.json CN->VI and save _art_b7_1_trans.json"""
import sys
sys.stdout.reconfigure(encoding='utf-8')
import json, re, copy

# Translation map: Chinese -> Vietnamese
TRANS = {
    "否": "Không",
    "特性": "Đặc điểm",
    "结果": "Kết quả",
    "问题": "Vấn đề",
    "维度": "Tiêu chí",
    "注意": "Lưu ý",
    "推荐": "Khuyến nghị",
    "示例": "Ví dụ",
    "模式": "Chế độ",
    "原理": "Nguyên lý",
    "说明": "Giải thích",
    "优势": "Ưu điểm",
    "重要": "Quan trọng",
    "场景": "Tình huống",
    "选择 ": "Chọn ",
    " 目录": " thư mục",
    "省流版": "Tóm tắt nhanh",
    "不推荐": "Không khuyến nghị",
    "❌ 差": "❌ Kém",
    "一句话": "Một câu",
    "登录态": "Trạng thái đăng nhập",
    "✅ 能": "✅ Có",
    "稳定性": "Độ ổn định",
    "：把 ": ": Thay ",
    "不稳定": "không ổn định",
    "打开 ": "Mở ",
    "适合场景": "Tình huống phù hợp",
    "✅ 极低": "✅ Rất thấp",
    "💰 比价": "💰 So sánh giá",
    "✅ 稳定": "✅ Ổn định",
    "⬇ 基于": "⬇ Dựa trên",
    " 目录。": " thư mục.",
    "⚠️ 高": "⚠️ Cao",
    "安全边界": "Ranh giới bảo mật",
    "❌ 不能": "❌ Không",
    "直接选 ": "Chọn ngay ",
    "适用场景": "Tình huống áp dụng",
    "需要登录": "Cần đăng nhập",
    "突然失效": "Đột ngột hỏng",
    " 中的 ": " trong ",
    "操作方式": "Cách thao tác",
    "，不是 ": ", không phải ",
    "操作步骤": "Các bước thao tác",
    "扩展模式": "Chế độ extension",
    "✅ 支持": "✅ Hỗ trợ",
    "但其实，": "Nhưng thực ra, ",
    "参数说明": "Giải thích tham số",
    "稳定持久": "Ổn định lâu dài",
    "⬇ 使用": "⬇ Sử dụng",
    "内容抓不到": "Không lấy được nội dung",
    "遇到的问题": "Vấn đề gặp phải",
    "被检测风险": "Rủi ro bị phát hiện",
    "复用登录态": "Tái sử dụng trạng thái đăng nhập",
    "⚠️ 中高": "⚠️ Trung bình - Cao",
    "结构关系：": "Mối quan hệ cấu trúc:",
    "IP 封禁": "Chặn IP",
    "❌ 不适合": "❌ Không phù hợp",
    " 属性为 ": " có giá trị là ",
    "⚠️ 一般": "⚠️ Trung bình",
    "更直白一点：": "Nói trắng ra:",
    "需要额外成本": "Cần chi phí thêm",
    "无验证码困扰": "Không bị phiền bởi captcha",
    "能复用登录态": "Có thể tái sử dụng trạng thái đăng nhập",
    "个人资料模式": "Chế độ profile cá nhân",
    "返回结果示例": "Ví dụ kết quả trả về",
    "能执行 JS": "Có thể chạy JS",
    "行为特征异常": "Hành vi bất thường",
    "打开目标网页": "Mở trang web mục tiêu",
    "24小时运行": "Chạy 24 giờ",
    "📜 滚动页面": "📜 Cuộn trang",
    "📦 批量操作": "📦 Thao tác hàng loạt",
    "👀 临时查看": "👀 Xem tạm thời",
    "❌ 关闭弹窗": "❌ Đóng popup",
    "一句话答案：": "Trả lời ngắn gọn:",
    "⏰ 定时抓取": "⏰ Thu thập định kỳ",
    "🤖 无人值守": "🤖 Không cần giám sát",
    "✅ 激活扩展": "✅ Kích hoạt extension",
    "🔐 敏感账号": "🔐 Tài khoản nhạy cảm",
    "点击网页  ": "Nhấp vào trang web  ",
    "真实浏览器指纹": "Fingerprint trình duyệt thật",
    "将开关切换为 ": "Chuyển công tắc sang ",
    "✅ 已登录网站": "✅ Website đã đăng nhập",
    "🎯 最后说一句": "🎯 Lời cuối",
    "遇到验证码时：": "Khi gặp captcha:",
    "修改配置文件 ": "Chỉnh sửa file cấu hình ",
    "需要说明的是：": "Cần lưu ý rằng:",
    "HTTP 爬虫": "HTTP crawler",
    "打开浏览器  ": "Mở trình duyệt  ",
    "总结：方案对比": "Tổng kết: So sánh các phương án",
    "登录触发验证码": "Đăng nhập kích hoạt captcha",
    "自动化特征暴露": "Lộ đặc điểm tự động hóa",
    "VNC 是什么": "VNC là gì",
    "🛡️ 清晰隔离": "🛡️ Cách ly rõ ràng",
    " 等自动化标记": " và các dấu hiệu tự động hóa",
    "为什么没那些问题": "Tại sao không gặp những vấn đề đó",
    "👆 手动点击一下": "👆 Nhấp thủ công một cái",
    "你手动完成验证码": "Bạn hoàn thành captcha thủ công",
    "，随时可能被封。": ", có thể bị chặn bất cứ lúc nào.",
    "执行定时任务  ": "Thực thi tác vụ định kỳ  ",
    "需要手动登录一次": "Cần đăng nhập thủ công một lần",
    "给飞书发消息  ": "Gửi tin nhắn qua Feishu  ",
    "📊 返回比价结果": "📊 Trả về kết quả so sánh giá",
    "XFCE 是什么": "XFCE là gì",
    "🔍 搜索同名商品": "🔍 Tìm kiếm sản phẩm cùng tên",
    "🔧 需要现有插件": "🔧 Cần plugin hiện có",
    "直接使用已有登录态": "Sử dụng trực tiếp trạng thái đăng nhập hiện có",
    "📋 整理成表格给我": "📋 Sắp xếp thành bảng cho tôi",
    " 换成你的用户名。": " thành tên người dùng của bạn.",
    "昨天有个朋友问我：": "Hôm qua có một người bạn hỏi tôi:",
    "三种方案，三种困境": "Ba phương án, ba khó khăn",
    "开启\"开发者模式\"": "Bật \"Chế độ nhà phát triển\"",
    "📦 安装缺失的依赖": "📦 Cài đặt các dependency còn thiếu",
    "，连页面都进不去。": ", thậm chí không vào được trang.",
    "\"操作网银查流水\"": "\"Thao tác internet banking xem giao dịch\"",
    "：❌ 方案行不通。": ": ❌ Phương án không khả thi.",
    "⚖️ 两种模式对比": "⚖️ So sánh hai chế độ",
    "这会把扩展下载到 ": "Lệnh này sẽ tải extension vào ",
    "技巧 4：处理验证码": "Mẹo 4: Xử lý captcha",
    "💡 扩展模式使用技巧": "💡 Mẹo sử dụng chế độ extension",
    "（以扩展模式为例）：": "(Lấy chế độ extension làm ví dụ):",
    "用个人资料模式打开 ": "Dùng chế độ profile cá nhân mở ",
    "第 1 步：安装扩展": "Bước 1: Cài đặt extension",
    "打开任意网页（比如 ": "Mở một trang web bất kỳ (ví dụ ",
    "我已经手动登录，继续": "Tôi đã đăng nhập thủ công, tiếp tục",
    "调用外部 API  ": "Gọi API bên ngoài  ",
    "方式二：自己人工安装": "Cách 2: Tự cài đặt thủ công",
    "第 4 步：激活扩展": "Bước 4: Kích hoạt extension",
    "🔧 扩展模式配置指南": "🔧 Hướng dẫn cấu hình chế độ extension",
    "：⚠️ 勉强能用，但": ": ⚠️ Tạm dùng được, nhưng",
    "：装好扩展，随用随开。": ": Cài xong extension, dùng lúc nào mở lúc đó.",
    "配置 OpenClaw": "Cấu hình OpenClaw",
    "案例 3：电商平台比价": "Ví dụ 3: So sánh giá trên sàn thương mại điện tử",
    "临时用一下、已有登录态": "Dùng tạm, đã có trạng thái đăng nhập",
    "：配置一次，长期受益。": ": Cấu hình một lần, hưởng lợi lâu dài.",
    "：批量收藏，省时省力。": ": Lưu hàng loạt, tiết kiệm thời gian và công sức.",
    "技巧 3：随时可以暂停": "Mẹo 3: Có thể tạm dừng bất cứ lúc nào",
    "DISPLAY 是什么": "DISPLAY là gì",
    "：聪明消费，省心省钱。": ": Mua sắm thông minh, tiết kiệm thời gian và tiền bạc.",
    "不会被识别为自动化工具": "Không bị nhận diện là công cụ tự động hóa",
    "✨ 建议：淘宝购买更划算": "✨ Gợi ý: Mua trên Taobao tiết kiệm hơn",
    "\"帮我在淘宝、京东比价\"": "\"Giúp tôi so sánh giá trên Taobao, JD\"",
    "\"后台自动运行，不用管\"": "\"Tự động chạy nền, không cần quan tâm\"",
    "WebFetch 是什么": "WebFetch là gì",
    "技巧 2：复杂操作分步说": "Mẹo 2: Chia nhỏ thao tác phức tạp thành từng bước",
    "\"用我的密码管理器登录\"": "\"Dùng trình quản lý mật khẩu của tôi để đăng nhập\"",
    "\"帮我关注这50个账号\"": "\"Giúp tôi follow 50 tài khoản này\"",
    "，可以很好地解决这个问题。": ", có thể giải quyết vấn đề này rất tốt.",
    "安装 XFCE 和 VNC": "Cài đặt XFCE và VNC",
    "⚙️ 个人资料模式配置指南": "⚙️ Hướng dẫn cấu hình chế độ profile cá nhân",
    "对 OpenClaw 说：": "Nói với OpenClaw:",
    "🤔 为什么需要浏览器模式？": "🤔 Tại sao cần chế độ trình duyệt?",
    "\"在知乎上收藏这5个回答\"": "\"Lưu 5 câu trả lời này trên Zhihu\"",
    "你的云服务器IP:5901": "IP_cloud_server_của_bạn:5901",
    "想要拉取推文，必须先登录。": "Muốn lấy tweet, phải đăng nhập trước.",
    "点击扩展图标，切换为 ON": "Nhấp vào biểu tượng extension, chuyển sang ON",
    "⚡ 临时用一下、已有登录态": "⚡ Dùng tạm, đã có trạng thái đăng nhập",
    "自动化不是难在控制浏览器，": "Tự động hóa không khó ở chỗ điều khiển trình duyệt,",
    "🔄 打开新标签页，访问淘宝": "🔄 Mở tab mới, truy cập Taobao",
    "配置 systemd 服务": "Cấu hình dịch vụ systemd",
    "它不只是聊天工具，还可以：": "Nó không chỉ là công cụ chat, mà còn có thể:",
    "但模拟登录大概率触发验证码": "Nhưng mô phỏng đăng nhập rất có thể kích hoạt captcha",
    "🔑 获取 Token 并配置": "🔑 Lấy Token và cấu hình",
    "封装好的 Skills 能力": "Các Skills đã được đóng gói",
    "\"帮我安装和配置扩展模式。\"": "\"Giúp tôi cài đặt và cấu hình chế độ extension.\"",
    "两种模式各有优劣，先看对比：": "Hai chế độ đều có ưu nhược điểm, hãy xem so sánh trước:",
    "：临时用一下，不用重新登录。": ": Dùng tạm, không cần đăng nhập lại.",
    "OpenClaw 的操作过程": "Quy trình thao tác của OpenClaw",
    "HTTP 爬虫无法保持登录态": "HTTP crawler không thể duy trì trạng thái đăng nhập",
    "✅ 选择「AI」收藏夹，确认": "✅ Chọn bộ sưu tập \"AI\", xác nhận",
    "第 3 步：配置 Token": "Bước 3: Cấu hình Token",
    "方案二：Playwright": "Phương án 2: Playwright",
    "点击\"加载未打包的扩展程序\"": "Nhấp \"Tải extension chưa đóng gói\"",
    "💰 提取淘宝搜索结果中的价格": "💰 Trích xuất giá từ kết quả tìm kiếm trên Taobao",
    "方案一：传统 HTTP 爬虫": "Phương án 1: HTTP crawler truyền thống",
    "\"谁把这件事做成了默认能力\"": "\"ai đã biến điều này thành khả năng mặc định\"",
    "通过插件接管当前 Chrome": "Tiếp quản Chrome hiện tại qua plugin",
    "通过安装 Chrome 扩展 ": "Bằng cách cài đặt Chrome extension ",
    "，它在大部分场景下是最全能的。": ", nó là lựa chọn toàn diện nhất trong hầu hết các tình huống.",
    "技巧 1：先激活扩展，再下指令": "Mẹo 1: Kích hoạt extension trước, rồi mới ra lệnh",
    "✅ 直到完成 5 个回答的收藏": "✅ Cho đến khi lưu xong 5 câu trả lời",
    "手动启动 Chrome 并登录": "Khởi động Chrome thủ công và đăng nhập",
    "案例 1：在知乎上批量收藏回答": "Ví dụ 1: Lưu hàng loạt câu trả lời trên Zhihu",
    "：✅在需要登录的场景下更稳定。": ": ✅ Ổn định hơn trong tình huống cần đăng nhập.",
    "🔐 操作敏感账号（网银、支付）": "🔐 Thao tác tài khoản nhạy cảm (internet banking, thanh toán)",
    "直接对 OpenClaw 说：": "Nói trực tiếp với OpenClaw:",
    "，就能看到 XFCE 桌面了。": ", là bạn có thể thấy desktop XFCE rồi.",
    "✅ 滚动到第二个回答，重复操作": "✅ Cuộn đến câu trả lời thứ hai, lặp lại thao tác",
    "💵 当前平台价格：¥9,999": "💵 Giá trên nền tảng hiện tại: ¥9.999",
    "难在把浏览器长期、稳定地跑起来。": "Khó ở chỗ làm cho trình duyệt chạy ổn định, lâu dài.",
    "OpenClaw 提供两种方式：": "OpenClaw cung cấp hai cách:",
    "OpenClaw 会引导你完成：": "OpenClaw sẽ hướng dẫn bạn hoàn thành:",
    "然后让 OpenClaw 继续。": "Sau đó cho OpenClaw tiếp tục.",
    "：扩展需要在已打开的网页上工作。": ": Extension cần hoạt động trên trang web đã mở.",
    "📦 提取当前页面的商品名称和价格": "📦 Trích xuất tên và giá sản phẩm trên trang hiện tại",
    "WebFetch 解决不了的场景": "Tình huống WebFetch không giải quyết được",
    "⚠️ 风险较高（操作你的日常账号）": "⚠️ Rủi ro khá cao (thao tác trên tài khoản thường ngày của bạn)",
    "🤖 需要登录、24小时无人值守运行": "🤖 Cần đăng nhập, chạy 24 giờ không cần giám sát",
    "浏览器是真实 Chrome，没有 ": "Trình duyệt là Chrome thật, không có ",
    "在 Chrome 中打开商品详情页": "Mở trang chi tiết sản phẩm trong Chrome",
    "✅ 找到第一个回答的收藏按钮，点击": "✅ Tìm nút lưu của câu trả lời đầu tiên, nhấp vào",
    "\"每天早上9点抓取 X 热点话题\"": "\"Mỗi sáng 9 giờ thu thập chủ đề hot trên X\"",
    "如果你是工程师，可以自己写脚本实现；": "Nếu bạn là kỹ sư, bạn có thể tự viết script để thực hiện;",
    "X.com 的推文需要登录才能查看。": "Tweet trên X.com cần đăng nhập mới xem được.",
    "方案三：OpenClaw 浏览器模式": "Phương án 3: Chế độ trình duyệt OpenClaw",
    "Playwright 启动的浏览器，": "Trình duyệt do Playwright khởi động,",
    "也正因为这样，它最近变得很火——  ": "Cũng chính vì vậy, gần đây nó trở nên rất hot —  ",
    "OpenClaw 内置了两种浏览器模式": "OpenClaw tích hợp sẵn hai chế độ trình duyệt",
    "在 Chrome 中打开知乎搜索结果页": "Mở trang kết quả tìm kiếm Zhihu trong Chrome",
    "Claude Code（编程开发工具）": "Claude Code (công cụ lập trình phát triển)",
    "如果任务比较复杂，建议分步指令。比如：": "Nếu tác vụ phức tạp, nên chia thành từng bước. Ví dụ:",
    "⚙️ 修改 OpenClaw 配置文件": "⚙️ Chỉnh sửa file cấu hình OpenClaw",
    "Playwright（浏览器控制工具）": "Playwright (công cụ điều khiển trình duyệt)",
    "需要登录、24 小时运行、操作敏感账号": "Cần đăng nhập, chạy 24 giờ, thao tác tài khoản nhạy cảm",
    "📖 读取当前页面的 Issues 列表": "📖 Đọc danh sách Issues trên trang hiện tại",
    "🌐 启动 Chrome 并帮你登录网站": "🌐 Khởi động Chrome và giúp bạn đăng nhập website",
    "🖱️ 需要交互的操作（点击、滚动、翻页）": "🖱️ Thao tác cần tương tác (nhấp, cuộn, chuyển trang)",
    "激活 OpenClaw Relay 扩展": "Kích hoạt extension OpenClaw Relay",
    "回到 OpenClaw 对话窗口，下指令": "Quay lại cửa sổ hội thoại OpenClaw, ra lệnh",
    "不需要模拟登录，直接使用已有的登录态操作": "Không cần mô phỏng đăng nhập, trực tiếp sử dụng trạng thái đăng nhập hiện có",
    "第 2 步：在 Chrome 中加载扩展": "Bước 2: Tải extension vào Chrome",
    "我发现上面的帖子链接不对，我继续跟它说：": "Tôi phát hiện link bài viết phía trên không đúng, tôi tiếp tục nói với nó:",
    "接下来，Playwright 的工作原理": "Tiếp theo, nguyên lý hoạt động của Playwright",
    "前者给你一段脚本，后者直接帮你完成操作。": "Cái trước cho bạn một đoạn script, cái sau trực tiếp giúp bạn hoàn thành thao tác.",
    "OpenClaw 会告诉你\"遇到验证码\"": "OpenClaw sẽ thông báo \"gặp captcha\"",
    "。如果设置错了，Chrome 启动不了。": ". Nếu cài đặt sai, Chrome sẽ không khởi động được.",
    "Claude Code 是帮你写代码的  ": "Claude Code giúp bạn viết code  ",
    "复制显示的 Token，粘贴到扩展配置中。": "Sao chép Token hiển thị, dán vào cấu hình extension.",
    "通过插件接管你当前正在使用的 Chrome": "Tiếp quản Chrome bạn đang sử dụng qua plugin",
    "OpenClaw 会引导你完成配置，包括：": "OpenClaw sẽ hướng dẫn bạn hoàn thành cấu hình, bao gồm:",
    "，风控系统更难区分是人工操作还是自动化操作": ", hệ thống kiểm soát rủi ro khó phân biệt hơn giữa thao tác thủ công và tự động hóa",
    "OpenClaw 是帮你把事情执行掉的  ": "OpenClaw giúp bạn thực thi công việc  ",
    "这里的关键不在于\"谁能控制浏览器\"，而在于": "Điểm mấu chốt ở đây không phải \"ai có thể điều khiển trình duyệt\", mà là",
    "，而且\"手动拉验证码也 100% 失败\"。": ", hơn nữa \"kéo captcha thủ công cũng 100% thất bại\".",
    "📖 告诉你如何在 Chrome 中加载扩展": "📖 Hướng dẫn bạn cách tải extension vào Chrome",
    "📥 下载 OpenClaw Relay 扩展": "📥 Tải xuống extension OpenClaw Relay",
    "OpenClaw 把这件事，变成了默认能力。": "OpenClaw đã biến điều này thành khả năng mặc định.",
    "：🤖 无头模式，后台运行（登录完成后可切换）": ": 🤖 Chế độ headless, chạy nền (có thể chuyển sau khi đăng nhập xong)",
    "帖子链接不对，应该是文章详情页的链接，形如 ": "Link bài viết không đúng, phải là link trang chi tiết bài viết, dạng như ",
    "点击 OpenClaw Relay 扩展图标": "Nhấp vào biểu tượng extension OpenClaw Relay",
    "🛒 淘宝最低价：¥9,299（省 ¥700）": "🛒 Giá thấp nhất Taobao: ¥9.299 (tiết kiệm ¥700)",
    "⚡ 需要执行 JavaScript 的动态内容": "⚡ Nội dung động cần thực thi JavaScript",
    "Skills：把这些操作打包成\"一个现成功能\"": "Skills: Đóng gói các thao tác này thành \"một chức năng sẵn có\"",
    "告诉 OpenClaw \"验证码已完成，继续\"": "Nói với OpenClaw \"captcha đã hoàn thành, tiếp tục\"",
    "🔌 扩展模式 --- 适合临时操作、已有登录态": "🔌 Chế độ extension --- Phù hợp thao tác tạm thời, đã có trạng thái đăng nhập",
    "在云服务器上运行个人资料模式，需要有图形界面。": "Để chạy chế độ profile cá nhân trên cloud server, cần có giao diện đồ họa.",
    "🖥️ 个人资料模式 --- 适合自动化、定时任务": "🖥️ Chế độ profile cá nhân --- Phù hợp tự động hóa, tác vụ định kỳ",
    "OpenClaw 启动独立的 Chrome 实例": "OpenClaw khởi động instance Chrome độc lập",
    "🔍 检查你的环境（是否安装了 XFCE、VNC）": "🔍 Kiểm tra môi trường của bạn (đã cài XFCE, VNC chưa)",
    "：你在某电商平台看中一个商品，想和其他平台比价。": ": Bạn thấy một sản phẩm trên sàn thương mại điện tử, muốn so sánh giá với các nền tảng khác.",
    "📊 提取每个 Issue 的标题、状态、创建时间": "📊 Trích xuất tiêu đề, trạng thái, thời gian tạo của mỗi Issue",
    "🎯 回到自动化的场景：想从 X.com 拉取推文": "🎯 Quay lại tình huống tự động hóa: Muốn lấy tweet từ X.com",
    "扩展必须在一个已打开的网页上激活才能工作。步骤：": "Extension phải được kích hoạt trên một trang web đã mở mới hoạt động được. Các bước:",
    "如果着急了，想直接看怎么配置，点击跳到配置章节：": "Nếu bạn nóng lòng, muốn xem ngay cách cấu hình, nhấp để chuyển đến phần cấu hình:",
    "OpenClaw 通过 CDP 协议接管这个浏览器": "OpenClaw tiếp quản trình duyệt này qua giao thức CDP",
    "云服务器跑 OpenClaw，浏览器自动化怎么搞？": "Chạy OpenClaw trên cloud server, tự động hóa trình duyệt làm thế nào?",
    "OpenClaw 的优势并不是底层协议不同，而是它": "Ưu điểm của OpenClaw không phải ở giao thức nền tảng khác nhau, mà là nó",
    "（不需要开新窗口再登录，再一层层点击才到当前页面）": "(Không cần mở cửa sổ mới rồi đăng nhập lại, rồi nhấp từng lớp mới đến trang hiện tại)",
    "⚠️ 需要额外配置（可通过持久化浏览器目录实现） ": "⚠️ Cần cấu hình thêm (có thể thực hiện qua việc lưu trữ thư mục trình duyệt) ",
    "\"帮我在 GitHub 查看最近的 Issues\"": "\"Giúp tôi xem các Issues gần đây trên GitHub\"",
    "第三步：\"把结果整理成 Markdown 格式。\"": "Bước 3: \"Sắp xếp kết quả thành định dạng Markdown.\"",
    "📄 如果列表不够 10 个，自动点击\"Next\"翻页": "📄 Nếu danh sách không đủ 10 mục, tự động nhấp \"Next\" chuyển trang",
    "：🖥️ 有头模式，能看到浏览器窗口（首次登录时必须）": ": 🖥️ Chế độ có giao diện, có thể thấy cửa sổ trình duyệt (bắt buộc khi đăng nhập lần đầu)",
    "在 Chrome 中打开 GitHub（确保已登录）": "Mở GitHub trong Chrome (đảm bảo đã đăng nhập)",
    "一句话：个人资料模式适合自动化，扩展模式适合临时用。": "Một câu: Chế độ profile cá nhân phù hợp tự động hóa, chế độ extension phù hợp dùng tạm.",
    "\"帮我登录网站 A，然后抓取数据，再发邮件通知我。\"": "\"Giúp tôi đăng nhập website A, sau đó thu thập dữ liệu, rồi gửi email thông báo cho tôi.\"",
    "\"把当前页面前 5 个回答都收藏到「AI」收藏夹。\"": "\"Lưu 5 câu trả lời đầu tiên trên trang hiện tại vào bộ sưu tập \"AI\".\"",
    "：启动一个真实的浏览器（无头或有头），模拟用户操作。": ": Khởi động một trình duyệt thật (headless hoặc có giao diện), mô phỏng thao tác người dùng.",
    "所以，当你需要登录、需要交互时，就需要用到浏览器模式。": "Vì vậy, khi bạn cần đăng nhập, cần tương tác, thì cần dùng chế độ trình duyệt.",
    "登录是手动完成的，验证码也是手动过的，和正常使用没区别": "Đăng nhập được thực hiện thủ công, captcha cũng được xử lý thủ công, không khác gì sử dụng bình thường",
    "AI 不再只是\"告诉你怎么做\"，而是\"帮你真的去做\"。": "AI không còn chỉ \"cho bạn biết phải làm gì\", mà \"giúp bạn thực sự làm điều đó\".",
    "Claude Code：在这里写代码、调用这些现成功能": "Claude Code: Viết code ở đây, gọi các chức năng sẵn có này",
    "案例 2：在已登录的 GitHub 上查看 Issues": "Ví dụ 2: Xem Issues trên GitHub đã đăng nhập",
    "对 OpenClaw 说：\"拉取首页最新 20 条推文\"": "Nói với OpenClaw: \"Lấy 20 tweet mới nhất trên trang chủ\"",
    "：直接向服务器发 HTTP 请求，获取 HTML 内容。": ": Gửi trực tiếp HTTP request đến server, lấy nội dung HTML.",
    "：接管你当前正在使用的 Chrome，直接用已有的登录态": ": Tiếp quản Chrome bạn đang sử dụng, dùng trực tiếp trạng thái đăng nhập hiện có",
    "激活 OpenClaw Relay 扩展（切换为 ON）": "Kích hoạt extension OpenClaw Relay (chuyển sang ON)",
    "在你的电脑上打开终端，SSH 连接到云服务器，然后执行：": "Mở terminal trên máy tính của bạn, kết nối SSH đến cloud server, sau đó thực thi:",
    "：你在知乎搜索了一个话题，想把前 5 个回答都收藏起来。": ": Bạn tìm kiếm một chủ đề trên Zhihu, muốn lưu 5 câu trả lời đầu tiên.",
    "我们最终就纠正了帖子的链接地址，重新得到正确的 URL。": "Cuối cùng chúng tôi đã sửa đúng địa chỉ link bài viết, nhận được URL chính xác.",
    "🔒 需要登录的网站（X、Reddit、YouTube 等）": "🔒 Website cần đăng nhập (X, Reddit, YouTube, v.v.)",
    "直接上实操：用个人资料模式读取 scys.com 最新文章": "Thực hành ngay: Dùng chế độ profile cá nhân đọc bài viết mới nhất trên scys.com",
    "：启动独立的 Chrome 实例，登录一次后长期保持登录态": ": Khởi động instance Chrome độc lập, đăng nhập một lần rồi duy trì trạng thái đăng nhập lâu dài",
    "如果你第一次听到 OpenClaw，可以先用一句话理解它：": "Nếu bạn lần đầu nghe về OpenClaw, có thể hiểu nó bằng một câu:",
    "我对 OpenClaw 说（目的就是拉取本周的精华文章）：": "Tôi nói với OpenClaw (mục đích là lấy bài viết tinh hoa trong tuần):",
    "现在，你可以告诉 OpenClaw 在当前页面上执行操作了。": "Bây giờ, bạn có thể yêu cầu OpenClaw thực hiện thao tác trên trang hiện tại.",
    "✅ 方式一：和 OpenClaw 对话，让它帮你配置（推荐）": "✅ Cách 1: Trò chuyện với OpenClaw, để nó giúp bạn cấu hình (Khuyến nghị)",
    "📱 商品名称：iPhone 15 Pro Max 256GB": "📱 Tên sản phẩm: iPhone 15 Pro Max 256GB",
    "它提示我需要微信扫码登录，掏出手机扫描，登录成功后，告诉它：": "Nó nhắc tôi cần quét mã WeChat để đăng nhập, lấy điện thoại ra quét, sau khi đăng nhập thành công, nói với nó:",
    "Playwright：负责\"怎么操作浏览器\"（点、填、抓数据）": "Playwright: Phụ trách \"cách thao tác trình duyệt\" (nhấp, điền, thu thập dữ liệu)",
    "用户不需要自己写代码管理浏览器目录，也不需要自己维护自动化脚本。": "Người dùng không cần tự viết code quản lý thư mục trình duyệt, cũng không cần tự duy trì script tự động hóa.",
    "🔄 配置 systemd 服务（设置 DISPLAY 环境变量）": "🔄 Cấu hình dịch vụ systemd (thiết lập biến môi trường DISPLAY)",
    "点击间隔固定、无鼠标移动轨迹，这些\"机器人行为\"会被风控系统识别。": "Khoảng cách nhấp cố định, không có quỹ đạo di chuyển chuột, những \"hành vi robot\" này sẽ bị hệ thống kiểm soát rủi ro nhận diện.",
    "\"提取这个商品的价格、名称，然后打开淘宝搜索同名商品，比较价格。\"": "\"Trích xuất giá và tên sản phẩm này, sau đó mở Taobao tìm kiếm sản phẩm cùng tên, so sánh giá.\"",
    "登录完成后，以后 OpenClaw 就可以用这个登录态自动操作了。": "Sau khi đăng nhập xong, từ nay OpenClaw có thể dùng trạng thái đăng nhập này để thao tác tự động.",
    "如果你是普通用户，OpenClaw 已经帮你把这层复杂度隐藏好了。": "Nếu bạn là người dùng thông thường, OpenClaw đã giúp bạn ẩn đi lớp phức tạp này.",
    "OpenClaw 启动独立的 Chrome 实例，有独立的用户目录": "OpenClaw khởi động instance Chrome độc lập, có thư mục người dùng riêng",
    "你手动打开 Chrome，正常登录 X.com（和你平时刷推特一样）": "Bạn mở Chrome thủ công, đăng nhập X.com bình thường (giống như bạn lướt Twitter hàng ngày)",
    "：操作需要登录的网站，OpenClaw 的浏览器模式是最稳妥的选择。": ": Để thao tác trên website cần đăng nhập, chế độ trình duyệt của OpenClaw là lựa chọn ổn định nhất.",
    "下左图：自己本地安装的软件 VNC Viewer，发起对服务器的连接": "Hình trái dưới: Phần mềm VNC Viewer cài trên máy local, kết nối đến server",
    "很多人会问，它和 Claude Code 有什么区别？简单区分一下：": "Nhiều người sẽ hỏi, nó khác gì với Claude Code? Phân biệt đơn giản:",
    "安装完成后，就能在自己的本地电脑上看到服务器的桌面和正在启动的浏览器": "Sau khi cài đặt xong, bạn có thể thấy desktop của server và trình duyệt đang khởi động trên máy tính local",
    "把\"持久浏览器环境 + 登录状态管理 + 任务调度\"做成了默认能力。": "đã biến \"môi trường trình duyệt bền vững + quản lý trạng thái đăng nhập + lập lịch tác vụ\" thành khả năng mặc định.",
    "：你想快速查看某个仓库最近有哪些 Issues，但不想一个个点进去看。": ": Bạn muốn xem nhanh repository gần đây có những Issues nào, nhưng không muốn nhấp vào từng cái.",
    "OpenClaw 是一个能\"自己去操作电脑和网站\"的 AI 执行系统。": "OpenClaw là một hệ thống thực thi AI có thể \"tự thao tác máy tính và website\".",
    "，让 OpenClaw 能够控制你当前正在使用的 Chrome 浏览器。": ", để OpenClaw có thể điều khiển trình duyệt Chrome bạn đang sử dụng.",
    "\"帮我在当前页面查看最近 10 个 Issues，列出标题、状态、创建时间。\"": "\"Giúp tôi xem 10 Issues gần đây trên trang hiện tại, liệt kê tiêu đề, trạng thái, thời gian tạo.\"",
    "就能实现，拿着手机躺着床上，和飞书吹吹水，就能把事情给干了，想想都安逸 😁😁😁": "Bạn có thể nằm trên giường cầm điện thoại, chat qua Feishu, là xong việc, nghĩ thôi cũng sướng 😁😁😁",
    "：一个网页抓取和正文提取的工具，能把 HTML 转成干净的 Markdown。": ": Một công cụ thu thập trang web và trích xuất nội dung chính, có thể chuyển HTML thành Markdown sạch.",
    "而 Claude Code 是可以调用和使用这些 Skills 的编程开发工具。": "Còn Claude Code là công cụ lập trình phát triển có thể gọi và sử dụng các Skills này.",
    "当它接入飞书等系统后，就可以自动发消息、读取群内容、执行流程，实现真正的远程互动。": "Khi nó kết nối với các hệ thống như Feishu, có thể tự động gửi tin nhắn, đọc nội dung nhóm, thực thi quy trình, thực hiện tương tác từ xa thực sự.",
    "扩展模式下，你可以随时在浏览器上手动操作。比如 OpenClaw 卡住了，你可以：": "Trong chế độ extension, bạn có thể thao tác thủ công trên trình duyệt bất cứ lúc nào. Ví dụ OpenClaw bị kẹt, bạn có thể:",
    "下右图：在自己本地看到的服务器的桌面，服务器启动 Chrome，并登录 x.com": "Hình phải dưới: Desktop server nhìn từ máy local, server khởi động Chrome và đăng nhập x.com",
    "\"云服务器没有 Mac 好用，因为没有图形界面，很多需要浏览器的操作做不了怎么办？\"": "\"Cloud server không tiện bằng Mac, vì không có giao diện đồ họa, nhiều thao tác cần trình duyệt không làm được thì phải làm sao?\"",
    "第一步：\"帮我登录网站 A。\"（等完成）\n第二步：\"抓取首页的公告列表。\"（等完成）\n": "Bước 1: \"Giúp tôi đăng nhập website A.\" (đợi hoàn thành)\nBước 2: \"Thu thập danh sách thông báo trên trang chủ.\" (đợi hoàn thành)\n",
    "确实，云服务器默认只有命令行，看不到浏览器窗口，好像没法做需要\"点击、滚动、登录\"的操作。": "Đúng vậy, cloud server mặc định chỉ có dòng lệnh, không thấy cửa sổ trình duyệt, dường như không thể thực hiện các thao tác cần \"nhấp, cuộn, đăng nhập\".",
    "，默认配置下，容易暴露自动化特征（例如 navigator.webdriver），从而被识别。": ", với cấu hình mặc định, dễ bị lộ đặc điểm tự động hóa (ví dụ navigator.webdriver), từ đó bị nhận diện.",
    "安装完成后，在你的电脑上打开 VNC Viewer（需要自己在本地电脑手动安装），连接地址填 ": "Sau khi cài đặt xong, mở VNC Viewer trên máy tính của bạn (cần tự cài thủ công trên máy local), điền địa chỉ kết nối ",
    "短时间内多次请求，IP 直接被封。有开发者反馈\"IP 封禁频率从每天 3 次激增到每小时 5 次\"。": "Gửi nhiều request trong thời gian ngắn, IP bị chặn ngay. Có nhà phát triển phản hồi \"tần suất chặn IP tăng vọt từ 3 lần/ngày lên 5 lần/giờ\".",
    "有开发者的 Playwright 爬虫\"稳定运行一周后突然罢工\"，每次都弹出\"当前环境正在被测试\"。": "Crawler Playwright của một nhà phát triển \"chạy ổn định một tuần rồi đột ngột ngừng hoạt động\", mỗi lần đều hiện \"môi trường hiện tại đang bị kiểm tra\".",
    "OpenClaw 内置的 WebFetch 工具已经能抓取很多网页内容了，为什么还需要浏览器模式呢？": "Công cụ WebFetch tích hợp sẵn của OpenClaw đã có thể thu thập nội dung nhiều trang web, vậy tại sao còn cần chế độ trình duyệt?",
    "Playwright 给的是能力本身，而 OpenClaw 给的是一整套可直接使用的浏览器运行模式。": "Playwright cung cấp bản thân khả năng, còn OpenClaw cung cấp một bộ chế độ vận hành trình duyệt hoàn chỉnh có thể sử dụng ngay.",
    "：DISPLAY 告诉程序\"把窗口画在哪个屏幕上\"。XFCE 通过 VNC 创建的\"虚拟屏幕\"通常是 ": ": DISPLAY cho chương trình biết \"vẽ cửa sổ trên màn hình nào\". \"Màn hình ảo\" mà XFCE tạo qua VNC thường là ",
    "估计，有人会有疑问：Playwright 和 Claude Code 有啥关系，和 Skills 有是啥关系？": "Có lẽ, sẽ có người thắc mắc: Playwright có liên quan gì với Claude Code, và có liên quan gì với Skills?",
    "最压缩版总结：Playwright 负责干活，Skills 负责定义功能，Claude Code 负责使用这些功能。": "Tóm tắt ngắn nhất: Playwright phụ trách làm việc, Skills phụ trách định nghĩa chức năng, Claude Code phụ trách sử dụng các chức năng đó.",
    "：通过 Chrome DevTools Protocol（CDP）控制浏览器，在扩展模式下，是接管已经运行的真实浏览器环境。": ": Điều khiển trình duyệt qua Chrome DevTools Protocol (CDP), trong chế độ extension, là tiếp quản môi trường trình duyệt thật đang chạy.",
    "Playwright 是底层浏览器控制工具；Skills 是基于它封装好的能力模块，例如 Browser Use 这类开源项目。": "Playwright là công cụ điều khiển trình duyệt tầng thấp; Skills là module khả năng được đóng gói dựa trên nó, ví dụ các dự án mã nguồn mở như Browser Use.",
    "现在，假设你想从 X.com（Twitter）拉取某个话题下的推文，这是很常见的需求。但用不同的技术方案，会遇到完全不同的困境。": "Bây giờ, giả sử bạn muốn lấy tweet theo một chủ đề trên X.com (Twitter), đây là nhu cầu rất phổ biến. Nhưng với các phương án kỹ thuật khác nhau, bạn sẽ gặp những khó khăn hoàn toàn khác nhau.",
    "X.com 是单页应用（SPA），推文内容靠 JavaScript 动态加载。HTTP 请求返回的 HTML 是空的，根本没有推文数据。": "X.com là ứng dụng trang đơn (SPA), nội dung tweet được tải động bằng JavaScript. HTML trả về từ HTTP request là rỗng, hoàn toàn không có dữ liệu tweet.",
    "：云服务器默认只有终端，像一台没有屏幕的电脑。XFCE 相当于给它装了一个桌面系统，你通过 VNC 连接后，就像在远程操作一台完整的电脑。": ": Cloud server mặc định chỉ có terminal, giống như một chiếc máy tính không có màn hình. XFCE tương đương với việc cài cho nó một hệ thống desktop, sau khi bạn kết nối qua VNC, giống như đang điều khiển từ xa một chiếc máy tính hoàn chỉnh.",
    " 拉取本周的帖子，一个帖子一个帖子的单独发送给我（不要全部总结完，一起发），格式：标题、核心总结、作者、发布日期、帖子链接、飞书文档的原文链接": " lấy bài viết trong tuần, gửi cho tôi từng bài một (đừng tổng hợp hết rồi gửi một lần), định dạng: tiêu đề, tóm tắt cốt lõi, tác giả, ngày đăng, link bài viết, link bài gốc trên Feishu",
    "然后通过 VNC 连接到云服务器，你会看到 Chrome 浏览器窗口打开了。在浏览器里登录你需要的网站（X、Reddit、YouTube 等）。": "Sau đó kết nối VNC đến cloud server, bạn sẽ thấy cửa sổ trình duyệt Chrome đã mở. Đăng nhập vào các website bạn cần trong trình duyệt (X, Reddit, YouTube, v.v.).",
    "：VNC 是远程桌面连接工具。你在自己的电脑上安装 VNC 客户端（比如 TigerVNC、RealVNC），连接到云服务器，就能看到云服务器上的桌面画面。": ": VNC là công cụ kết nối desktop từ xa. Bạn cài VNC client trên máy tính của mình (ví dụ TigerVNC, RealVNC), kết nối đến cloud server, là có thể thấy giao diện desktop trên cloud server.",
    "\"帮我在云服务器上配置个人资料模式。我需要安装 XFCE 桌面环境、TigerVNC 远程桌面、配置 DISPLAY 环境变量，然后启动 Chrome 浏览器。\"": "\"Giúp tôi cấu hình chế độ profile cá nhân trên cloud server. Tôi cần cài đặt XFCE desktop environment, TigerVNC remote desktop, cấu hình biến môi trường DISPLAY, sau đó khởi động trình duyệt Chrome.\"",
    # Smart-quote variants (U+201C / U+201D)
    "OpenClaw 是一个能\u201c自己去操作电脑和网站\u201d的 AI 执行系统。": "OpenClaw là một hệ thống thực thi AI có thể \u201ctự thao tác máy tính và website\u201d.",
    "AI 不再只是\u201c告诉你怎么做\u201d，而是\u201c帮你真的去做\u201d。": "AI không còn chỉ \u201ccho bạn biết phải làm gì\u201d, mà \u201cgiúp bạn thực sự làm điều đó\u201d.",
    "Playwright：负责\u201c怎么操作浏览器\u201d（点、填、抓数据）": "Playwright: Phụ trách \u201ccách thao tác trình duyệt\u201d (nhấp, điền, thu thập dữ liệu)",
    "Skills：把这些操作打包成\u201c一个现成功能\u201d": "Skills: Đóng gói các thao tác này thành \u201cmột chức năng sẵn có\u201d",
    "把\u201c持久浏览器环境 + 登录状态管理 + 任务调度\u201d做成了默认能力。": "đã biến \u201cmôi trường trình duyệt bền vững + quản lý trạng thái đăng nhập + lập lịch tác vụ\u201d thành khả năng mặc định.",
    "这里的关键不在于\u201c谁能控制浏览器\u201d，而在于": "Điểm mấu chốt ở đây không phải \u201cai có thể điều khiển trình duyệt\u201d, mà là",
    "\u201c谁把这件事做成了默认能力\u201d": "\u201cai đã biến điều này thành khả năng mặc định\u201d",
}

# Load original
with open('_art_b7_1_orig.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

def has_chinese(text):
    return bool(re.search(r'[\u4e00-\u9fff]', text))

# Apply translations
trans_data = copy.deepcopy(data)
translated_count = 0
kept_count = 0
total_text_runs = 0

for block in trans_data['blocks']:
    for el in block['elements']:
        if el['type'] == 'text_run':
            total_text_runs += 1
            content = el['content']
            if content in TRANS:
                el['content'] = TRANS[content]
                translated_count += 1
            elif content.strip() and has_chinese(content):
                # Try to find a close match
                print(f"WARNING: No translation for: {repr(content)}")
                kept_count += 1
            else:
                kept_count += 1

    # Add space between adjacent Vietnamese text_runs
    new_elements = []
    for i, el in enumerate(block['elements']):
        new_elements.append(el)
        # Check if we need space between this and next text_run
        if (i < len(block['elements']) - 1 and
            el['type'] == 'text_run' and
            block['elements'][i+1]['type'] == 'text_run'):
            curr = el['content']
            next_c = block['elements'][i+1]['content']
            # Add space if current doesn't end with space/newline and next doesn't start with space/punctuation
            if (curr and next_c and
                not curr.endswith((' ', '\n', '\t')) and
                not next_c.startswith((' ', '\n', '\t', ':', ',', '.', '!', '?', ')', ']', '}', '」', '、', '，', '。', '！', '？'))):
                # Check they are both non-empty after strip
                if curr.strip() and next_c.strip():
                    el['content'] = curr + ' '
    block['elements'] = new_elements

# Save
with open('_art_b7_1_trans.json', 'w', encoding='utf-8') as f:
    json.dump(trans_data, f, ensure_ascii=False, indent=2)

print(f"Total text_runs: {total_text_runs}")
print(f"Translated: {translated_count}")
print(f"Kept as-is: {kept_count}")
print(f"Saved to _art_b7_1_trans.json")
