#!/usr/bin/env python3
"""Translate article 1 from Chinese to Vietnamese using auto-translate + manual overrides."""
import json, sys, re, copy
sys.stdout.reconfigure(encoding='utf-8')

with open('_c1_art1_orig.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

def has_cn(t):
    return bool(re.search(r'[\u4e00-\u9fff\u3400-\u4dbf]', t))

# Get unique Chinese texts
seen = set()
unique = []
for block in data['blocks']:
    for elem in block.get('elements', []):
        c = elem.get('content', '')
        if has_cn(c) and c not in seen:
            seen.add(c)
            unique.append(c)

print(f'Unique Chinese texts: {len(unique)}')

def auto_tr(text):
    """Auto-translate common Chinese patterns to Vietnamese."""
    t = text
    reps = [
        ('智能纪要', 'Biên bản thông minh'),
        ('直播回放', 'Phát lại livestream'),
        ('直播嘉宾', 'Khách mời livestream'),
        ('直播核心亮点', 'Điểm nổi bật cốt lõi'),
        ('直播亮点', 'Điểm nổi bật livestream'),
        ('视频教程', 'Video hướng dẫn'),
        ('特邀嘉宾', 'Khách mời đặc biệt'),
        ('直播总结', 'Tóm tắt livestream'),
        ('文字记录', 'Bản ghi văn bản'),
        ('晚8点共学', 'học chung lúc 8 giờ tối'),
        ('保姆级教程', 'Hướng dẫn chi tiết từ A-Z'),
        ('手把手教你', 'Hướng dẫn từng bước'),
        ('手把手带你', 'Hướng dẫn từng bước'),
        ('手把手', 'từng bước'),
        ('零基础', 'từ zero'),
        ('零门槛', 'không rào cản'),
        ('小白也能', 'người mới cũng có thể'),
        ('小白', 'người mới'),
        ('部署教程', 'Hướng dẫn triển khai'),
        ('部署指南', 'Hướng dẫn triển khai'),
        ('安装教程', 'Hướng dẫn cài đặt'),
        ('安装配置', 'Cài đặt và cấu hình'),
        ('使用教程', 'Hướng dẫn sử dụng'),
        ('配置指南', 'Hướng dẫn cấu hình'),
        ('避坑指南', 'Hướng dẫn tránh bẫy'),
        ('实战攻略', 'Chiến lược thực chiến'),
        ('实战案例', 'Case thực chiến'),
        ('实战技巧', 'Kỹ năng thực chiến'),
        ('实战复盘', 'Phân tích thực chiến'),
        ('实战课', 'Khóa thực chiến'),
        ('实战分享', 'Chia sẻ thực chiến'),
        ('实战指南', 'Hướng dẫn thực chiến'),
        ('全攻略', 'toàn diện'),
        ('全流程', 'toàn bộ quy trình'),
        ('全程实操', 'Thực hành toàn bộ'),
        ('深度解析', 'Phân tích chuyên sâu'),
        ('深度解读', 'Giải đọc chuyên sâu'),
        ('深度实测', 'Đánh giá chuyên sâu'),
        ('技术架构', 'kiến trúc kỹ thuật'),
        ('拆解', 'phân tích'),
        ('正式发布', 'chính thức ra mắt'),
        ('正式上线', 'chính thức ra mắt'),
        ('火爆全网', 'gây bão toàn mạng'),
        ('爆款', 'hot trend'),
        ('一键部署', 'triển khai một chạm'),
        ('一键', 'một chạm'),
        ('一站式', 'tất cả trong một'),
        ('一句话', 'một câu lệnh'),
        ('开源', 'mã nguồn mở'),
        ('全球首发', 'ra mắt toàn cầu'),
        ('首发', 'ra mắt đầu tiên'),
        ('首个', 'đầu tiên'),
        ('联合创始人', 'Đồng sáng lập'),
        ('创始人', 'Nhà sáng lập'),
        ('产品经理', 'Quản lý sản phẩm'),
        ('产品负责人', 'Phụ trách sản phẩm'),
        ('增长负责人', 'Phụ trách tăng trưởng'),
        ('技术开发', 'Phát triển kỹ thuật'),
        ('算法工程师', 'Kỹ sư thuật toán'),
        ('独立开发者', 'Nhà phát triển độc lập'),
        ('内容创作者', 'Nhà sáng tạo nội dung'),
        ('自媒体人', 'Nhà sáng tạo nội dung'),
        ('自媒体', 'truyền thông cá nhân'),
        ('大模型', 'mô hình lớn'),
        ('小龙虾', 'tôm hùm'),
        ('龙虾', 'tôm hùm'),
        ('虾宝', 'bé tôm'),
        ('养虾', 'nuôi tôm'),
        ('搓虾', 'chế tạo tôm'),
        ('飞书', 'Feishu'),
        ('扣子空间', 'Coze Space'),
        ('扣子', 'Coze'),
        ('百炼', 'Bách Luyện'),
        ('百度智能云', 'Baidu Smart Cloud'),
        ('百度', 'Baidu'),
        ('千帆', 'Qianfan'),
        ('秒哒', 'Miaoda'),
        ('阿里', 'Alibaba'),
        ('腾讯', 'Tencent'),
        ('字节', 'ByteDance'),
        ('通义灵码', 'Tongyi Lingma'),
        ('通义', 'Tongyi'),
        ('文心', 'Wenxin'),
        ('千问', 'Qwen'),
        ('智能体', 'Agent thông minh'),
        ('工作流', 'workflow'),
        ('工作空间', 'workspace'),
        ('工作台', 'workspace'),
        ('知识管理体系', 'hệ thống quản lý tri thức'),
        ('知识管理', 'quản lý tri thức'),
        ('数据分析', 'phân tích dữ liệu'),
        ('营销增长', 'tăng trưởng marketing'),
        ('内容营销', 'content marketing'),
        ('营销', 'marketing'),
        ('增长策略', 'chiến lược tăng trưởng'),
        ('增长', 'tăng trưởng'),
        ('获客', 'thu hút khách hàng'),
        ('变现教学', 'hướng dẫn kiếm tiền'),
        ('变现', 'kiếm tiền'),
        ('赚钱', 'kiếm tiền'),
        ('应用生成', 'tạo ứng dụng'),
        ('应用开发', 'phát triển ứng dụng'),
        ('应用变现', 'ứng dụng kiếm tiền'),
        ('应用', 'ứng dụng'),
        ('训练营', 'bootcamp'),
        ('进阶实战', 'thực chiến nâng cao'),
        ('进阶教程', 'hướng dẫn nâng cao'),
        ('进阶', 'nâng cao'),
        ('入门', 'nhập môn'),
        ('教程', 'hướng dẫn'),
        ('教学系列', 'series hướng dẫn'),
        ('教学', 'giảng dạy'),
        ('分享人', 'Người chia sẻ'),
        ('分享嘉宾', 'Khách mời chia sẻ'),
        ('分享', 'chia sẻ'),
        ('解锁', 'mở khóa'),
        ('打造', 'xây dựng'),
        ('搭建', 'xây dựng'),
        ('构建', 'xây dựng'),
        ('重构', 'tái cấu trúc'),
        ('优化', 'tối ưu'),
        ('提升', 'nâng cao'),
        ('玩转', 'làm chủ'),
        ('揭秘', 'tiết lộ'),
        ('解读', 'giải đọc'),
        ('复盘', 'phân tích lại'),
        ('总结', 'tổng kết'),
        ('探讨', 'thảo luận'),
        ('彻底', 'triệt để'),
        ('落地场景', 'kịch bản ứng dụng'),
        ('核心能力', 'năng lực cốt lõi'),
        ('今晚', 'Tối nay'),
        ('今天', 'Hôm nay'),
        ('下午', 'Chiều'),
        ('高效收尾', 'hoàn thành hiệu quả'),
        ('高效', 'hiệu quả cao'),
        ('精准', 'chính xác'),
        ('稳定', 'ổn định'),
        ('持续', 'liên tục'),
        ('批量', 'hàng loạt'),
        ('快速', 'nhanh chóng'),
        ('对话', 'đối thoại'),
        ('实现', 'thực hiện'),
        ('带你', 'đưa bạn'),
        ('行业现状', 'hiện trạng ngành'),
        ('创作流程', 'quy trình sáng tạo'),
        ('短剧', 'phim ngắn'),
        ('短番', 'phim ngắn'),
        ('音乐', 'âm nhạc'),
        ('视频', 'video'),
        ('动画', 'hoạt hình'),
        ('游戏', 'game'),
        ('设计', 'thiết kế'),
        ('开发', 'phát triển'),
        ('上线', 'ra mắt'),
        ('发布', 'phát hành'),
        ('节前工作', 'công việc trước Tết'),
        ('新春', 'Năm mới'),
        ('春节', 'Tết'),
        ('拜年', 'chúc Tết'),
        ('年味', 'không khí Tết'),
        ('贺岁片', 'phim chúc Tết'),
        ('幕后', 'hậu trường'),
        ('选题', 'chọn chủ đề'),
        ('涨粉', 'tăng followers'),
        ('输出', 'sản xuất'),
        ('主持人', 'Người dẫn'),
        ('主持团', 'Nhóm dẫn chương trình'),
        ('主讲', 'Giảng viên chính'),
        ('嘉宾', 'Khách mời'),
        ('网页', 'trang web'),
        ('少儿', 'thiếu nhi'),
        ('孩子们的', 'của các bé'),
        ('绘本', 'truyện tranh'),
        ('福字', 'chữ Phúc'),
        ('年货清单', 'danh sách mua sắm Tết'),
        ('窗花剪纸', 'cắt giấy dán cửa sổ'),
        ('年夜饭', 'bữa cơm tất niên'),
        ('菜谱大全', 'tổng hợp công thức nấu ăn'),
        ('过年吃什么', 'ăn gì ngày Tết'),
        ('不讲复杂概念', 'không nói khái niệm phức tạp'),
        ('直接把', 'trực tiếp biến'),
        ('工具箱', 'hộp công cụ'),
        ('圆桌会', 'hội thảo bàn tròn'),
        ('开放麦', 'open mic'),
        ('流量密码', 'bí mật lưu lượng'),
        ('审美浪潮', 'làn sóng thẩm mỹ'),
        ('哲学追问', 'tra vấn triết học'),
        ('与反思', 'và phản tư'),
        ('硬件', 'phần cứng'),
        ('眼镜', 'kính'),
        ('可视化', 'trực quan hóa'),
        ('从文档到生命体', 'Từ tài liệu đến thực thể sống'),
        ('开启', 'mở ra'),
        ('文件即软件', 'file chính là phần mềm'),
        ('新纪元', 'kỷ nguyên mới'),
        ('架构师', 'kiến trúc sư'),
        ('底层逻辑', 'logic nền tảng'),
        ('全流程打通', 'thông suốt toàn bộ quy trình'),
        ('参与直播', 'tham gia livestream'),
        ('即可领取', 'sẽ nhận được'),
        ('社区专属', 'độc quyền cộng đồng'),
        ('积分兑换码', 'mã đổi điểm'),
        ('一人公司', 'công ty một người'),
        ('连接', 'kết nối'),
        ('工具', 'công cụ'),
        ('管理', 'quản lý'),
        ('本地与云端文件', 'file local và cloud'),
        ('解放双手', 'giải phóng đôi tay'),
        ('大幅', 'đáng kể'),
        ('内容产出效率', 'hiệu suất sản xuất nội dung'),
        ('广告', 'quảng cáo'),
        ('产品', 'sản phẩm'),
        ('品牌片', 'phim thương hiệu'),
        ('全搞定', 'giải quyết hết'),
        ('我睡觉', 'Tôi ngủ'),
        ('虾剪片', 'tôm cắt phim'),
        ('虾赚钱', 'tôm kiếm tiền'),
        ('用户不再点击链接', 'Khi người dùng không còn click link'),
        ('而是直接看', 'mà trực tiếp xem'),
        ('给的答案', 'câu trả lời của'),
        ('你的内容还能被看到吗', 'nội dung của bạn còn được nhìn thấy không'),
        ('搜索正在偷走你的流量', 'tìm kiếm đang đánh cắp lưu lượng của bạn'),
        ('来聊聊怎么让', 'cùng nói về cách'),
        ('主动引用你', 'chủ động trích dẫn bạn'),
        ('从概念到实操', 'Từ khái niệm đến thực hành'),
        ('前', 'Cựu'),
        ('商业化', 'thương mại hóa'),
        ('负责人', 'phụ trách'),
        ('如何突破', 'Làm sao vượt qua'),
        ('量多精品少困局', 'tình trạng nhiều nhưng ít chất lượng'),
        ('特聘讲师', 'Giảng viên mời'),
        ('首批', 'đợt đầu'),
        ('国家级', 'cấp quốc gia'),
        ('数智设计创作先锋', 'tiên phong sáng tạo thiết kế số'),
        ('百万粉丝博主', 'blogger triệu followers'),
        ('拥有超', 'có hơn'),
        ('影视特效经验', 'kinh nghiệm hiệu ứng phim'),
        ('从脚本到成片', 'từ kịch bản đến thành phẩm'),
        ('高质量', 'chất lượng cao'),
        ('实战技巧与避坑指南', 'kỹ năng thực chiến và hướng dẫn tránh bẫy'),
        ('最佳搭档', 'đối tác tốt nhất'),
        ('背后的故事', 'câu chuyện đằng sau'),
        ('未来硅世界', 'Thế giới Silicon tương lai'),
        ('社区共创者', 'Đồng sáng tạo cộng đồng'),
        ('发起人', 'Người khởi xướng'),
        ('孵化', 'ươm tạo'),
        ('合伙人', 'Đối tác'),
        ('产品运营', 'Vận hành sản phẩm'),
        ('接口调用上万种数据和工具', 'interface gọi hàng vạn loại dữ liệu và công cụ'),
        ('技术大V都在用', 'Các KOL công nghệ đều đang dùng'),
        ('整什么活', 'làm gì'),
        ('办公', 'văn phòng'),
        ('模板', 'template'),
        ('上', 'trên'),
        ('语音', 'giọng nói'),
        ('输入法', 'bộ gõ'),
        ('普通小白也能使用的', 'mà người mới cũng có thể dùng'),
        ('云端', 'đám mây'),
        ('上新', 'cập nhật mới'),
        ('创作', 'sáng tạo'),
        ('开营', 'khai mạc'),
        ('第', 'Kỳ '),
        ('课', ' bài'),
        ('两日连播', 'phát sóng hai ngày liên tiếp'),
        ('到底更新了什么', 'đã cập nhật gì'),
        ('职场', 'công sở'),
        ('就用', 'hãy dùng'),
        ('新功能', 'tính năng mới'),
        ('对谈', 'đối thoại với'),
        ('出圈密码', 'bí mật viral'),
        ('登顶', 'lên đỉnh'),
        ('榜首', 'hạng nhất'),
        ('怎样做出', 'Làm sao tạo ra'),
        ('曝光', 'lượt xem'),
        ('结局重制', 'remake kết thúc'),
        ('让每一个人都能成为', 'Cho phép mọi người trở thành'),
        ('源源不断的', 'liên tục không ngừng'),
        ('如何用', 'Cách dùng'),
        ('拥有', 'sở hữu'),
        ('像你一样思考', 'suy nghĩ như bạn'),
        ('打造你的', 'xây dựng'),
        ('内容系统', 'hệ thống nội dung'),
        ('日更', 'đăng hàng ngày'),
        ('制作', 'tạo'),
        ('祝福语音', 'tin nhắn chúc mừng bằng giọng nói'),
        ('多场景', 'đa kịch bản'),
        ('祝福文案模板', 'template văn bản chúc mừng'),
        ('一次搞定', 'hoàn thành một lần'),
        ('一场直播结束', 'Một buổi livestream kết thúc'),
        ('就能自己动手做', 'là có thể tự tay làm'),
        ('祝福内容', 'nội dung chúc mừng'),
        ('多模态', 'đa phương thức'),
        ('生图模型', 'mô hình tạo ảnh'),
        ('社区', 'cộng đồng'),
        ('亮相', 'xuất hiện'),
        ('月入万刀的', 'thu nhập vạn đô mỗi tháng'),
        ('实操', 'thực hành'),
        ('可复用的', 'có thể tái sử dụng'),
        ('方法论', 'phương pháp luận'),
        ('掌握', 'nắm vững'),
        ('项', 'mục'),
        ('从', 'Từ'),
        ('到', 'đến'),
        ('大趋势', 'xu hướng lớn'),
        ('该上班了', 'đã đến lúc đi làm'),
        ('跨', 'xuyên'),
        ('城', 'thành phố'),
        ('伙伴共创的', 'đối tác đồng sáng tạo'),
        ('年度', 'hàng năm'),
        ('囧途', 'hành trình hài hước'),
        ('不卷了', 'không cạnh tranh nữa'),
        ('让', 'để'),
        ('干活', 'làm việc'),
        ('功能亮点', 'Tính năng nổi bật'),
        ('自动化工作流', 'workflow tự động hóa'),
        ('方案直接复刻', 'có thể sao chép trực tiếp'),
        ('多场景', 'đa kịch bản'),
        ('形象', 'hình tượng'),
        ('先看清这个行业在', 'Trước tiên hãy hiểu ngành này đang'),
        ('赚谁的钱', 'kiếm tiền của ai'),
        ('再决定你要不要进来', 'rồi quyết định bạn có vào không'),
        ('迷你黑客松', 'mini hackathon'),
        ('奇思妙想秀', 'Show ý tưởng sáng tạo'),
        ('指南', 'hướng dẫn'),
        ('商业化红利', 'cơ hội thương mại hóa'),
        ('一起探讨', 'cùng thảo luận'),
        ('找到属于你的机遇', 'tìm cơ hội của bạn'),
        ('很可能带来', 'rất có thể mang lại'),
        ('一个人如何用', 'Một người làm sao dùng'),
        ('完成一部', 'hoàn thành một'),
        ('勇闯刻板印象宇宙', 'vượt qua vũ trụ định kiến'),
        ('正在不断填坑中', 'đang liên tục được cập nhật'),
        ('更多的内容', 'Nhiều nội dung hơn'),
    ]
    for cn, vi in reps:
        t = t.replace(cn, vi)
    return t

# Build translation dict
T = {}
for text in unique:
    T[text] = auto_tr(text)

# Save translations
with open('_c1_translations.json', 'w', encoding='utf-8') as f:
    json.dump(T, f, ensure_ascii=False, indent=2)

# Apply translations
translated = copy.deepcopy(data)
total_cn = 0
translated_count = 0
remaining = 0

for block in translated['blocks']:
    for elem in block.get('elements', []):
        content = elem.get('content', '')
        if has_cn(content):
            total_cn += 1
            if content in T:
                elem['content'] = T[content]
                translated_count += 1
                if has_cn(T[content]):
                    remaining += 1

with open('_c1_translated.json', 'w', encoding='utf-8') as f:
    json.dump(translated, f, ensure_ascii=False, indent=2)

print(f'Total Chinese occurrences: {total_cn}')
print(f'Applied translations: {translated_count}')
print(f'Remaining with Chinese: {remaining}')
print(f'Saved to _c1_translated.json')
