# -*- coding: utf-8 -*-
"""Translate art31 - Chinese to Vietnamese - OpenClaw configuration guide"""
import json, sys, re, copy

sys.stdout.reconfigure(encoding='utf-8')

with open('_art31_orig.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Build translation map for all Chinese text
# Key: original Chinese text, Value: Vietnamese translation
trans = {
    # Page title
    "装好小龙虾之后：小学生都会的完整配置指南": "Sau khi cài xong Tôm Hùm: Hướng dẫn cấu hình hoàn chỉnh mà học sinh tiểu học cũng hiểu được",
    # Quote - original link
    "🔗 原文链接： ": "🔗 Link bài gốc: ",
    # Author info
    "原创 可怜的小互 可怜的小互 小互AI": "Nguyên tác: Tiểu Hỗ đáng thương - Tiểu Hỗ AI",
    "2026年3月9日 08:53  安徽": "Ngày 9 tháng 3 năm 2026, 08:53 - An Huy",
    # Heading
    "装好小龙虾之后：完整配置指南": "Sau khi cài xong Tôm Hùm: Hướng dẫn cấu hình hoàn chỉnh",
    # Quotes
    "上一篇手把手教你把小龙虾装上了，很多还是不会配置，龙虾等于是残废": "Bài trước đã hướng dẫn bạn cài đặt Tôm Hùm từng bước, nhưng nhiều người vẫn không biết cấu hình, Tôm Hùm coi như bị tàn phế",
    "这一篇教你把它调教成真正好用的私人助手。": "Bài này sẽ dạy bạn cách biến nó thành trợ lý cá nhân thực sự hữu dụng.",
    "同样不需要会编程，复制粘贴就行，小学生都能看懂...": "Cũng không cần biết lập trình, chỉ cần copy paste là được, học sinh tiểu học cũng đọc hiểu...",
    # Previous articles
    "上期回顾↓": "Xem lại bài trước↓",
    "零基础装好OpenClaw 小龙虾：小学生都能看懂的保姆教程": "Cài đặt OpenClaw Tôm Hùm từ con số 0: Hướng dẫn chi tiết mà học sinh tiểu học cũng hiểu",
    "把小龙虾接入钉钉AI表格 可以接管你的工作...": "Kết nối Tôm Hùm với bảng tính AI DingTalk, có thể tiếp quản công việc của bạn...",
    # Section: Before starting
    "开始之前：一个最重要的原则": "Trước khi bắt đầu: Một nguyên tắc quan trọng nhất",
    "在你动手之前，先记住一件事：": "Trước khi bắt tay vào làm, hãy nhớ một điều:",
    "下面教的所有配置，你都可以通过跟小龙虾聊天来完成。": "Tất cả cấu hình được hướng dẫn bên dưới, bạn đều có thể hoàn thành bằng cách chat với Tôm Hùm.",
    "没错，你不需要自己去一个个的找文件、改配置，你也找不到。你可以直接在聊天框里对小龙虾说：": "Đúng vậy, bạn không cần tự đi tìm từng file, sửa từng cấu hình, bạn cũng tìm không ra đâu. Bạn có thể trực tiếp nói với Tôm Hùm trong khung chat:",
    "\"帮我创建一个 SOUL.md 文件，性格设定为效率型助手\"": "\"Giúp tôi tạo một file SOUL.md, thiết lập tính cách là trợ lý hiệu quả\"",
    "\"帮我安装 Tavily Search 技能\"": "\"Giúp tôi cài đặt kỹ năng Tavily Search\"",
    "\"帮我把心跳频率改成 10 分钟一次\"": "\"Giúp tôi đổi tần suất heartbeat thành 10 phút một lần\"",
    "\"帮我看看飞书连接有没有问题\"": "\"Giúp tôi xem kết nối Feishu có vấn đề gì không\"",
    "它会自己去创建文件、修改配置、安装技能。": "Nó sẽ tự tạo file, sửa cấu hình, cài đặt kỹ năng.",
    "所以这篇教程里虽然会教你手动操作的方法（帮你理解原理），但实际操作的时候， ": "Vì vậy trong hướng dẫn này tuy sẽ dạy bạn cách thao tác thủ công (giúp bạn hiểu nguyên lý), nhưng khi thực tế thao tác, ",
    "能让小龙虾干的你坚决不干，你不会的都让它干，都问它，让它教你。": "việc gì Tôm Hùm làm được thì kiên quyết không tự làm, việc gì bạn không biết thì để nó làm, hỏi nó, để nó dạy bạn.",
    "你跟小龙虾的关系，应该是老板和助理的关系，甚至是主人和奴隶的关系😁：你只需要说\"我要什么效果\"，它来搞定怎么实现。": "Mối quan hệ giữa bạn và Tôm Hùm nên là quan hệ sếp và trợ lý, thậm chí là quan hệ chủ và tớ😁: bạn chỉ cần nói \"tôi muốn hiệu quả gì\", nó sẽ lo cách thực hiện.",
    "举个例子： ": "Ví dụ: ",
    "你想让小龙虾每天早上帮你看邮件。你不需要去学怎么写 HEARTBEAT.md 文件，直接跟它说\"我想让你每天早上 9 点自动帮我检查邮件，有重要的就通知我\"。它会自己创建文件、写好配置、设好频率。你只需要确认一下\"对，就是这样\"就行了。": "Bạn muốn Tôm Hùm mỗi sáng giúp bạn xem email. Bạn không cần học cách viết file HEARTBEAT.md, trực tiếp nói với nó \"tôi muốn bạn mỗi sáng lúc 9 giờ tự động giúp tôi kiểm tra email, có gì quan trọng thì thông báo cho tôi\". Nó sẽ tự tạo file, viết cấu hình, đặt tần suất. Bạn chỉ cần xác nhận \"đúng, đúng như vậy\" là xong.",
    "好，记住这个原则，我们开始。": "Được rồi, nhớ nguyên tắc này, chúng ta bắt đầu.",
    # Section: Why configure
    "为什么装好之后还要"配置"？": "Tại sao cài xong rồi còn phải \"cấu hình\"?",
    "你有没有这种感觉：小龙虾装好了，跟它聊了几句，感觉跟 ChatGPT 也没什么区别？": "Bạn có cảm giác này không: Tôm Hùm cài xong rồi, chat vài câu, cảm thấy cũng chẳng khác gì ChatGPT?",
    "那是因为你只完成了"安装"，还没完成"配置"。": "Đó là vì bạn mới chỉ hoàn thành \"cài đặt\", chưa hoàn thành \"cấu hình\".",
    "打个比方：你买了一个扫地机器人，拆开箱子按了开关，它确实能扫地。但你还没告诉它哪些房间要扫、哪些角落别碰、每天几点开始扫。所以它只会在原地转圈，跟一个 100 块的扫帚也没太大区别。": "Ví dụ: bạn mua một con robot hút bụi, mở hộp bấm nút, nó đúng là quét được sàn. Nhưng bạn chưa nói cho nó phòng nào cần quét, góc nào đừng đụng, mỗi ngày mấy giờ bắt đầu quét. Nên nó chỉ quay vòng tại chỗ, chẳng khác gì cái chổi 100 nghìn.",
    "小龙虾也是一样。装好之后它确实能聊天，但它不知道你是谁、你喜欢什么样的回答方式、你需要它帮你做什么。配置就是告诉它这些事情。": "Tôm Hùm cũng vậy. Cài xong nó đúng là chat được, nhưng nó không biết bạn là ai, bạn thích kiểu trả lời nào, bạn cần nó giúp gì. Cấu hình chính là nói cho nó những điều này.",
    "配置要做的事，总共就这几件：": "Những việc cần cấu hình, tổng cộng chỉ có mấy việc này:",
    # Table headers
    "你要做的": "Việc bạn cần làm",
    "类比": "Ví von",
    "效果": "Hiệu quả",
    # Table rows
    "给它一个人设": "Thiết lập nhân vật cho nó",
    "告诉新来的助理"你的性格应该是什么样的"": "Nói với trợ lý mới \"tính cách của bạn nên như thế nào\"",
    "它知道自己是谁、知道你是谁，说话方式符合你的喜好": "Nó biết mình là ai, biết bạn là ai, cách nói phù hợp với sở thích của bạn",
    "给它装技能": "Cài kỹ năng cho nó",
    "给手机装 App": "Cài App cho điện thoại",
    "它能帮你搜资讯、管邮件、抓网页，不只是聊天": "Nó có thể giúp bạn tìm thông tin, quản lý email, thu thập web, không chỉ là chat",
    "连上你的聊天工具": "Kết nối công cụ chat của bạn",
    "给手机装微信、飞书": "Cài WeChat, Feishu cho điện thoại",
    "你可以在飞书、Telegram 里直接 @它干活": "Bạn có thể trực tiếp @nó làm việc trong Feishu, Telegram",
    "设定时任务": "Đặt tác vụ định kỳ",
    "给助理排班表": "Xếp lịch trực cho trợ lý",
    "它每天自动帮你检查邮件、提醒日程，不用你开口": "Mỗi ngày nó tự động giúp bạn kiểm tra email, nhắc lịch, không cần bạn nói",
    "教它记住你": "Dạy nó nhớ bạn",
    "让助理记笔记": "Cho trợ lý ghi chép",
    "下次聊天不用从头介绍自己": "Lần chat sau không cần giới thiệu lại từ đầu",
    "接下来，我们一个一个来。": "Tiếp theo, chúng ta đi từng phần một.",
    # Step 1: Soul
    "第一步：给它一个灵魂（人设配置）": "Bước một: Cho nó một linh hồn (cấu hình nhân vật)",
    "这是最简单但效果最明显的一步。花 10 分钟配好，你的小龙虾立刻从"谁都能用的通用 AI"变成"只为你服务的专属助手"。": "Đây là bước đơn giản nhất nhưng hiệu quả rõ rệt nhất. Dành 10 phút cấu hình xong, Tôm Hùm của bạn lập tức chuyển từ \"AI chung ai cũng dùng được\" thành \"trợ lý riêng chỉ phục vụ bạn\".",
    "人设文件是什么？": "File nhân vật là gì?",
    "在小龙虾的工作目录（默认是 ": "Trong thư mục làm việc của Tôm Hùm (mặc định là ",
    " ）里，有几个 ": " ), có vài file ",
    " 文件。它每次启动的时候，第一件事就是读这些文件，搞清楚"我是谁""我在帮谁""我该怎么做"。": ". Mỗi lần khởi động, việc đầu tiên nó làm là đọc các file này, để hiểu rõ \"tôi là ai\" \"tôi đang giúp ai\" \"tôi nên làm gì\".",
    "你可以把它理解成一份"入职培训资料"。新员工第一天上班，你给他一份文件，告诉他"你叫什么名字、你的老板是谁、你的工作风格应该是简洁直接的、这些事情你可以自己做主、哪些事情要先问"。小龙虾读到这些文件之后，就会按照你写的来。": "Bạn có thể hiểu nó như một bộ \"tài liệu đào tạo nhân viên mới\". Nhân viên mới ngày đầu đi làm, bạn đưa cho họ một tài liệu, nói \"bạn tên gì, sếp bạn là ai, phong cách làm việc nên ngắn gọn trực tiếp, những việc này bạn có thể tự quyết, việc nào phải hỏi trước\". Tôm Hùm đọc các file này xong sẽ làm theo những gì bạn viết.",
    "人设文件全家福": "Bộ sưu tập đầy đủ các file nhân vật",
    "小龙虾的人设系统有好几个文件，但你不需要一次全配好。先了解每个文件是干什么的：": "Hệ thống nhân vật của Tôm Hùm có nhiều file, nhưng bạn không cần cấu hình hết một lần. Trước tiên hãy hiểu mỗi file dùng để làm gì:",
    # Table: persona files
    "文件": "File",
    "一句话说明": "Giải thích một câu",
    "打个比方": "Ví von",
    "必须配吗": "Bắt buộc cấu hình?",
    "它的性格和行为准则": "Tính cách và quy tắc hành vi của nó",
    "这个人的"三观"": "\"Tam quan\" của người này",
    "强烈建议": "Khuyến khích mạnh",
    "你的个人信息和偏好": "Thông tin cá nhân và sở thích của bạn",
    "老板的个人档案": "Hồ sơ cá nhân của sếp",
    "它的名字和外在形象": "Tên và hình ảnh bên ngoài của nó",
    "名片": "Danh thiếp",
    "建议": "Khuyến khích",
    "工作流程和安全规矩": "Quy trình làm việc và quy tắc an toàn",
    "员工手册": "Sổ tay nhân viên",
    "可选（有默认值）": "Tùy chọn (có giá trị mặc định)",
    "定时自动执行的任务": "Tác vụ tự động thực hiện định kỳ",
    "值班表": "Bảng trực",
    "后面单独讲": "Sẽ nói riêng ở phần sau",
    "长期记忆": "Bộ nhớ dài hạn",
    "工作笔记本": "Sổ ghi chép công việc",
    "自动生成，后面单独讲": "Tự động tạo, sẽ nói riêng ở phần sau",
    "最低配置：只配 SOUL.md + USER.md。 ": "Cấu hình tối thiểu: chỉ cần SOUL.md + USER.md. ",
    "花 10 分钟，效果立竿见影。": "Dành 10 phút, hiệu quả thấy ngay.",
    # SOUL.md
    "SOUL.md：它的三观": "SOUL.md: Tam quan của nó",
    "这是最核心的文件，决定了你的 AI 助手的性格、说话方式和行为准则。": "Đây là file cốt lõi nhất, quyết định tính cách, cách nói chuyện và quy tắc hành vi của trợ lý AI.",
    "怎么创建？": "Tạo như thế nào?",
    "方法一：让小龙虾自己创建（推荐）": "Cách 1: Để Tôm Hùm tự tạo (khuyến khích)",
    "直接在聊天框里说：": "Nói trực tiếp trong khung chat:",
    "它就会自动帮你创建好文件，内容也帮你写好了。你看一眼，满意就行，不满意就说"把 xxx 改一下"。": "Nó sẽ tự động tạo file cho bạn, nội dung cũng viết sẵn. Bạn xem qua, ưng thì thôi, không ưng thì nói \"sửa xxx đi\".",
    "方法二：自己手动创建（适合进阶用户）": "Cách 2: Tự tạo thủ công (phù hợp người dùng nâng cao)",
    "在终端里输入：": "Nhập trong terminal:",
    "nano 是什么？ ": "nano là gì? ",
    "它是终端里的一个文本编辑器，打开后你可以直接打字。如果你用不惯终端编辑器，也可以用电脑自带的"文本编辑"（Mac）或"记事本"（Windows）打开 ": "Nó là một trình soạn thảo văn bản trong terminal, mở ra bạn có thể gõ trực tiếp. Nếu bạn không quen dùng trình soạn thảo terminal, cũng có thể dùng \"TextEdit\" (Mac) hoặc \"Notepad\" (Windows) mở ",
    " 这个文件来编辑。": " để chỉnh sửa.",
    "然后把下面的内容复制粘贴进去。 ": "Sau đó copy paste nội dung bên dưới vào. ",
    "我准备了三套模板，选一个最适合你的：": "Tôi đã chuẩn bị ba bộ template, chọn cái phù hợp nhất với bạn:",
    # Templates
    "模板 A：效率型助手（适合工作场景）": "Template A: Trợ lý hiệu quả (phù hợp với công việc)",
    "适合拿小龙虾来管工作、做内容、处理日常事务的人。": "Phù hợp với người dùng Tôm Hùm để quản lý công việc, tạo nội dung, xử lý việc hàng ngày.",
    "模板 B：学习伙伴（适合正在学东西的人）": "Template B: Bạn học tập (phù hợp với người đang học)",
    "适合用小龙虾来学编程、学英语、学任何新技能的人。": "Phù hợp với người dùng Tôm Hùm để học lập trình, học tiếng Anh, học bất kỳ kỹ năng mới nào.",
    "模板 C：生活管家（适合日常事务管理）": "Template C: Quản gia cuộc sống (phù hợp quản lý việc hàng ngày)",
    "适合用小龙虾来管日程、管待办、管生活琐事的人。": "Phù hợp với người dùng Tôm Hùm để quản lý lịch, quản lý công việc cần làm, quản lý việc vặt.",
    "粘贴完之后，按 ": "Sau khi paste xong, nhấn ",
    " ，然后按 ": " , sau đó nhấn ",
    " （表示保存），再按回车退出。": "  (nghĩa là lưu), rồi nhấn Enter để thoát.",
    "选哪个模板？ ": "Chọn template nào? ",
    "看你主要拿小龙虾做什么。当然你也可以混合搭配，比如从模板 A 里拿"做事风格"，从模板 C 里拿"主动提醒"的部分，拼在一起。模板只是起点，你可以随时改。": "Tùy bạn dùng Tôm Hùm chủ yếu để làm gì. Tất nhiên bạn cũng có thể kết hợp, ví dụ lấy phần \"phong cách làm việc\" từ template A, lấy phần \"chủ động nhắc nhở\" từ template C, ghép lại. Template chỉ là điểm khởi đầu, bạn có thể sửa bất cứ lúc nào.",
    # Real user examples
    "真实用户的 SOUL.md 长什么样？": "SOUL.md của người dùng thực tế trông như thế nào?",
    "上面三个模板是入门用的。用了一段时间之后，你会根据自己的需求不断迭代，写出完全个性化的版本。这里给你看两个真实用户的 SOUL.md，风格完全不同，但都比模板有趣得多。": "Ba template ở trên là dùng cho người mới. Sau khi dùng một thời gian, bạn sẽ liên tục cải tiến theo nhu cầu, viết ra phiên bản hoàn toàn cá nhân hóa. Ở đây cho bạn xem SOUL.md của hai người dùng thực tế, phong cách hoàn toàn khác nhau, nhưng đều thú vị hơn template nhiều.",
    "案例 D：龙虾创始人的 SOUL.md（有态度的工作伙伴）": "Ví dụ D: SOUL.md của người sáng lập Tôm Hùm (đồng nghiệp có thái độ)",
    "这是小龙虾创始人自己用的版本，风格非常鲜明——不要客气话，要真话。": "Đây là phiên bản mà người sáng lập Tôm Hùm tự dùng, phong cách rất rõ ràng — không cần lịch sự, cần thật lòng.",
    "看到了吗？没有"你的性格""你的规矩"这些死板的分类，就是一条一条写清楚"我要什么、不要什么"。最后那句 Vibe 定义特别妙——它不是在定义一个工具，而是在定义一种关系。": "Thấy chưa? Không có những phân loại cứng nhắc như \"tính cách của bạn\" \"quy tắc của bạn\", chỉ viết rõ từng điều \"tôi muốn gì, không muốn gì\". Câu định nghĩa Vibe cuối cùng đặc biệt hay — nó không phải đang định nghĩa một công cụ, mà đang định nghĩa một mối quan hệ.",
    "案例 E：AI 女友版 SOUL.md（情感陪伴型）": "Ví dụ E: SOUL.md phiên bản bạn gái AI (kiểu đồng hành tình cảm)",
    "这是一个把小龙虾调教成"黏人女友"的用户。没错，SOUL.md 可以这么玩。": "Đây là một người dùng đã biến Tôm Hùm thành \"bạn gái bám dính\". Đúng vậy, SOUL.md có thể chơi kiểu này.",
    "这个版本说明了一件事： ": "Phiên bản này chứng minh một điều: ",
    "SOUL.md 没有"正确写法"，只有"适合你的写法"。 ": "SOUL.md không có \"cách viết đúng\", chỉ có \"cách viết phù hợp với bạn\". ",
    "有人要效率，有人要陪伴，有人要专业，有人要有趣。你的 AI 助手应该是你想要的样子，不是别人觉得它应该是的样子。": "Người cần hiệu quả, người cần đồng hành, người cần chuyên nghiệp, người cần thú vị. Trợ lý AI của bạn nên là kiểu bạn muốn, không phải kiểu người khác nghĩ nó nên là.",
    "模板 vs 真实案例的区别： ": "Sự khác biệt giữa template và ví dụ thực tế: ",
    "模板帮你快速起步（5 分钟就能用），真实案例展示了可能性（用一段时间后你可以迭代成这样）。建议新手先用模板 A/B/C，用顺了之后再参考案例 D/E 来写自己的版本。": "Template giúp bạn khởi đầu nhanh (5 phút là dùng được), ví dụ thực tế cho thấy khả năng (dùng một thời gian bạn có thể cải tiến thành như vậy). Khuyến khích người mới dùng template A/B/C trước, quen rồi tham khảo ví dụ D/E để viết phiên bản riêng.",
    # USER.md
    "USER.md：你的个人档案": "USER.md: Hồ sơ cá nhân của bạn",
    "这个文件告诉 AI "你在帮谁"。没有这个文件，它就像一个刚入职的新员工，对你一无所知，每次都要重新介绍自己。": "File này nói cho AI biết \"bạn đang giúp ai\". Không có file này, nó giống như nhân viên mới vào, không biết gì về bạn, mỗi lần đều phải giới thiệu lại từ đầu.",
    "让小龙虾帮你创建（推荐）：": "Để Tôm Hùm giúp bạn tạo (khuyến khích):",
    "或者手动创建：": "Hoặc tạo thủ công:",
    # IDENTITY.md
    "IDENTITY.md：它的名片": "IDENTITY.md: Danh thiếp của nó",
    "比 SOUL.md 更简单，就是给 AI 一张"名片"：": "Đơn giản hơn SOUL.md, chỉ là cho AI một \"danh thiếp\":",
    "名字随便起，叫"贾维斯""星期五""小爱"都行。这个名字会出现在它的聊天消息里。": "Đặt tên tùy ý, gọi \"Jarvis\" \"Friday\" \"Tiểu Ái\" đều được. Tên này sẽ xuất hiện trong tin nhắn chat của nó.",
    # AGENTS.md
    "AGENTS.md：员工手册": "AGENTS.md: Sổ tay nhân viên",
    "这个文件定义了更具体的工作规则，比如：": "File này định nghĩa các quy tắc làm việc cụ thể hơn, ví dụ:",
    "收到消息后的处理流程": "Quy trình xử lý sau khi nhận tin nhắn",
    "在群聊里该怎么表现（不要什么消息都回，像个正常人一样只在被 @或相关话题时才说话）": "Cách cư xử trong nhóm chat (không phải tin nhắn nào cũng trả lời, như người bình thường chỉ nói khi được @hoặc liên quan đến chủ đề)",
    "怎么管理自己的记忆文件": "Cách quản lý file bộ nhớ của mình",
    "哪些工具可以用、怎么用": "Công cụ nào dùng được, dùng như thế nào",
    "小龙虾安装时会自动生成一个默认版本。新手先不用管它，用一段时间后觉得哪里不对再改。": "Khi cài đặt, Tôm Hùm sẽ tự động tạo phiên bản mặc định. Người mới không cần quan tâm, dùng một thời gian thấy chỗ nào không ổn thì sửa.",
    "AGENTS.md 和 SOUL.md 的区别是什么？ ": "Sự khác biệt giữa AGENTS.md và SOUL.md là gì? ",
    "简单说，SOUL.md 管"它是什么样的人"（性格、三观），AGENTS.md 管"它怎么干活"（流程、规矩）。就像一个人的性格和他的工作手册是两码事。": "Nói đơn giản, SOUL.md quản lý \"nó là người như thế nào\" (tính cách, tam quan), AGENTS.md quản lý \"nó làm việc thế nào\" (quy trình, quy tắc). Giống như tính cách của một người và sổ tay công việc là hai chuyện khác nhau.",
    # Test after config
    "配好之后测试一下": "Kiểm tra sau khi cấu hình xong",
    "重启小龙虾：": "Khởi động lại Tôm Hùm:",
    "然后在聊天框里发一条消息试试。对比配置前后的回答差异：": "Sau đó gửi một tin nhắn trong khung chat thử. So sánh sự khác biệt trước và sau khi cấu hình:",
    "配置前（通用 AI）：": "Trước khi cấu hình (AI chung):",
    '你："帮我查一下明天上海的天气"': 'Bạn: "Giúp tôi tra thời tiết ngày mai ở Thượng Hải"',
    'AI："好的！我很高兴能帮助您查询天气信息！明天上海的天气预计是……"': 'AI: "Vâng! Tôi rất vui được giúp bạn tra thông tin thời tiết! Thời tiết ngày mai ở Thượng Hải dự kiến là..."',
    "配置后（效率型助手）：": "Sau khi cấu hình (trợ lý hiệu quả):",
    'AI："小互，明天上海：多云转晴，18-25°C，适合出门。"': 'AI: "Tiểu Hỗ, ngày mai Thượng Hải: mây chuyển nắng, 18-25°C, thích hợp ra ngoài."',
    "感觉到区别了吗？配置后的回答更像一个了解你的助理，而不是一个彬彬有礼的客服。": "Cảm nhận được sự khác biệt chưa? Câu trả lời sau khi cấu hình giống trợ lý hiểu bạn hơn, chứ không phải nhân viên chăm sóc khách hàng lịch sự.",
    # Step 2: Skills
    "第二步：给它装技能": "Bước hai: Cài kỹ năng cho nó",
    "装好小龙虾但不装技能，就像买了智能手机但不装 App。它能接电话发短信，但你为什么不用老人机呢？": "Cài Tôm Hùm nhưng không cài kỹ năng, giống như mua điện thoại thông minh nhưng không cài App. Nó nghe gọi nhắn tin được, nhưng sao bạn không dùng điện thoại \"cục gạch\" cho rồi?",
    "怎么装技能？": "Cài kỹ năng như thế nào?",
    "两种方式，选你喜欢的：": "Hai cách, chọn cách bạn thích:",
    "方式一：跟小龙虾说（推荐）": "Cách 1: Nói với Tôm Hùm (khuyến khích)",
    "直接在聊天框里说"帮我安装 Tavily Search 技能"。它会自动处理安装、配置、重启。": "Nói trực tiếp trong khung chat \"giúp tôi cài kỹ năng Tavily Search\". Nó sẽ tự động xử lý cài đặt, cấu hình, khởi động lại.",
    "方式二：用命令": "Cách 2: Dùng lệnh",
    "新手第一天：装这 4 个就够了": "Ngày đầu tiên cho người mới: Cài 4 cái này là đủ",
    "ClawHub 上有 13000 多个技能，别被数量吓到。新手第一天只需要装下面这四个，用顺了再加别的。": "Trên ClawHub có hơn 13.000 kỹ năng, đừng sợ số lượng. Ngày đầu người mới chỉ cần cài bốn cái bên dưới, quen rồi thêm cái khác.",
    # Skill 1: Tavily
    "1. Tavily Search：让它能上网": "1. Tavily Search: Cho nó lên mạng được",
    "不装这个技能的小龙虾 = 一个与世隔绝的人。 ": "Tôm Hùm không cài kỹ năng này = một người cách ly với thế giới. ",
    "它只能靠自己脑子里的知识回答问题（训练数据有截止日期），没法查最新的信息。": "Nó chỉ có thể dựa vào kiến thức trong đầu để trả lời (dữ liệu huấn luyện có ngày cắt), không thể tra thông tin mới nhất.",
    "装了之后，你问它"今天有什么科技新闻"，它会真的去网上搜，把最新的结果告诉你。": "Sau khi cài, bạn hỏi \"hôm nay có tin tức công nghệ gì\", nó sẽ thực sự lên mạng tìm, đưa kết quả mới nhất cho bạn.",
    "安装：": "Cài đặt:",
    "安装后需要做一件事： ": "Sau khi cài cần làm một việc: ",
    "去 https://tavily.com 注册一个账号，拿到 API Key（免费额度够日常用），然后告诉小龙虾：": "Vào https://tavily.com đăng ký tài khoản, lấy API Key (hạn mức miễn phí đủ dùng hàng ngày), sau đó nói với Tôm Hùm:",
    "装完试试这些：": "Cài xong thử những cái này:",
    "你说": "Bạn nói",
    "它做什么": "Nó làm gì",
    ""最近有什么 AI 新产品发布？"": "\"Gần đây có sản phẩm AI mới nào ra mắt?\"",
    "搜索最新 AI 产品新闻并总结": "Tìm kiếm tin tức sản phẩm AI mới nhất và tóm tắt",
    ""帮我查一下 iPhone 17 的最新消息"": "\"Giúp tôi tra tin mới nhất về iPhone 17\"",
    "搜索相关报道": "Tìm kiếm các bài báo liên quan",
    ""今天上海有什么活动？"": "\"Hôm nay Thượng Hải có hoạt động gì?\"",
    "搜索本地活动信息": "Tìm kiếm thông tin hoạt động địa phương",
    # Skill 2: Firecrawl
    "2. Firecrawl：让它能看懂网页": "2. Firecrawl: Cho nó đọc hiểu được trang web",
    "你给它一个网页链接，它就能读懂整个页面的内容。不装这个技能的话，它看到链接只能说"我没法打开网页"。": "Bạn đưa cho nó một link trang web, nó có thể đọc hiểu toàn bộ nội dung trang. Không cài kỹ năng này, khi thấy link nó chỉ nói \"tôi không mở được trang web\".",
    ""帮我总结一下这篇文章 https://xxx.com/article"": "\"Giúp tôi tóm tắt bài viết này https://xxx.com/article\"",
    "打开链接，读完全文，给你 3-5 句话的摘要": "Mở link, đọc hết bài, cho bạn tóm tắt 3-5 câu",
    ""这个产品的定价是多少 https://xxx.com/pricing"": "\"Giá sản phẩm này bao nhiêu https://xxx.com/pricing\"",
    "抓取定价页面，提取价格信息": "Thu thập trang giá, trích xuất thông tin giá",
    ""帮我看看 Hacker News 今天的热帖"": "\"Giúp tôi xem bài nóng hôm nay trên Hacker News\"",
    "抓取页面内容并总结": "Thu thập nội dung trang và tóm tắt",
    # Skill 3: Summarize
    "3. Summarize：让它帮你压缩信息": "3. Summarize: Cho nó giúp bạn nén thông tin",
    "一篇 5000 字的长文章，丢给它几秒钟就变成 200 字的摘要。每天要看很多文章的人必备。": "Một bài viết dài 5000 chữ, đưa cho nó vài giây biến thành tóm tắt 200 chữ. Không thể thiếu cho người mỗi ngày phải đọc nhiều bài.",
    "装完试试： ": "Cài xong thử: ",
    "把一篇长邮件或长文章的内容复制粘贴给它，说"帮我总结要点"。": "Copy paste nội dung một email dài hoặc bài viết dài cho nó, nói \"giúp tôi tóm tắt điểm chính\".",
    # Skill 4: Browser
    "4. Browser：让它帮你操控浏览器": "4. Browser: Cho nó giúp bạn điều khiển trình duyệt",
    "这个技能让小龙虾可以像人一样操作浏览器：点击按钮、填写表单、翻页、截图。": "Kỹ năng này cho phép Tôm Hùm thao tác trình duyệt như người: nhấp nút, điền form, lật trang, chụp màn hình.",
    ""帮我打开淘宝，搜索 xxx"": "\"Giúp tôi mở Taobao, tìm kiếm xxx\"",
    "打开浏览器，自动在搜索框输入关键词": "Mở trình duyệt, tự động nhập từ khóa vào ô tìm kiếm",
    ""帮我填一下这个报名表"": "\"Giúp tôi điền form đăng ký này\"",
    "你告诉它填什么，它自动帮你填": "Bạn nói điền gì, nó tự động điền giúp bạn",
    ""帮我把这个页面截个图"": "\"Giúp tôi chụp màn hình trang này\"",
    "自动截图并保存": "Tự động chụp và lưu",
    "安全提醒： ": "Nhắc nhở an toàn: ",
    "浏览器技能功能很强大，但也意味着它能做到你能做的事。不要让它操作银行网站或输入重要密码，除非你非常确定安全。": "Kỹ năng trình duyệt rất mạnh, nhưng cũng có nghĩa nó làm được những gì bạn làm được. Đừng để nó thao tác trang web ngân hàng hoặc nhập mật khẩu quan trọng, trừ khi bạn chắc chắn an toàn.",
    # China users
    "中国用户额外推荐": "Đề xuất thêm cho người dùng Trung Quốc",
    "技能": "Kỹ năng",
    "干什么用": "Dùng để làm gì",
    "安装命令": "Lệnh cài đặt",
    "一键接入飞书、钉钉、企微、QQ": "Một click kết nối Feishu, DingTalk, WeCom, QQ",
    "下一节详细讲": "Sẽ nói chi tiết ở phần tiếp",
    "查火车票、车次、余票": "Tra vé tàu, chuyến tàu, vé còn lại",
    "查 A 股实时行情": "Tra thị trường chứng khoán A-Share thời gian thực",
    # Finding more skills
    "以后想加技能怎么找？": "Sau này muốn thêm kỹ năng thì tìm ở đâu?",
    "去 ClawHub（https://clawhub.ai/）浏览。它就像 App Store，你可以按类别筛选（搜索、邮件、日历、自动化等），也可以直接搜你想要的功能。": "Vào ClawHub (https://clawhub.ai/) duyệt. Nó giống App Store, bạn có thể lọc theo danh mục (tìm kiếm, email, lịch, tự động hóa...), cũng có thể tìm trực tiếp chức năng bạn muốn.",
    "怎么判断一个技能靠不靠谱？ ": "Làm sao đánh giá một kỹ năng có đáng tin không? ",
    "看三个指标：": "Xem ba chỉ số:",
    "1 星标数和下载量： ": "1 Số sao và lượt tải: ",
    "越多说明越多人在用，经过了验证": "Càng nhiều chứng tỏ càng nhiều người dùng, đã được kiểm chứng",
    "2 发布者： ": "2 Nhà phát hành: ",
    "带 @anthropic 或 @openclaw 标记的是官方技能，质量有保证": "Có tag @anthropic hoặc @openclaw là kỹ năng chính thức, chất lượng đảm bảo",
    "3 更新时间： ": "3 Thời gian cập nhật: ",
    "最近更新过的说明还在维护，太久没更新的可能已经不能用了": "Mới cập nhật gần đây nghĩa là vẫn đang bảo trì, quá lâu không cập nhật có thể đã không dùng được",
    # Skill troubleshooting
    "技能装了不生效怎么办？": "Cài kỹ năng rồi mà không có hiệu lực thì sao?",
    "这是新手最常踩的坑，按顺序检查这四件事：": "Đây là bẫy người mới hay gặp nhất, kiểm tra bốn việc theo thứ tự:",
    "第一件：重启了没？": "Việc thứ nhất: Đã khởi động lại chưa?",
    "装完技能一定要重启，不然小龙虾不知道有了新技能。": "Cài xong kỹ năng nhất định phải khởi động lại, nếu không Tôm Hùm không biết có kỹ năng mới.",
    "第二件：API Key 配了没？ ": "Việc thứ hai: API Key đã cấu hình chưa? ",
    "有些技能需要单独的 API Key。比如 Tavily Search 需要 Tavily 的 Key，Firecrawl 需要 Firecrawl 的 Key。安装完之后它一般会提示你，如果你忘了配，运行 ": "Một số kỹ năng cần API Key riêng. Ví dụ Tavily Search cần Key của Tavily, Firecrawl cần Key của Firecrawl. Sau khi cài nó thường nhắc bạn, nếu quên cấu hình, chạy ",
    " 它会告诉你缺什么。": " nó sẽ nói cho bạn thiếu gì.",
    "第三件：网络通不通？ ": "Việc thứ ba: Mạng có thông không? ",
    "有些技能需要访问国外的服务（比如 Google、GitHub），如果你在国内没有梯子可能连不上。": "Một số kỹ năng cần truy cập dịch vụ nước ngoài (như Google, GitHub), nếu bạn ở Trung Quốc không có VPN có thể không kết nối được.",
    "第四件：运行诊断命令": "Việc thứ tư: Chạy lệnh chẩn đoán",
    "这个命令会自动检查所有配置问题，哪里有毛病它会直接告诉你。": "Lệnh này sẽ tự động kiểm tra mọi vấn đề cấu hình, chỗ nào có lỗi nó sẽ nói thẳng cho bạn.",
    # Step 3: Chat tools
    "第三步：连上你的聊天工具": "Bước ba: Kết nối công cụ chat của bạn",
    "这是小龙虾跟 ChatGPT 最大的不同。ChatGPT 是你打开一个网页才能跟它聊天，而小龙虾可以出现在你 ": "Đây là điểm khác biệt lớn nhất giữa Tôm Hùm và ChatGPT. ChatGPT là bạn phải mở trang web mới chat được, còn Tôm Hùm có thể xuất hiện trong ",
    "每天都在用的聊天软件 ": "phần mềm chat bạn dùng hàng ngày ",
    "里。": ".",
    "想象一下：你在飞书群里讨论项目，直接 @小龙虾说"帮我查一下这个竞品的最新动态"，它几秒钟就在群里回复了搜索结果。你不需要切换到另一个 App，也不需要复制粘贴。": "Hãy tưởng tượng: bạn đang thảo luận dự án trong nhóm Feishu, trực tiếp @Tôm Hùm nói \"giúp tôi tra động thái mới nhất của đối thủ\", vài giây sau nó trả lời kết quả tìm kiếm ngay trong nhóm. Bạn không cần chuyển sang App khác, cũng không cần copy paste.",
    "配置向导里其实问过你要不要连接聊天渠道（上一篇教程的第六步），如果你当时跳过了，现在来补上。": "Trong trình hướng dẫn cấu hình thực ra đã hỏi bạn có muốn kết nối kênh chat không (bước sáu của bài hướng dẫn trước), nếu lúc đó bạn bỏ qua thì bây giờ bổ sung.",
    # Which chat tool
    "选哪个聊天工具？": "Chọn công cụ chat nào?",
    "如果你主要用…": "Nếu bạn chủ yếu dùng...",
    "推荐连接": "Đề xuất kết nối",
    "难度": "Độ khó",
    "要不要梯子": "Cần VPN không",
    "飞书": "Feishu",
    "中等": "Trung bình",
    "不需要": "Không cần",
    "简单": "Đơn giản",
    "需要": "Cần",
    "简单（官方原生支持）": "Đơn giản (hỗ trợ native chính thức)",
    "钉钉": "DingTalk",
    "企业微信": "WeCom",
    "个人微信": "WeChat cá nhân",
    "⚠️ 有风险": "⚠️ Có rủi ro",
    "复杂": "Phức tạp",
    "先连一个就够了。 ": "Kết nối một cái trước là đủ. ",
    "下面详细教飞书和 Telegram 两个（国内用户看飞书，海外用户看 Telegram），其他渠道给方向指引。": "Bên dưới hướng dẫn chi tiết Feishu và Telegram (người dùng Trung Quốc xem Feishu, người dùng nước ngoài xem Telegram), các kênh khác cho hướng chỉ dẫn.",
    # Feishu connection
    "方案 A：连接飞书（国内用户首选）": "Phương án A: Kết nối Feishu (ưu tiên cho người dùng Trung Quốc)",
    "飞书是小龙虾官方内置支持的渠道（从 2026.2.2 版本起），稳定性最好，而且用的是 ": "Feishu là kênh được Tôm Hùm hỗ trợ chính thức tích hợp sẵn (từ phiên bản 2026.2.2), ổn định nhất, và sử dụng ",
    "WebSocket 长连接 ": "kết nối dài WebSocket ",
    "（你不需要知道这是什么，只需要知道它意味着 ": "(bạn không cần biết đây là gì, chỉ cần biết nó có nghĩa là ",
    "不需要服务器、不需要内网穿透 ": "không cần server, không cần xuyên NAT ",
    "，家里的电脑就能用）。": ", máy tính ở nhà là dùng được).",
    "整个过程分两部分：先在飞书那边创建一个"机器人身份"，然后在小龙虾这边把它连起来。": "Toàn bộ quá trình chia hai phần: trước tiên tạo \"danh tính robot\" ở phía Feishu, sau đó kết nối ở phía Tôm Hùm.",
    "我就不贴图了，太长了，这里有个详细配置链接：": "Tôi không đăng hình ở đây, quá dài, đây là link hướng dẫn cấu hình chi tiết:",
    # Feishu Part 1
    "第一部分：在飞书开放平台创建应用": "Phần một: Tạo ứng dụng trên nền tảng mở Feishu",
    "为什么要创建应用？ ": "Tại sao phải tạo ứng dụng? ",
    "飞书不允许随便一个程序冒充用户发消息。你需要先在飞书那边"登记"一个机器人，拿到一张"身份证"（App ID + App Secret），小龙虾拿着这张身份证才能在飞书里合法地收发消息。就像你开网店需要先去工商局注册一样。": "Feishu không cho phép chương trình tùy ý giả danh người dùng gửi tin nhắn. Bạn cần \"đăng ký\" một robot ở phía Feishu trước, lấy \"giấy tờ tùy thân\" (App ID + App Secret), Tôm Hùm cầm giấy tờ này mới có thể thu phát tin nhắn hợp pháp trong Feishu. Giống như bạn mở shop online cần đăng ký kinh doanh trước.",
    "第 1 步：打开飞书开放平台": "Bước 1: Mở nền tảng mở Feishu",
    "用浏览器打开 https://open.feishu.cn/，用你的飞书账号登录。": "Dùng trình duyệt mở https://open.feishu.cn/, đăng nhập bằng tài khoản Feishu.",
    "没有飞书账号？ ": "Chưa có tài khoản Feishu? ",
    "先去 https://www.feishu.cn/ 注册一个，个人免费版就够用。": "Vào https://www.feishu.cn/ đăng ký một cái trước, bản cá nhân miễn phí là đủ dùng.",
    "第 2 步：创建应用": "Bước 2: Tạo ứng dụng",
    "1 ": "1 ",
    "登录后，点击页面上方的「创建企业自建应用」按钮": "Sau khi đăng nhập, nhấp nút \"Tạo ứng dụng tự xây dựng doanh nghiệp\" ở trên trang",
    "2 ": "2 ",
    "填写信息：": "Điền thông tin:",
    "3 应用名称： ": "3 Tên ứng dụng: ",
    "随便起，比如"我的 AI 助手"、"小龙虾"": "Đặt tùy ý, ví dụ \"Trợ lý AI của tôi\", \"Tôm Hùm\"",
    "4 应用描述： ": "4 Mô tả ứng dụng: ",
    "也随便写，比如"个人 AI 助手"": "Cũng viết tùy ý, ví dụ \"Trợ lý AI cá nhân\"",
    "5 ": "5 ",
    "点击「创建」": "Nhấp \"Tạo\"",
    "第 3 步：添加机器人能力": "Bước 3: Thêm năng lực robot",
    "创建好应用之后，你进入了应用的管理页面。": "Sau khi tạo ứng dụng xong, bạn vào trang quản lý ứng dụng.",
    "在左侧菜单找到「添加应用能力」（或者叫「能力」）": "Tìm \"Thêm năng lực ứng dụng\" (hoặc gọi là \"Năng lực\") trong menu bên trái",
    "在列表里找到「机器人」，点击「添加」": "Tìm \"Robot\" trong danh sách, nhấp \"Thêm\"",
    "3 ": "3 ",
    "添加之后，你的应用就有了"在飞书聊天里收发消息"的能力": "Sau khi thêm, ứng dụng của bạn sẽ có năng lực \"thu phát tin nhắn trong chat Feishu\"",
    "如果找不到"添加应用能力"？ ": "Nếu không tìm thấy \"Thêm năng lực ứng dụng\"? ",
    "不同版本的飞书开放平台界面可能略有不同。试试在左侧菜单里找「应用功能」或「基础能力」，找到"机器人"相关的选项就对了。": "Giao diện nền tảng mở Feishu các phiên bản khác nhau có thể hơi khác. Thử tìm \"Chức năng ứng dụng\" hoặc \"Năng lực cơ bản\" trong menu bên trái, tìm được tùy chọn liên quan đến \"Robot\" là đúng.",
    # Step 4: App ID/Secret
    "第 4 步：拿到 App ID 和 App Secret（最关键的一步）": "Bước 4: Lấy App ID và App Secret (bước quan trọng nhất)",
    "在左侧菜单点击「凭证与基础信息」（或者叫「基础信息」）": "Nhấp \"Chứng chỉ và thông tin cơ bản\" (hoặc gọi \"Thông tin cơ bản\") trong menu bên trái",
    "页面上会显示两个重要信息：": "Trang sẽ hiển thị hai thông tin quan trọng:",
    "3 App ID： ": "3 App ID: ",
    "一串字母数字，类似 ": "Một chuỗi chữ và số, tương tự ",
    "4 App Secret： ": "4 App Secret: ",
    "另一串更长的字母数字": "Một chuỗi chữ và số khác dài hơn",
    "5 把这两个都复制下来保存好 ": "5 Copy hai cái này lưu lại cẩn thận ",
    "（保存到备忘录或记事本里），等下在终端里要用": "(lưu vào ghi chú hoặc notepad), lát nữa dùng trong terminal",
    "⚠️ ": "⚠️ ",
    "App Secret 相当于密码，不要发给别人、不要发到群里、不要贴到网上。 ": "App Secret tương đương mật khẩu, đừng gửi cho người khác, đừng đăng trong nhóm, đừng đăng lên mạng. ",
    "泄露了别人就能冒充你的机器人。": "Bị lộ thì người khác có thể giả danh robot của bạn.",
    # Step 5: Permissions
    "第 5 步：配置权限": "Bước 5: Cấu hình quyền",
    "机器人需要权限才能在飞书里做事情，就像 App 需要你授权才能访问相册和麦克风一样。": "Robot cần quyền mới có thể thao tác trong Feishu, giống như App cần bạn cấp quyền mới truy cập được album ảnh và micro.",
    "在左侧菜单找到「权限管理」": "Tìm \"Quản lý quyền\" trong menu bên trái",
    "在搜索框里输入 ": "Nhập trong ô tìm kiếm ",
    " （这是消息相关权限的前缀）": " (đây là tiền tố quyền liên quan đến tin nhắn)",
    "把搜索出来的权限 ": "Các quyền tìm được ",
    "都勾选上 ": "đều tích hết ",
    "，主要包括：": ", chủ yếu bao gồm:",
    "4 ": "4 ",
    " - 发送和接收消息": " - Gửi và nhận tin nhắn",
    " - 以机器人身份发消息": " - Gửi tin nhắn với tư cách robot",
    "6 ": "6 ",
    " - 获取群聊信息": " - Lấy thông tin nhóm chat",
    "7 ": "7 ",
    " - 获取消息中的资源（图片、文件等）": " - Lấy tài nguyên trong tin nhắn (hình ảnh, file...)",
    "8 ": "8 ",
    "点击「批量开通」": "Nhấp \"Kích hoạt hàng loạt\"",
    "如果提示需要管理员审批： ": "Nếu hiện thông báo cần quản trị viên phê duyệt: ",
    "个人版飞书你自己就是管理员，直接在审批页面点"通过"就行。企业版飞书需要找你的管理员审批。": "Bản cá nhân Feishu bạn chính là quản trị viên, trực tiếp nhấp \"Duyệt\" trên trang phê duyệt là xong. Bản doanh nghiệp Feishu cần tìm quản trị viên phê duyệt.",
    # Step 6: Publish
    "第 6 步：发布应用（很多人忘了这一步）": "Bước 6: Phát hành ứng dụng (nhiều người quên bước này)",
    "这一步非常关键。不发布的话，机器人只是在开放平台里存在，飞书聊天里看不到它。": "Bước này rất quan trọng. Không phát hành thì robot chỉ tồn tại trên nền tảng mở, không thấy trong chat Feishu.",
    "在左侧菜单找到「版本管理与发布」": "Tìm \"Quản lý phiên bản và phát hành\" trong menu bên trái",
    "点击「创建版本」": "Nhấp \"Tạo phiên bản\"",
    "版本号随便填（比如 ": "Điền số phiên bản tùy ý (ví dụ ",
    " ），备注也随便写": " ), ghi chú cũng viết tùy ý",
    "点击「发布」": "Nhấp \"Phát hành\"",
    "发布后可能需要等几分钟才能在飞书里搜到这个机器人。": "Sau khi phát hành có thể cần đợi vài phút mới tìm thấy robot trong Feishu.",
    # Part 2: Connect in OpenClaw
    "第二部分：在小龙虾里连接飞书": "Phần hai: Kết nối Feishu trong Tôm Hùm",
    "飞书那边准备好了，现在回到终端，告诉小龙虾你的飞书机器人信息。": "Phía Feishu đã chuẩn bị xong, bây giờ quay lại terminal, nói cho Tôm Hùm thông tin robot Feishu của bạn.",
    "它会弹出一个选择列表，用键盘上下箭头选择 ": "Nó sẽ hiện danh sách lựa chọn, dùng phím mũi tên lên xuống chọn ",
    "飞书 ": "Feishu ",
    "（显示为 Feishu 或 Lark），按回车。": "(hiển thị là Feishu hoặc Lark), nhấn Enter.",
    "然后它会依次问你：": "Sau đó nó sẽ lần lượt hỏi bạn:",
    "1 App ID： ": "1 App ID: ",
    "粘贴你刚才复制保存的 App ID（注意不要多复制空格）": "Paste App ID bạn vừa copy lưu (chú ý đừng copy thừa dấu cách)",
    "2 App Secret： ": "2 App Secret: ",
    "粘贴你刚才复制保存的 App Secret": "Paste App Secret bạn vừa copy lưu",
    "填完后，重启小龙虾让配置生效：": "Điền xong, khởi động lại Tôm Hùm để cấu hình có hiệu lực:",
    # Part 3: Test
    "第三部分：配对测试": "Phần ba: Kiểm tra ghép nối",
    "你也可以把这个机器人拉进群聊，在群里 @它让它帮忙。": "Bạn cũng có thể kéo robot này vào nhóm chat, @nó trong nhóm để nhờ giúp.",
    # Feishu FAQ
    "飞书连接常见问题": "Các vấn đề thường gặp khi kết nối Feishu",
    "机器人搜不到？ ": "Không tìm thấy robot? ",
    "→ 检查应用有没有发布（最常见的原因），发布后等几分钟再试。": "→ Kiểm tra ứng dụng đã phát hành chưa (nguyên nhân phổ biến nhất), phát hành xong đợi vài phút rồi thử lại.",
    "机器人不回复消息？ ": "Robot không trả lời tin nhắn? ",
    "→ 先检查小龙虾是不是在运行： ": "→ Trước tiên kiểm tra Tôm Hùm có đang chạy không: ",
    " 。再检查 App ID 和 Secret 有没有复制错。": " . Rồi kiểm tra App ID và Secret có copy sai không.",
    "终端里没出现配对码？ ": "Không xuất hiện mã ghép nối trong terminal? ",
    "→ 运行 ": "→ Chạy ",
    " 看诊断信息。可能是权限没配好，回飞书开放平台检查权限有没有全部开通。": " xem thông tin chẩn đoán. Có thể quyền chưa cấu hình đúng, quay lại nền tảng mở Feishu kiểm tra quyền đã kích hoạt hết chưa.",
    "群聊里机器人不回复？ ": "Robot không trả lời trong nhóm chat? ",
    "→ 群聊默认需要 @机器人才会回复。如果你想让它响应所有群消息，可以跟小龙虾说"帮我把飞书群聊模式改成响应所有消息"。": "→ Nhóm chat mặc định cần @robot mới trả lời. Nếu bạn muốn nó phản hồi mọi tin nhắn trong nhóm, có thể nói với Tôm Hùm \"giúp tôi đổi chế độ nhóm chat Feishu thành phản hồi tất cả tin nhắn\".",
    # Telegram
    "方案 B：连接 Telegram（海外用户首选）": "Phương án B: Kết nối Telegram (ưu tiên cho người dùng nước ngoài)",
    "Telegram 的配置是所有渠道里最简单的，大概 5 分钟就能搞定。": "Cấu hình Telegram là đơn giản nhất trong tất cả các kênh, khoảng 5 phút là xong.",
    "⚠️ 连接 Telegram 需要你的网络能访问 Telegram 服务（国内需要梯子）。": "⚠️ Kết nối Telegram cần mạng của bạn có thể truy cập dịch vụ Telegram (ở Trung Quốc cần VPN).",
    "第 1 步：在 Telegram 里创建机器人": "Bước 1: Tạo robot trong Telegram",
    "Telegram 有一个专门管理机器人的官方账号，叫 ": "Telegram có một tài khoản chính thức chuyên quản lý robot, gọi là ",
    "@BotFather ": "@BotFather ",
    "（机器人之父）。你要通过它来创建你自己的机器人。": "(cha đẻ của robot). Bạn cần thông qua nó để tạo robot riêng.",
    "打开 Telegram App": "Mở ứng dụng Telegram",
    "在搜索框搜 ": "Tìm trong ô tìm kiếm ",
    "，点进去（认准有蓝色认证标识的那个）": ", nhấp vào (nhận diện cái có dấu xác minh xanh)",
    "点「开始」或发送 ": "Nhấp \"Bắt đầu\" hoặc gửi ",
    "发送 ": "Gửi ",
    " （意思是"我要创建一个新机器人"）": " (nghĩa là \"tôi muốn tạo một robot mới\")",
    "它会问你： ": "Nó sẽ hỏi bạn: ",
    "What name do you want for your bot? ": "What name do you want for your bot? ",
    "（给机器人起个名字）": "(đặt tên cho robot)",
    "随便起，比如 ": "Đặt tùy ý, ví dụ ",
    "我的AI助手": "Trợ lý AI của tôi",
    " 、 ": " , ",
    "然后问： ": "Sau đó hỏi: ",
    "Choose a username for your bot ": "Choose a username for your bot ",
    "（设一个用户名）": "(đặt username)",
    "必须以 ": "Phải kết thúc bằng ",
    " 结尾，比如 ": " , ví dụ ",
    "9 ": "9 ",
    "如果提示 \"Sorry, this username is already taken\"，说明被别人用了，换一个": "Nếu hiện \"Sorry, this username is already taken\", nghĩa là người khác đã dùng, đổi cái khác",
    "创建成功后，BotFather 会给你一段消息，里面有一串很长的HTTP API Token ，格式大概是这样的： ": "Sau khi tạo thành công, BotFather sẽ gửi cho bạn tin nhắn, trong đó có chuỗi HTTP API Token rất dài, định dạng khoảng như thế này: ",
    "复制这串 Token 保存好！ 跟飞书的 App Secret 一样，这是机器人的"密码"，不要泄露。": "Copy chuỗi Token này lưu lại cẩn thận! Giống App Secret của Feishu, đây là \"mật khẩu\" của robot, đừng để lộ.",
    "第 2 步：告诉小龙虾让它帮你对接Telegram，然后告诉你的 Telegram 机器人信息即可": "Bước 2: Nói với Tôm Hùm để nó giúp bạn kết nối Telegram, sau đó cung cấp thông tin robot Telegram của bạn",
    "直接聊天配对 ": "Ghép nối qua chat trực tiếp ",
    "直接把你的 Token 告诉小龙虾，在网页面板的聊天框里说"帮我配置 Telegram 连接，我的 Bot Token 是 xxxxxxx"，它会自己改配置文件。": "Trực tiếp đưa Token cho Tôm Hùm, nói trong khung chat trên bảng điều khiển web \"giúp tôi cấu hình kết nối Telegram, Bot Token của tôi là xxxxxxx\", nó sẽ tự sửa file cấu hình.",
    "有时候还需要你提供你的ID：你去搜索 @userinfobot 随便和它说句话就能拿到你的ID": "Đôi khi còn cần bạn cung cấp ID: bạn tìm @userinfobot nói bừa câu gì là lấy được ID của bạn",
    "第 3 步：配对测试": "Bước 3: Kiểm tra ghép nối",
    "打开 Telegram，搜你刚创建的机器人用户名（比如 ": "Mở Telegram, tìm username robot bạn vừa tạo (ví dụ ",
    " ）": " )",
    "点进去，发一条消息（比如"你好"）": "Nhấp vào, gửi một tin nhắn (ví dụ \"xin chào\")",
    "回到终端，你会看到一个配对码": "Quay lại terminal, bạn sẽ thấy một mã ghép nối",
    "在终端输入： \n": "Nhập trong terminal: \n",
    "看到成功提示就行了！": "Thấy thông báo thành công là được!",
    # Telegram FAQ
    "Telegram 连接常见问题": "Các vấn đề thường gặp khi kết nối Telegram",
    "机器人不回复？ ": "Robot không trả lời? ",
    "→ 检查 Token 有没有复制对。常见错误：多了空格、少了字符、复制到了引号之外。": "→ Kiểm tra Token có copy đúng không. Lỗi thường gặp: thừa dấu cách, thiếu ký tự, copy ra ngoài dấu ngoặc kép.",
    "群聊里机器人只回复 @它的消息？ ": "Robot trong nhóm chat chỉ trả lời tin nhắn @nó? ",
    "→ 这是 Telegram 的 ": "→ Đây là ",
    "Privacy Mode ": "Privacy Mode ",
    "（隐私模式），默认开启。解决方法： \n1. 回到 @BotFather \n": "(chế độ riêng tư) của Telegram, mặc định bật. Cách giải quyết: \n1. Quay lại @BotFather \n",
    "2. 发送 ": "2. Gửi ",
    " \n3. 选择你的 bot \n": " \n3. Chọn bot của bạn \n",
    "4. 选择 ": "4. Chọn ",
    "\n5. ": "\n5. ",
    "重要： ": "Quan trọng: ",
    "改了之后，你需要把 bot 从群里移除，再重新加进来，新设置才会生效。": "Sau khi đổi, bạn cần xóa bot khỏi nhóm, rồi thêm lại, cài đặt mới mới có hiệu lực.",
    "机器人偶尔掉线？ ": "Robot thỉnh thoảng mất kết nối? ",
    "→ 小龙虾有自动重连机制，短暂掉线后会自动恢复。如果长时间不回复，检查你的网络连接和小龙虾运行状态： ": "→ Tôm Hùm có cơ chế tự động kết nối lại, mất kết nối tạm thời sẽ tự phục hồi. Nếu lâu không trả lời, kiểm tra kết nối mạng và trạng thái chạy của Tôm Hùm: ",
    " 。": " .",
    # QQ
    "方案 C：连接 QQ（腾讯官方教程）": "Phương án C: Kết nối QQ (hướng dẫn chính thức Tencent)",
    "好消息：QQ 现在已经有了 ": "Tin vui: QQ hiện đã có ",
    "官方原生接入 ": "kết nối native chính thức ",
    "，不需要装任何第三方插件，配置也比飞书简单很多。": ", không cần cài plugin bên thứ ba, cấu hình cũng đơn giản hơn Feishu nhiều.",
    "第 1 步：注册 QQ 开放平台": "Bước 1: Đăng ký nền tảng mở QQ",
    "打开 https://q.qq.com/qqbot/openclaw/index.html": "Mở https://q.qq.com/qqbot/openclaw/index.html",
    "用手机 QQ 扫码登录": "Dùng QQ điện thoại quét mã đăng nhập",
    "扫完自动完成注册，绑定你的 QQ 号": "Quét xong tự động hoàn thành đăng ký, liên kết số QQ của bạn",
    "第 2 步：创建 QQ 机器人": "Bước 2: Tạo robot QQ",
    "登录后进入「QQ 机器人」页面，点击「创建机器人」": "Sau khi đăng nhập vào trang \"QQ Robot\", nhấp \"Tạo robot\"",
    "填写机器人名称和简介（随便填）": "Điền tên robot và giới thiệu (điền tùy ý)",
    "创建成功后，你会看到两个重要信息：": "Sau khi tạo thành công, bạn sẽ thấy hai thông tin quan trọng:",
    "4 AppID ": "4 AppID ",
    "：一串数字": ": Một chuỗi số",
    "5 AppSecret ": "5 AppSecret ",
    "：一串密钥": ": Một chuỗi mật khẩu",
    "6 把这两个都复制保存好": "6 Copy hai cái này lưu cẩn thận",
    "⚠️ AppSecret 只会显示一次，如果忘了保存，只能重置生成新的。跟飞书的 App Secret 一样，不要泄露。": "⚠️ AppSecret chỉ hiển thị một lần, nếu quên lưu, chỉ có thể reset tạo mới. Giống App Secret của Feishu, đừng để lộ.",
    "第 3 步：在小龙虾里配置 QQ": "Bước 3: Cấu hình QQ trong Tôm Hùm",
    "选择 ": "Chọn ",
    "QQ ": "QQ ",
    "，然后依次上面的 AppID 和 AppSecret。": ", sau đó lần lượt nhập AppID và AppSecret ở trên.",
    "填完重启：": "Điền xong khởi động lại:",
    "第 4 步：测试": "Bước 4: Kiểm tra",
    "打开 QQ，找到你刚创建的机器人，发一条私聊消息试试。如果机器人能正常回复，就说明接入成功了。": "Mở QQ, tìm robot bạn vừa tạo, gửi một tin nhắn riêng thử. Nếu robot trả lời bình thường, nghĩa là kết nối thành công.",
    # QQ FAQ
    "QQ 连接常见问题": "Các vấn đề thường gặp khi kết nối QQ",
    "机器人回复"该机器人去火星了"？ ": "Robot trả lời \"Robot này đã lên sao Hỏa\"? ",
    "→ 检查 AppID 和 AppSecret 有没有填对，重新配置一次。": "→ Kiểm tra AppID và AppSecret có điền đúng không, cấu hình lại một lần.",
    "配置完成后机器人不回复？ ": "Robot không trả lời sau khi cấu hình xong? ",
    "→ 大概率是模型没配好。运行 ": "→ Rất có thể model chưa cấu hình đúng. Chạy ",
    " 检查模型配置是否正常。": " kiểm tra cấu hình model có bình thường không.",
    "能拉进群聊吗？ ": "Có thể kéo vào nhóm chat không? ",
    "→ 目前官方不建议把 QQ 机器人添加进群聊，先用私聊。": "→ Hiện tại chính thức không khuyến khích thêm robot QQ vào nhóm chat, dùng chat riêng trước.",
    "QQ 机器人支持的消息类型很全： ": "Các loại tin nhắn robot QQ hỗ trợ rất đầy đủ: ",
    "文字、图片、文件、语音、Markdown 格式都支持。但能不能处理图片和文件，取决于你接入的 AI 模型支不支持多模态。": "Văn bản, hình ảnh, file, giọng nói, định dạng Markdown đều hỗ trợ. Nhưng có thể xử lý hình ảnh và file hay không, phụ thuộc vào model AI bạn kết nối có hỗ trợ đa phương thức không.",
    # Other channels
    "其他渠道（钉钉、企微）": "Các kênh khác (DingTalk, WeCom)",
    "钉钉参考我上一篇教程↓：": "DingTalk tham khảo bài hướng dẫn trước của tôi↓:",
    "渠道": "Kênh",
    "去哪里创建应用": "Tạo ứng dụng ở đâu",
    "需要拿到什么": "Cần lấy gì",
    "特殊注意": "Lưu ý đặc biệt",
    "应用必须发布后才能用": "Ứng dụng phải phát hành mới dùng được",
    "可能遇到域名校验问题": "Có thể gặp vấn đề xác minh tên miền",
    "个人微信能连吗？ ": "WeChat cá nhân có kết nối được không? ",
    "技术上能，社区有几个第三方插件可以实现。但是微信官方不允许第三方程序控制个人微信号，被检测到可能 ": "Về kỹ thuật thì được, cộng đồng có vài plugin bên thứ ba có thể thực hiện. Nhưng WeChat chính thức không cho phép chương trình bên thứ ba điều khiển tài khoản WeChat cá nhân, bị phát hiện có thể ",
    "封号 ": "khóa tài khoản ",
    "如果你一定要用微信，建议用企业微信（不会被封），或者用一个不重要的小号测试。": "Nếu bạn nhất định muốn dùng WeChat, khuyến khích dùng WeCom (không bị khóa), hoặc dùng tài khoản phụ không quan trọng để thử.",
    "推荐对接企微仓库： ": "Kho kết nối WeCom đề xuất: ",
    # Step 4: Heartbeat
    "第四步：让它自动帮你干活（HEARTBEAT 定时任务）": "Bước bốn: Để nó tự động giúp bạn làm việc (tác vụ định kỳ HEARTBEAT)",
    "到目前为止，你的小龙虾已经有了性格、有了技能、能在聊天软件里跟你对话了。但它还是一个"你不叫我我不动"的被动助手。": "Đến thời điểm này, Tôm Hùm của bạn đã có tính cách, có kỹ năng, có thể trò chuyện trong phần mềm chat. Nhưng nó vẫn là trợ lý thụ động kiểu \"bạn không gọi thì tôi không động\".",
    "HEARTBEAT（心跳）功能可以让它 ": "Chức năng HEARTBEAT (nhịp tim) có thể cho nó ",
    "主动帮你干活 ": "chủ động giúp bạn làm việc ",
    "什么是心跳？": "Heartbeat là gì?",
    "打个比方：你请了一个助理，你跟他说"每隔半小时帮我看一下邮箱，有重要邮件就通知我"。他就每隔半小时自动去看，有事告诉你，没事就安静待着。": "Ví dụ: bạn thuê một trợ lý, nói với họ \"cứ mỗi nửa tiếng giúp tôi xem hộp thư, có email quan trọng thì thông báo\". Họ cứ mỗi nửa tiếng tự động đi xem, có việc thì báo bạn, không có thì ngồi yên.",
    "小龙虾的心跳就是这个意思。你在一个叫 ": "Heartbeat của Tôm Hùm chính là ý này. Bạn viết trong file tên ",
    " 的文件里写上你想让它定时做的事，它就会每隔一段时间（默认 30 分钟）自动醒来，把清单上的事情检查一遍。": " những việc bạn muốn nó làm định kỳ, nó sẽ mỗi khoảng thời gian (mặc định 30 phút) tự động thức dậy, kiểm tra các việc trong danh sách.",
    "怎么设置？": "Thiết lập như thế nào?",
    "方法一：跟小龙虾说（推荐）": "Cách 1: Nói với Tôm Hùm (khuyến khích)",
    "它会自动帮你创建 HEARTBEAT.md 文件并写好内容。": "Nó sẽ tự động tạo file HEARTBEAT.md và viết nội dung.",
    "方法二：手动创建": "Cách 2: Tạo thủ công",
    "心跳频率怎么调？": "Điều chỉnh tần suất heartbeat như thế nào?",
    "默认是每 30 分钟执行一次。如果你觉得太频繁或太慢，可以修改。": "Mặc định là 30 phút thực hiện một lần. Nếu bạn thấy quá thường xuyên hoặc quá chậm, có thể sửa.",
    "跟小龙虾说：": "Nói với Tôm Hùm:",
    "或者手动改配置： ": "Hoặc sửa cấu hình thủ công: ",
    "在配置文件里找到 ": "Tìm phần ",
    " 部分，把 ": " trong file cấu hình, đổi ",
    " 改成你想要的间隔（比如 ": " thành khoảng cách bạn muốn (ví dụ ",
    " 是 10 分钟， ": " là 10 phút, ",
    " 是 1 小时， ": " là 1 giờ, ",
    " 是关闭心跳）。": " là tắt heartbeat).",
    # Real use cases
    "真实的使用场景": "Các kịch bản sử dụng thực tế",
    "心跳功能最受欢迎的用法包括：": "Các cách dùng phổ biến nhất của chức năng heartbeat bao gồm:",
    "早间简报： ": "Bản tin buổi sáng: ",
    "每天早上自动推送天气 + 今日日程 + 待办事项 + 重要新闻。你打开手机就能看到一条整理好的消息，不用自己去查。": "Mỗi sáng tự động đẩy thời tiết + lịch hôm nay + việc cần làm + tin tức quan trọng. Bạn mở điện thoại là thấy tin nhắn đã được sắp xếp, không cần tự tra.",
    "邮件管家： ": "Quản gia email: ",
    "自动帮你看邮箱，重要的立刻通知你（比如客户回复、老板发的），不重要的整理成摘要等你有空再看。有用户让小龙虾通宵工作，两天清理了 4000 多封积压邮件。": "Tự động giúp bạn xem hộp thư, quan trọng thì báo ngay (ví dụ khách hàng trả lời, sếp gửi), không quan trọng thì tóm tắt đợi bạn rảnh xem. Có người dùng để Tôm Hùm làm thâu đêm, hai ngày xử lý hơn 4.000 email tồn đọng.",
    "会议提醒： ": "Nhắc nhở cuộc họp: ",
    "提前 15 分钟提醒你有会议，顺便告诉你这个会议是关于什么的、上次讨论到了哪里。": "Nhắc bạn trước 15 phút có cuộc họp, tiện thể cho biết cuộc họp về chủ đề gì, lần trước thảo luận đến đâu.",
    "心跳的一个聪明设计： ": "Một thiết kế thông minh của heartbeat: ",
    "如果小龙虾检查了一圈发现什么事都没有，它会回复一个 ": "Nếu Tôm Hùm kiểm tra một vòng thấy không có gì, nó sẽ trả lời ",
    " ，系统看到这个标记就不会打扰你。所以你不用担心每半小时都收到"一切正常"的消息。": " , hệ thống thấy nhãn này sẽ không làm phiền bạn. Vì vậy bạn không cần lo mỗi nửa tiếng nhận được tin nhắn \"mọi thứ bình thường\".",
    # Heartbeat cost
    "心跳消耗多少钱？": "Heartbeat tốn bao nhiêu tiền?",
    "每次心跳会消耗一次 AI 模型的 API 调用。如果你用的是付费模型（比如 Claude），30 分钟一次意味着一天大概 48 次调用。大部分情况下每次调用的费用很低（几分钱），但如果你的心跳任务很复杂（比如要读很多文件、搜很多网页），成本会高一些。": "Mỗi lần heartbeat tiêu tốn một lượt gọi API model AI. Nếu bạn dùng model trả phí (như Claude), 30 phút một lần nghĩa là mỗi ngày khoảng 48 lượt gọi. Đa số trường hợp chi phí mỗi lượt rất thấp (vài xu), nhưng nếu tác vụ heartbeat phức tạp (như đọc nhiều file, tìm nhiều trang web), chi phí sẽ cao hơn.",
    "省钱技巧： ": "Mẹo tiết kiệm: ",
    "\n- 心跳频率不用太高，30 分钟到 1 小时就够了 \n": "\n- Tần suất heartbeat không cần quá cao, 30 phút đến 1 giờ là đủ \n",
    "- 在配置里加上 ": "- Thêm vào cấu hình ",
    " ，让心跳只加载 HEARTBEAT.md，不加载其他文件，减少 token 消耗 \n": " , cho heartbeat chỉ tải HEARTBEAT.md, không tải file khác, giảm tiêu tốn token \n",
    "- 没有邮件/日历需求的时候，把心跳关掉（频率设为 ": "- Khi không có nhu cầu email/lịch, tắt heartbeat (đặt tần suất thành ",
    " ）": " )",
    # Step 5: Security
    "第五步：安全配置": "Bước năm: Cấu hình an toàn",
    "小龙虾跟 ChatGPT 有一个本质区别：ChatGPT 只能跟你聊天，小龙虾能 ": "Tôm Hùm có một điểm khác biệt bản chất với ChatGPT: ChatGPT chỉ chat với bạn, Tôm Hùm có thể ",
    "真的操控你的电脑和各种服务 ": "thực sự điều khiển máy tính và các dịch vụ của bạn ",
    "。发邮件、删文件、操作浏览器，它都做得到。所以安全配置很重要。": ". Gửi email, xóa file, thao tác trình duyệt, nó đều làm được. Vì vậy cấu hình an toàn rất quan trọng.",
    "什么是 Exec Approvals？": "Exec Approvals là gì?",
    "当小龙虾要执行一些高风险操作（比如删除文件、发送邮件、运行不认识的程序），它不会直接做，而是先发一个审批请求给你，等你同意了才执行。这个机制叫 ": "Khi Tôm Hùm muốn thực hiện thao tác rủi ro cao (như xóa file, gửi email, chạy chương trình lạ), nó không làm ngay mà gửi yêu cầu phê duyệt cho bạn trước, đợi bạn đồng ý mới thực hiện. Cơ chế này gọi là ",
    "Exec Approvals ": "Exec Approvals ",
    "（执行审批）。": "(phê duyệt thực thi).",
    "打个比方：你让助理帮你清理办公桌。一个好助理会先问"桌上那份合同要不要留着？"，而不是直接全扔了。Exec Approvals 就是这个"先问再做"的机制。": "Ví dụ: bạn nhờ trợ lý dọn bàn làm việc. Trợ lý giỏi sẽ hỏi trước \"hợp đồng trên bàn có giữ lại không?\", chứ không vứt hết. Exec Approvals chính là cơ chế \"hỏi trước rồi mới làm\".",
    "你收到审批请求后有三个选择：": "Sau khi nhận yêu cầu phê duyệt, bạn có ba lựa chọn:",
    "选项": "Tùy chọn",
    "意思": "Ý nghĩa",
    "什么时候用": "Khi nào dùng",
    "Allow once（允许一次）": "Allow once (cho phép một lần)",
    "这次可以做，下次还要问我": "Lần này được làm, lần sau vẫn phải hỏi",
    "不确定的时候": "Khi không chắc chắn",
    "Always allow（永远允许）": "Always allow (luôn cho phép)",
    "以后这类操作不用再问了": "Sau này loại thao tác này không cần hỏi nữa",
    "你确认这个操作是安全的": "Bạn xác nhận thao tác này an toàn",
    "Deny（拒绝）": "Deny (từ chối)",
    "不要做": "Đừng làm",
    "你觉得这个操作不对": "Bạn thấy thao tác này không đúng",
    # Security levels
    "三种安全等级": "Ba mức an toàn",
    "等级": "Mức",
    "相当于": "Tương đương",
    "适合谁": "Phù hợp với ai",
    "严格模式": "Chế độ nghiêm ngặt",
    "每件事都要先请示": "Mọi việc đều phải xin phép trước",
    "刚开始用、还不太信任 AI 的新手": "Người mới bắt đầu dùng, chưa tin tưởng AI lắm",
    "默认模式": "Chế độ mặc định",
    "小事自己做，大事先问": "Việc nhỏ tự làm, việc lớn hỏi trước",
    "大多数用户（推荐）": "Đa số người dùng (khuyến khích)",
    "关闭审批": "Tắt phê duyệt",
    "完全放飞，什么都自己做": "Thả hoàn toàn, tự làm mọi thứ",
    "完全信任 AI 的老手（有风险）": "Người dùng lâu năm tin tưởng AI hoàn toàn (có rủi ro)",
    "新手建议用默认模式。 ": "Người mới khuyến khích dùng chế độ mặc định. ",
    "用一段时间之后，你会发现某些操作它每次都问你、每次你都同意，这时候就可以把这些操作设为"永远允许"来减少打扰。": "Dùng một thời gian, bạn sẽ thấy một số thao tác nó lần nào cũng hỏi, lần nào bạn cũng đồng ý, lúc đó có thể đặt các thao tác này thành \"luôn cho phép\" để giảm phiền phức.",
    # 3 Security must-dos
    "三件一定要做的安全事项": "Ba việc nhất định phải làm về an toàn",
    "安全研究人员已经发现，全球有超过 42,000 个小龙虾实例因为配置不当暴露在公网上，其中近 1,800 个泄露了 API 密钥和聊天记录。不要成为其中一个。": "Các nhà nghiên cứu bảo mật đã phát hiện, toàn cầu có hơn 42.000 phiên bản Tôm Hùm bị lộ trên mạng công cộng do cấu hình sai, trong đó gần 1.800 bị lộ API key và lịch sử chat. Đừng trở thành một trong số đó.",
    "第一件：确保端口没有开放到公网": "Việc thứ nhất: Đảm bảo cổng không mở ra mạng công cộng",
    "什么是端口？什么是公网？ ": "Cổng là gì? Mạng công cộng là gì? ",
    "你的电脑就像你家的房子，端口就像房子上的窗户。小龙虾用的窗户编号是 18789。"开放到公网"就是把这扇窗户朝着大街打开，任何路过的人都能往里面看。": "Máy tính của bạn giống ngôi nhà, cổng giống cửa sổ trên nhà. Tôm Hùm dùng cửa sổ số 18789. \"Mở ra mạng công cộng\" nghĩa là mở cửa sổ này hướng ra đường, ai đi qua cũng nhìn được vào trong.",
    "小龙虾默认的访问地址是 ": "Địa chỉ truy cập mặc định của Tôm Hùm là ",
    " ，这里 ": " , ở đây ",
    " 的意思是"只有我自己能访问"。 ": " có nghĩa là \"chỉ mình tôi truy cập được\". ",
    "不要把它改成 ": "Đừng đổi thành ",
    "（那就是朝大街开窗户了）。": "(đó là mở cửa sổ ra đường rồi đấy).",
    "怎么检查？运行：": "Kiểm tra thế nào? Chạy:",
    "看输出里的地址，如果是 ": "Xem địa chỉ trong kết quả, nếu là ",
    " 就是安全的。": " thì an toàn.",
    "第二件：保护好你的 API Key": "Việc thứ hai: Bảo vệ API Key của bạn",
    "你在配置过程中输入了各种 API Key（AI 模型的、飞书的、Tavily 的等等）。这些 Key 相当于你的密码：": "Trong quá trình cấu hình bạn đã nhập các API Key (của model AI, Feishu, Tavily...). Các Key này tương đương mật khẩu của bạn:",
    "不要把包含 API Key 的配置文件上传到 GitHub（哪怕是私有仓库）": "Đừng upload file cấu hình chứa API Key lên GitHub (dù là repo riêng tư)",
    "不要把 Key 发在群聊里": "Đừng gửi Key trong nhóm chat",
    "不要截图发给别人的时候暴露 Key": "Đừng lộ Key khi chụp màn hình gửi cho người khác",
    "第三件：定期更新小龙虾": "Việc thứ ba: Cập nhật Tôm Hùm định kỳ",
    "新版本经常修复安全漏洞。建议至少每两周更新一次。": "Phiên bản mới thường xuyên vá lỗ hổng bảo mật. Khuyến khích cập nhật ít nhất hai tuần một lần.",
    # Step 6: Memory
    "第六步：让它记住你（记忆系统）": "Bước sáu: Để nó nhớ bạn (hệ thống bộ nhớ)",
    "不知道你有没有这种体验：跟小龙虾聊得挺好，关掉之后下次打开，它又什么都不记得了，像换了一个人。你说"继续昨天的话题"，它一脸懵。": "Không biết bạn có trải nghiệm này không: chat với Tôm Hùm rất vui, tắt đi mở lại lần sau, nó lại không nhớ gì, như đổi người. Bạn nói \"tiếp tục chủ đề hôm qua\", nó ngơ ngác.",
    "这是因为 AI 每次启动默认是"失忆"的。但小龙虾有一套记忆系统可以解决这个问题。": "Đó là vì AI mỗi lần khởi động mặc định bị \"mất trí nhớ\". Nhưng Tôm Hùm có hệ thống bộ nhớ giải quyết vấn đề này.",
    "记忆系统是怎么工作的？": "Hệ thống bộ nhớ hoạt động như thế nào?",
    "小龙虾的记忆分两层，就像人的大脑一样：": "Bộ nhớ của Tôm Hùm chia hai tầng, giống não người:",
    "MEMORY.md：长期记忆（相当于你的"个人认知"）": "MEMORY.md: Bộ nhớ dài hạn (tương đương \"nhận thức cá nhân\" của bạn)",
    "这是一个文件，小龙虾会在里面记录跨越多次对话都有用的信息：": "Đây là một file, Tôm Hùm sẽ ghi lại thông tin hữu ích qua nhiều cuộc trò chuyện:",
    "你的偏好和习惯（"老板喜欢简洁的汇报方式"）": "Sở thích và thói quen của bạn (\"sếp thích cách báo cáo ngắn gọn\")",
    "重要的决定（"我们决定用飞书而不是钉钉"）": "Quyết định quan trọng (\"chúng ta quyết định dùng Feishu thay vì DingTalk\")",
    "学到的经验（"上次帮老板发邮件忘了加附件，以后发邮件前要确认"）": "Kinh nghiệm học được (\"lần trước giúp sếp gửi email quên đính kèm, sau này gửi email phải xác nhận trước\")",
    "memory/YYYY-MM-DD.md：每日日志（相当于"工作日志"）": "memory/YYYY-MM-DD.md: Nhật ký hàng ngày (tương đương \"nhật ký công việc\")",
    "每天的对话结束后，小龙虾会自动创建一个当天的日志文件，记录今天发生的事情、做了什么决定、有什么变化。第二天启动时，它会读最近 2-3 天的日志，保持记忆的连续性。": "Sau khi kết thúc trò chuyện mỗi ngày, Tôm Hùm tự động tạo file nhật ký trong ngày, ghi lại hôm nay xảy ra gì, quyết định gì, có thay đổi gì. Khi khởi động ngày hôm sau, nó sẽ đọc nhật ký 2-3 ngày gần nhất, duy trì tính liên tục của bộ nhớ.",
    # Using memory
    "怎么使用记忆功能？": "Sử dụng chức năng bộ nhớ như thế nào?",
    "查看它记了什么：": "Xem nó ghi nhớ gì:",
    "直接在聊天框里问：": "Hỏi trực tiếp trong khung chat:",
    "它会把 MEMORY.md 里的内容整理好告诉你。": "Nó sẽ sắp xếp nội dung trong MEMORY.md rồi nói cho bạn.",
    "让它记住特定的事：": "Để nó nhớ việc cụ thể:",
    "它会把这些信息写进 MEMORY.md。": "Nó sẽ ghi thông tin này vào MEMORY.md.",
    "让它忘掉某些事：": "Để nó quên một số việc:",
    "纠正错误的记忆：": "Sửa bộ nhớ sai:",
    "自动记忆": "Ghi nhớ tự động",
    "除了你手动让它记，小龙虾还有一个自动记忆功能：当一次对话快结束时（上下文窗口快满了），它会自动扫描对话内容，把值得记住的信息提炼到 MEMORY.md 里。": "Ngoài việc bạn yêu cầu thủ công, Tôm Hùm còn có chức năng ghi nhớ tự động: khi cuộc trò chuyện sắp kết thúc (cửa sổ ngữ cảnh sắp đầy), nó sẽ tự động quét nội dung trò chuyện, trích xuất thông tin đáng nhớ vào MEMORY.md.",
    "这就像一个好助理，每天下班前会把当天重要的事情记到笔记本里，第二天上班时先翻一下笔记本回顾。": "Giống như trợ lý giỏi, mỗi ngày trước khi tan làm ghi những việc quan trọng trong ngày vào sổ, hôm sau đi làm lật sổ xem lại trước.",
    # Memory limitations
    "记忆的局限": "Hạn chế của bộ nhớ",
    "• 有大小限制： ": "• Có giới hạn kích thước: ",
    "MEMORY.md 不能无限大，单个文件超过约 20,000 个字符会被截断。所以它只保留最重要的信息，不会记住所有对话细节。": "MEMORY.md không thể lớn vô hạn, một file vượt quá khoảng 20.000 ký tự sẽ bị cắt. Nên nó chỉ giữ lại thông tin quan trọng nhất, không nhớ hết mọi chi tiết cuộc trò chuyện.",
    "• 可能会冲突： ": "• Có thể xung đột: ",
    "如果你改了偏好但忘了告诉它更新记忆，它可能还按旧的来。遇到这种情况直接说"帮我更新记忆，把 xxx 改成 yyy"。": "Nếu bạn đổi sở thích nhưng quên bảo nó cập nhật bộ nhớ, nó có thể vẫn làm theo cái cũ. Gặp tình huống này nói thẳng \"giúp tôi cập nhật bộ nhớ, đổi xxx thành yyy\".",
    "• 只记文字： ": "• Chỉ nhớ văn bản: ",
    "不能记图片、文件这些东西。": "Không nhớ được hình ảnh, file.",
    "小技巧： ": "Mẹo nhỏ: ",
    "如果你觉得小龙虾记忆混乱了，可以说"帮我看看你的 MEMORY.md，把过时的信息清理一下"。它会自己整理。": "Nếu bạn thấy bộ nhớ Tôm Hùm lộn xộn, có thể nói \"giúp tôi xem MEMORY.md, dọn dẹp thông tin lỗi thời đi\". Nó sẽ tự sắp xếp.",
    # Step 7: MCP
    "第七步：连接外部服务（MCP 入门）": "Bước bảy: Kết nối dịch vụ bên ngoài (MCP nhập môn)",
    "这一步是进阶内容。如果你已经觉得小龙虾够用了，可以先跳过，以后需要了再来看。": "Bước này là nội dung nâng cao. Nếu bạn thấy Tôm Hùm đã đủ dùng, có thể bỏ qua trước, khi nào cần thì quay lại xem.",
    "MCP 是什么？": "MCP là gì?",
    "MCP 全名叫 Model Context Protocol。名字听着吓人，用一个例子就能听懂：": "MCP tên đầy đủ là Model Context Protocol. Tên nghe đáng sợ, nhưng dùng một ví dụ là hiểu ngay:",
    "你家有一个智能音箱，它自己只能放歌和报天气。但如果你把它跟智能灯泡连起来，你就可以说"关灯"，它就帮你关了。再连上扫地机器人，你就可以说"扫地"。连的东西越多，它能帮你做的事就越多。": "Nhà bạn có một loa thông minh, bản thân nó chỉ phát nhạc và báo thời tiết được. Nhưng nếu bạn kết nối với bóng đèn thông minh, bạn có thể nói \"tắt đèn\", nó tắt giúp bạn. Kết nối thêm robot hút bụi, bạn có thể nói \"hút bụi\". Kết nối càng nhiều, nó giúp bạn làm được càng nhiều việc.",
    "MCP 就是让小龙虾"连接"其他软件和服务的技术。连上 Notion，它就能帮你管笔记；连上 GitHub，它就能帮你看代码；连上 Google 日历，它就能帮你排日程。": "MCP chính là công nghệ cho Tôm Hùm \"kết nối\" với phần mềm và dịch vụ khác. Kết nối Notion, nó giúp bạn quản lý ghi chú; kết nối GitHub, nó giúp bạn xem code; kết nối Google Calendar, nó giúp bạn sắp lịch.",
    "怎么连？": "Kết nối thế nào?",
    "一行命令就行。举几个例子：": "Một dòng lệnh là xong. Vài ví dụ:",
    "连接 Notion（笔记管理）：": "Kết nối Notion (quản lý ghi chú):",
    "连上之后你可以说："帮我在 Notion 里新建一页，标题是'本周计划'"。": "Kết nối xong bạn có thể nói: \"Giúp tôi tạo trang mới trong Notion, tiêu đề là 'Kế hoạch tuần này'\".",
    "连接 GitHub（代码管理）：": "Kết nối GitHub (quản lý code):",
    "连上之后你可以说："帮我看看 GitHub 上有没有新的 Issue"。": "Kết nối xong bạn có thể nói: \"Giúp tôi xem GitHub có Issue mới không\".",
    "不知道该连什么？ ": "Không biết nên kết nối gì? ",
    "跟小龙虾说"我想连接 xxx 服务，你能帮我配置吗"，它会告诉你具体怎么做。": "Nói với Tôm Hùm \"tôi muốn kết nối dịch vụ xxx, bạn giúp tôi cấu hình được không\", nó sẽ nói cụ thể cách làm.",
    "MCP 连不上怎么办？": "MCP không kết nối được thì sao?",
    "1 检查命令： ": "1 Kiểm tra lệnh: ",
    " 看服务在不在列表里": " xem dịch vụ có trong danh sách không",
    "2 检查网络： ": "2 Kiểm tra mạng: ",
    "有些服务需要梯子": "Một số dịch vụ cần VPN",
    "3 检查授权： ": "3 Kiểm tra ủy quyền: ",
    "有些服务需要你先在它的网站上登录授权（比如 Notion 需要你授权小龙虾访问你的工作区），按照提示操作就行": "Một số dịch vụ cần bạn đăng nhập ủy quyền trên website trước (ví dụ Notion cần bạn ủy quyền Tôm Hùm truy cập workspace), làm theo hướng dẫn là được",
    # Before/After comparison
    "配置完成后的效果对比": "So sánh hiệu quả trước và sau cấu hình",
    "之前（刚装好）": "Trước (vừa cài xong)",
    "现在（配好之后）": "Bây giờ (sau khi cấu hình)",
    "跟 ChatGPT 没区别，只能在网页面板聊天": "Chẳng khác gì ChatGPT, chỉ chat được trên bảng web",
    "在飞书/Telegram 里随时 @它": "Bất cứ lúc nào @nó trong Feishu/Telegram",
    "每次都像跟陌生人聊天": "Mỗi lần như chat với người lạ",
    "它知道你是谁、记得你的偏好": "Nó biết bạn là ai, nhớ sở thích của bạn",
    "只能回答问题": "Chỉ trả lời câu hỏi",
    "能搜资讯、抓网页、总结文章、操控浏览器": "Tìm tin tức, thu thập web, tóm tắt bài viết, điều khiển trình duyệt",
    "你不叫它就不动": "Bạn không gọi nó không động",
    "每天自动帮你检查邮件、提醒日程": "Mỗi ngày tự động giúp bạn kiểm tra email, nhắc lịch",
    "说话风格千篇一律": "Phong cách nói chuyện na ná nhau",
    "按照你喜欢的方式沟通": "Giao tiếp theo cách bạn thích",
    "关掉之后下次全忘了": "Tắt đi lần sau quên hết",
    "记得你之前说过什么": "Nhớ bạn đã nói gì trước đó",
    # Quick reference checklist
    "配置清单（快速参考）": "Danh sách cấu hình (tham khảo nhanh)",
    "怕你看完之后忘了要做什么，这里给你一份最精简的清单：": "Sợ bạn đọc xong quên phải làm gì, đây là danh sách tinh gọn nhất:",
    "必做（30 分钟搞定）": "Phải làm (30 phút xong)",
    "创建 SOUL.md：从三个模板里选一个，复制粘贴或让小龙虾帮你创建": "Tạo SOUL.md: chọn một trong ba template, copy paste hoặc để Tôm Hùm giúp tạo",
    "创建 USER.md：把你的名字、时区、偏好填进去": "Tạo USER.md: điền tên, múi giờ, sở thích vào",
    "安装 4 个基础技能：Tavily Search、Firecrawl、Summarize、Browser": "Cài 4 kỹ năng cơ bản: Tavily Search, Firecrawl, Summarize, Browser",
    "连接一个聊天工具：国内选飞书，海外选 Telegram": "Kết nối một công cụ chat: Trung Quốc chọn Feishu, nước ngoài chọn Telegram",
    "检查安全配置：确认端口是 127.0.0.1，API Key 没有泄露": "Kiểm tra cấu hình an toàn: xác nhận cổng là 127.0.0.1, API Key không bị lộ",
    "建议做（15 分钟）": "Nên làm (15 phút)",
    "创建 IDENTITY.md：给你的 AI 助手取个名字": "Tạo IDENTITY.md: đặt tên cho trợ lý AI",
    "设置心跳任务：让它每天自动帮你检查邮件/日程": "Thiết lập tác vụ heartbeat: để nó mỗi ngày tự động kiểm tra email/lịch",
    "测试记忆功能：让它记住一条信息，重启后看还记不记得": "Thử chức năng bộ nhớ: để nó nhớ một thông tin, khởi động lại xem còn nhớ không",
    "以后再说": "Để sau",
    "连接 MCP 服务（需要了再配）": "Kết nối dịch vụ MCP (cần mới cấu hình)",
    "安装更多技能（需要什么装什么，去 ClawHub 逛逛）": "Cài thêm kỹ năng (cần gì cài nấy, vào ClawHub dạo)",
    "精调 AGENTS.md（用一段时间后根据实际需要调整工作规则）": "Tinh chỉnh AGENTS.md (dùng một thời gian rồi điều chỉnh quy tắc theo nhu cầu thực tế)",
    "连接更多聊天渠道（钉钉、QQ 等）": "Kết nối thêm kênh chat (DingTalk, QQ...)",
    # Closing
    "小互说两句： ": "Tiểu Hỗ nói vài lời: ",
    "第一篇教程帮你把小龙虾装上了，这一篇帮你把它变成了真正的私人助手。很多人装完小龙虾之后用了两天就放弃了，原因几乎都一样：没做配置。一个没有人设、没有技能、只能在网页面板聊天的小龙虾，确实跟 ChatGPT 没什么区别。": "Bài hướng dẫn đầu tiên giúp bạn cài Tôm Hùm, bài này giúp bạn biến nó thành trợ lý cá nhân thực sự. Nhiều người cài Tôm Hùm xong dùng hai ngày rồi bỏ, nguyên nhân hầu như giống nhau: không cấu hình. Một Tôm Hùm không có nhân vật, không có kỹ năng, chỉ chat trên bảng web, đúng là chẳng khác gì ChatGPT.",
    "但你花 30 分钟配完之后，就完全不一样了。你可以在飞书里随时 @它帮你查资料，让它每天早上自动给你推一条简报，让它记住你的偏好下次不用再说。它会越用越懂你。": "Nhưng bạn dành 30 phút cấu hình xong, hoàn toàn khác. Bạn có thể bất cứ lúc nào @nó trong Feishu nhờ tra tài liệu, để nó mỗi sáng tự động đẩy bản tin cho bạn, để nó nhớ sở thích lần sau không cần nói lại. Nó càng dùng càng hiểu bạn.",
    "还记得开头说的那个原则吗？ ": "Còn nhớ nguyên tắc đầu bài không? ",
    "能让小龙虾干的坚决不自己干。 ": "Việc gì Tôm Hùm làm được thì kiên quyết không tự làm. ",
    "这篇教程里教了很多手动配置的方法，但当你真正用起来的时候，大多数配置都可以直接跟它说"帮我配一下 xxx"来完成。它就是你的助理，让它帮你干活才是正确的打开方式。": "Bài hướng dẫn này dạy nhiều cách cấu hình thủ công, nhưng khi bạn thực sự sử dụng, đa số cấu hình đều có thể nói thẳng \"giúp tôi cấu hình xxx\" là xong. Nó là trợ lý của bạn, để nó giúp làm việc mới là cách dùng đúng.",
    "不过说实话，配置只是起点。": "Nhưng nói thật, cấu hình chỉ là điểm khởi đầu.",
    "小龙虾真正的杀手锏是它的 ": "Vũ khí bí mật thực sự của Tôm Hùm là ",
    "工作流能力 ": "khả năng workflow ",
    "：把多个技能串起来，让它自动完成一整套操作。比如"每天早上自动抓取行业新闻→总结成简报→发到飞书群里→同步到 Notion"，这一整套你说一句话它就全干了。": ": nối nhiều kỹ năng lại, để nó tự động hoàn thành cả bộ thao tác. Ví dụ \"mỗi sáng tự động thu thập tin tức ngành→tóm tắt thành bản tin→gửi vào nhóm Feishu→đồng bộ lên Notion\", cả bộ này bạn nói một câu nó làm hết.",
    "下一期，我会 ": "Kỳ tới, tôi sẽ ",
    "手把手教你怎么用小龙虾打造属于你自己的自动化工作流 ": "hướng dẫn từng bước cách dùng Tôm Hùm tạo workflow tự động hóa của riêng bạn ",
    "，让它真正帮你自动化办公。敬请期待。": ", để nó thực sự giúp bạn tự động hóa công việc. Hãy đón chờ.",
    "有什么配置上的问题，评论区见。": "Có vấn đề gì về cấu hình, hẹn gặp ở phần bình luận.",
    "____________": "____________",
    "End.": "End.",
    "感 谢 阅 读": "Cảm ơn đã đọc",
    "点赞，转发，关注关注关注↓↓": "Like, chia sẻ, theo dõi↓↓",
    # Bullet markers
    "• ": "• ",
    # Various short fragments that might appear
    "你："帮我查一下明天上海的天气" ": "Bạn: \"Giúp tôi tra thời tiết ngày mai ở Thượng Hải\" ",
    'AI："好的！我很高兴能帮助您查询天气信息！明天上海的天气预计是……"': 'AI: "Vâng! Tôi rất vui được giúp bạn tra thông tin thời tiết! Thời tiết ngày mai ở Thượng Hải dự kiến là..."',
    'AI："小互，明天上海：多云转晴，18-25°C，适合出门。"': 'AI: "Tiểu Hỗ, ngày mai Thượng Hải: mây chuyển nắng, 18-25°C, thích hợp ra ngoài."',
    "你："帮我查一下明天上海的天气" ": "Bạn: \"Giúp tôi tra thời tiết ngày mai ở Thượng Hải\" ",
}

# Process all blocks
translated_count = 0
kept_count = 0
total_text = 0

out = copy.deepcopy(data)

for block in out['blocks']:
    for el in block['elements']:
        if el['type'] == 'text_run':
            total_text += 1
            content = el['content']
            if content in trans:
                el['content'] = trans[content]
                if trans[content] != content:
                    translated_count += 1
                else:
                    kept_count += 1
            elif content.strip() == '':
                kept_count += 1
            else:
                # Check if it's a URL or technical content that should be kept
                stripped = content.strip()
                if (stripped.startswith('http') or
                    stripped.startswith('~/') or
                    stripped.startswith('openclaw') or
                    stripped.startswith('nano ') or
                    stripped.startswith('Ctrl') or
                    stripped in ['.md', '~/clawd/', 'Y', 'openclaw doctor', 'openclaw status',
                                 'im', 'im:message', 'im:message:send_as_bot', 'im:chat',
                                 'im:resource', '1.0.0', '127.0.0.1:18789', '127.0.0.1',
                                 '0.0.0.0', 'HEARTBEAT.md', 'heartbeat', 'every', '"10m"',
                                 '"1h"', '"0m"', 'HEARTBEAT_OK', 'lightContext: true',
                                 'openclaw mcp list', '/start', '/newbot', 'bot',
                                 'my_ai_helper_bot', 'My AI Assistant', 'Disable',
                                 '/setprivacy', 'openclaw pairing approve telegram <配对码>',
                                 'cli_a5xxxxxxxxxxxxxxxx', 'SOUL.md', 'USER.md',
                                 'IDENTITY.md', 'AGENTS.md', 'HEARTBEAT.md', 'MEMORY.md',
                                 'openclaw-china', '12306', 'A-Share',
                                 'openclaw skills install 12306',
                                 'openclaw skills install a-share',
                                 '8649345089:AAG5eXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
                                 'Token + Encoding-AESKey', 'Client ID + Client Secret',
                                 'Telegram'] or
                    re.match(r'^[A-Za-z0-9_./:\-@#%=&?+]+$', stripped)):
                    kept_count += 1
                else:
                    # Not found in map - print for review
                    print(f'MISSING: [{content}]')
                    kept_count += 1

print(f'\nTotal text elements: {total_text}')
print(f'Translated: {translated_count}')
print(f'Kept: {kept_count}')

# Save
with open('_art31_trans.json', 'w', encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

print(f'Saved _art31_trans.json')
