# -*- coding: utf-8 -*-
"""Translate art30: OpenClaw tutorial CN->VI"""
import json, sys, re

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')

with open('_art30_orig.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Build translation map: index -> Vietnamese text
# We translate ALL text_run content from Chinese to Vietnamese
# Keep: URLs, code commands, proper nouns (OpenClaw, ChatGPT, etc.), version numbers

CN_TO_VI = {}

def t(idx, vi):
    CN_TO_VI[idx] = vi

# Block 0 - page title
t(0, "Hướng dẫn cài đặt OpenClaw Tôm Hùm từ zero cho người mới bắt đầu")
t(1, "🔗 Link bài gốc: ")
# 2 is URL - keep as is
t(3, "Bài gốc: Tiểu Hỗ đáng thương - Tiểu Hỗ AI")
t(4, "Ngày 6 tháng 3 năm 2026, 10:51 - An Huy")
t(5, "Không cần biết lập trình, không sao cả")
t(6, "Cứ làm theo là được...")
t(7, "Mỗi bước đều có hướng dẫn chi tiết, học sinh tiểu học cũng hiểu được.")

t(8, "OpenClaw là gì? Giải thích trong một câu")
t(9, "OpenClaw là một ")
t(10, "trợ lý AI cá nhân ")
t(11, "được cài trên chính máy tính của bạn.")
t(12, "Điểm khác biệt lớn nhất so với ChatGPT là: ChatGPT chỉ có thể trò chuyện với bạn, còn OpenClaw có thể ")
t(13, "thực sự giúp bạn làm việc ")
t(14, ": gửi email, quản lý lịch trình, sắp xếp file, thu thập dữ liệu web, điều khiển nhà thông minh...")
t(15, "Và nó là mã nguồn mở miễn phí (nhưng cần tự trả phí API cho mô hình AI, phía sau sẽ hướng dẫn cách chọn phương án tiết kiệm nhất).")
t(16, "Sau khi cài xong, bạn có thể trò chuyện với nó qua QQ, Feishu, DingTalk, Telegram hoặc trang web để nhờ nó giúp việc.")
t(17, "Nó hot đến mức nào? ")
t(18, "OpenClaw đã đứng đầu bảng xếp hạng sao trên GitHub, vượt qua React (framework frontend phổ biến nhất thế giới) để đứng số 1, chỉ trong hơn một tháng. Đây là một trong những dự án AI mã nguồn mở được quan tâm nhất hiện nay.")
t(19, "Trước khi bắt đầu: Bạn cần gì")
t(20, "Những gì bạn cần chuẩn bị")
t(21, "Giải thích")
t(22, "Một chiếc máy tính")
t(23, "Mac hoặc Windows đều được (Mac trải nghiệm tốt hơn, Windows cần cài thêm một thứ, phía sau sẽ hướng dẫn)")
t(24, "Kết nối mạng")
t(25, "Đôi khi có thể cần truy cập mạng quốc tế (quá trình cài đặt cần tải từ GitHub)")
t(26, "Khoảng 30 phút")
t(27, "Lần đầu cài sẽ hơi lâu, sau khi quen rồi sẽ rất nhanh")
t(28, "Không cần: ")
t(29, "Không cần biết lập trình, không cần hiểu code. Mặc dù phải dùng \"Terminal\" (một cửa sổ để nhập lệnh), nhưng tất cả lệnh đều là copy paste, bạn không cần tự viết bất kỳ đoạn code nào.")
t(30, "\"Terminal\" là gì? ")
t(31, "Terminal là một cửa sổ để giao tiếp với máy tính. Bình thường bạn dùng chuột click vào biểu tượng để thao tác, Terminal là dùng cách gõ chữ để thao tác máy tính. Ví dụ bạn gõ \"mở trình duyệt\" trong Terminal, máy tính sẽ mở trình duyệt. Nghe có vẻ cao siêu, nhưng thực ra chỉ là copy paste lệnh mà thôi.")
t(32, "Lưu ý quan trọng: Quy trình cài đặt Mac và Windows khác nhau")
t(33, "Vì sự khác biệt giữa Mac và Windows khá lớn, phía dưới sẽ chia thành hai hướng dẫn. ")
t(34, "Vui lòng chỉ xem phần tương ứng với loại máy tính của bạn.")
t(35, "• Người dùng Mac ")
t(36, "→ Xem tiếp phần \"Quy trình cài đặt Mac\"")
t(37, "• Người dùng Windows ")
t(38, "→ Chuyển đến phần \"Quy trình cài đặt Windows\"")
t(39, "Phần hướng dẫn cấu hình (chọn mô hình AI, nhập khóa API, v.v.) giống nhau cho cả hai hệ thống, sẽ được hướng dẫn chung ở phần sau.")
t(40, "🍎 Quy trình cài đặt Mac (Người dùng Win bỏ qua)")
t(41, "Mac bước 1: Mở Terminal")
t(42, "1 ")
t(43, "Nhấn tổ hợp phím ")
t(44, "Command + Space")
t(45, " (nhấn đồng thời hai phím này), sẽ hiện ra một hộp tìm kiếm (gọi là Spotlight)")
t(46, "2 ")
t(47, "Trong hộp tìm kiếm, gõ ")
t(48, "Terminal")
t(49, " (hoặc gõ tiếng Trung \"终端\")")
t(50, "3 ")
t(51, "Nhấn Enter, hoặc click vào \"Terminal\" trong kết quả tìm kiếm")
t(52, "4 ")
t(53, "Sẽ hiện ra một cửa sổ, bên trong có một dòng chữ và một con trỏ nhấp nháy, ")
t(54, "đó chính là Terminal")
t(55, "Terminal trông như thế nào? ")
t(56, "Nó là một cửa sổ nền trắng (hoặc đen), phía trên có thể hiển thị tên máy tính và tên người dùng, cuối cùng có một ký hiệu ")
t(57, "$")
t(58, " hoặc ")
t(59, "%")
t(60, " và một con trỏ nhấp nháy. Bạn gõ lệnh ở đây, nhấn Enter, máy tính sẽ thực thi.")
t(61, "Làm sao để paste lệnh trong Terminal? ")
t(62, "Trước tiên copy lệnh trên trang web (chọn văn bản rồi nhấn ")
t(63, "Command + C")
t(64, " ), sau đó chuyển sang cửa sổ Terminal, nhấn ")
t(65, "Command + V")
t(66, " để paste, cuối cùng nhấn Enter để thực thi.")
t(67, "Mac bước 2: Kiểm tra đã có Homebrew chưa")
t(68, "⚠️ ")
t(69, "Lưu ý: Thông thường, OpenClaw sẽ tự động cài Homebrew và Node.js khi bạn cài OpenClaw, nó sẽ cài kèm luôn.")
t(70, "Vì vậy ở đây chúng ta chuyển thẳng đến ")
t(71, "bước 5 ")
t(72, ", nếu chưa cài thì quay lại bước này!")
t(73, "Homebrew là một \"trình quản lý phần mềm\" trên Mac, dùng để cài các công cụ phát triển. Cài OpenClaw cần có nó trước.")
t(74, "Nhập dòng lệnh sau trong Terminal, nhấn Enter:")
t(75, "Xem kết quả:")
t(76, "• ")
t(77, "Nếu hiển thị số phiên bản tương tự như ")
t(78, "Homebrew 4.x.x")
t(79, " → Nghĩa là bạn đã có rồi, ")
t(80, "bỏ qua bước tiếp theo, chuyển thẳng đến \"Mac bước 4\"")
t(81, "• ")
t(82, "Nếu hiển thị ")
t(83, "command not found: brew")
t(84, " hoặc báo lỗi → Nghĩa là chưa cài, tiếp tục bước tiếp theo")
t(85, "Mac bước 3: Cài đặt Homebrew")
t(86, "Bước này mất khoảng 3-10 phút ")
t(87, ", tùy thuộc vào tốc độ mạng. Trong quá trình cài sẽ yêu cầu bạn nhập mật khẩu máy tính (mật khẩu đăng nhập).")
t(88, "Nếu máy bạn đã có, có thể bỏ qua!")
t(89, "Copy paste dòng lệnh sau trong Terminal, nhấn Enter:")
t(90, "Những tình huống bạn sẽ gặp trong quá trình cài đặt:")
t(91, "1 Yêu cầu bạn nhấn Enter để xác nhận ")
t(92, "→ Nhấn Enter")
t(93, "2 Yêu cầu nhập mật khẩu ")
t(94, "→ Nhập mật khẩu đăng nhập Mac (lưu ý: khi nhập mật khẩu, màn hình sẽ không hiển thị ký tự nào, đây là bình thường! Không phải bị đơ, mà là để bảo vệ quyền riêng tư. Gõ mù xong mật khẩu rồi nhấn Enter)")
t(95, "3 Màn hình cuộn một đống tiếng Anh ")
t(96, "→ Hiện tượng bình thường, đợi nó chạy xong là được")
t(97, "4 Cuối cùng xuất hiện \"Installation successful!\" ")
t(98, "→ Chúc mừng, cài đặt thành công!")
t(99, "Nếu bạn dùng Apple Silicon (Mac chip M1/M2/M3/M4):")
t(100, "Sau khi cài xong Homebrew, nó có thể nhắc bạn chạy hai dòng lệnh để cấu hình đường dẫn. Thường sẽ tương tự như thế này:")
t(101, "Hãy copy paste nguyên văn hai dòng lệnh mà Terminal hiển thị để thực thi ")
t(102, "(đừng dùng của tôi viết ở trên, hãy lấy theo những gì Terminal của bạn thực tế hiển thị).")
t(103, "Làm sao biết mình có phải Apple Silicon không? ")
t(104, "Click vào biểu tượng Apple ở góc trên bên trái màn hình → \"Giới thiệu về máy Mac\", nếu phần chip ghi là \"Apple M1\", \"Apple M2\" hoặc tương tự, thì đúng rồi.")
t(105, "Xác nhận Homebrew đã cài thành công:")
t(106, "Thấy số phiên bản là cài thành công.")
t(107, "Mac bước 4: Cài đặt Node.js")
t(108, "Node.js là một môi trường mà OpenClaw cần để chạy (bạn không cần hiểu nó là gì, cứ cài là được).")
t(109, "Lưu ý: OpenClaw yêu cầu Node.js phiên bản >= 22. ")
t(110, "Nếu bạn đã cài phiên bản Node.js cũ trước đó, có thể cần nâng cấp.")
t(111, "Trước tiên kiểm tra máy bạn đã có Node.js chưa:")
t(112, "Xem kết quả:")
t(113, "• ")
t(114, "Nếu hiển thị ")
t(115, "v22.x.x")
t(116, " hoặc phiên bản cao hơn (ví dụ v22.5.0, v24.13.0) → ")
t(117, "Phiên bản đủ rồi, bỏ qua bước này, chuyển thẳng đến \"Mac bước 5\"")
t(118, "• ")
t(119, "Nếu phiên bản hiển thị thấp hơn v22 (ví dụ v18.x.x, v20.x.x) → Cần nâng cấp, tiếp tục xem phía dưới")
t(120, "• ")
t(121, "Nếu hiển thị ")
t(122, "command not found")
t(123, " → Chưa cài, tiếp tục xem phía dưới")
t(124, "Cài đặt (hoặc nâng cấp) Node.js:")
t(125, "Sau khi cài xong, xác nhận:")
t(126, "Thấy ")
t(127, "v22")
t(128, " hoặc số phiên bản cao hơn là đúng rồi.")
t(129, "Nếu brew install node cài ra phiên bản vẫn thấp hơn 22 thì sao?")
t(130, "Thử lệnh này để cài bắt buộc phiên bản mới nhất: ")
# 131 is empty newline
# 132 is "brew install node@22" - code, keep as is
# 133 is " " - whitespace
# 134 is empty newline
t(135, "Sau đó làm theo hướng dẫn trong Terminal để liên kết nó vào đường dẫn hệ thống.")
t(136, "Mac bước 5: Cài đặt OpenClaw bằng một lệnh")
t(137, "Cuối cùng cũng đến lúc cài OpenClaw! Copy paste dòng lệnh sau trong Terminal, nhấn Enter:")
t(138, "Dòng lệnh này làm gì? ")
t(139, "Nó sẽ tải về một script cài đặt từ trang web chính thức của OpenClaw, sau đó tự động thực thi. Script sẽ giúp bạn: ")
# 140 is empty newline
t(141, "1. Tải về các file chương trình OpenClaw, bao gồm Homebrew và Node.js ")
t(142, "(nếu chưa có thì quay lại bước 2 để bắt đầu) ")
# 143 is empty newline
t(144, "2. Cài đặt vào đúng vị trí ")
# 145 is empty newline
t(146, "3. Tự động khởi chạy trình hướng dẫn cấu hình")
t(147, "Toàn bộ quá trình mất khoảng 5-10 phút ")
t(148, ", đợi nó chạy xong là được, đừng đóng cửa sổ Terminal.")
t(149, "Sau khi cài xong, nó sẽ tự động vào trình hướng dẫn cấu hình. → ")
t(150, "Chuyển đến phần ")
t(151, "\"Hướng dẫn cấu hình (dùng chung cho Mac và Windows)\" ")
t(152, "ở phía dưới để tiếp tục.")
t(153, "🪟 Quy trình cài đặt Windows (Người dùng Mac bỏ qua)")
t(154, "Quan trọng: Windows cần cài WSL trước")
t(155, "WSL là gì? ")
t(156, "WSL (Windows Subsystem for Linux) là công cụ chính thức của Microsoft, cho phép bạn chạy hệ thống Linux trên Windows. OpenClaw không thể chạy trực tiếp trên Windows, cần thông qua WSL. Yên tâm, cài WSL rất đơn giản, chỉ một dòng lệnh.")
t(157, "Windows bước 1: Mở PowerShell với quyền quản trị")
t(158, "1 ")
t(159, "Nhấn phím ")
t(160, "Win")
t(161, " (biểu tượng Windows ở góc dưới bên trái bàn phím)")
t(162, "2 ")
t(163, "Tìm kiếm ")
t(164, "PowerShell")
t(165, "3 Click chuột phải vào ")
t(166, "\"Windows PowerShell\"")
t(167, "4 ")
t(168, "Chọn \"")
t(169, "Chạy với quyền quản trị viên ")
t(170, "\"")
t(171, "5 ")
t(172, "Nếu hiện thông báo \"Bạn có muốn cho phép ứng dụng này thay đổi thiết bị không?\", nhấn \"")
t(173, "Có ")
t(174, "\"")
t(175, "6 ")
t(176, "Hiện ra một cửa sổ màu xanh, đó chính là PowerShell")
t(177, "Tại sao phải \"chạy với quyền quản trị\"? ")
t(178, "Vì cài WSL cần sửa cài đặt hệ thống, chỉ có quyền quản trị viên mới làm được.")
t(179, "Windows bước 2: Cài đặt WSL")
t(180, "Nhập dòng lệnh sau trong PowerShell, nhấn Enter:")
t(181, "Những tình huống bạn sẽ gặp trong quá trình cài đặt:")
t(182, "1 ")
t(183, "Hệ thống sẽ tự động tải và cài WSL2 cùng Ubuntu (một hệ thống Linux), ")
t(184, "mất vài phút đến hơn chục phút")
t(185, "2 Sau khi cài xong cần khởi động lại máy tính ")
t(186, "→ Lưu lại những gì bạn đang làm, sau đó khởi động lại")
t(187, "3 ")
t(188, "Sau khi khởi động lại, máy tính có thể tự động mở cửa sổ Ubuntu, yêu cầu bạn thiết lập tên người dùng và mật khẩu")
t(189, "4 Tên người dùng ")
t(190, ": Đặt một tên tiếng Anh bất kỳ (ví dụ ")
t(191, "user")
t(192, " ), không có dấu cách và tiếng Trung")
t(193, "5 Mật khẩu ")
t(194, ": Đặt một mật khẩu bạn có thể nhớ (")
t(195, "khi nhập cũng sẽ không hiển thị ký tự, gõ mù rồi nhấn Enter")
t(196, ")")
t(197, "6 Xác nhận mật khẩu ")
t(198, ": Nhập lại mật khẩu giống như trên")
t(199, "Nếu sau khi khởi động lại không tự động mở cửa sổ Ubuntu: ")
t(200, "Trong menu Start tìm kiếm ")
t(201, "Ubuntu")
t(202, " , click mở, sau đó làm theo hướng dẫn để thiết lập tên người dùng và mật khẩu.")
t(203, "Windows bước 3: Mở Terminal WSL")
t(204, "Từ giờ mỗi lần thao tác OpenClaw đều thực hiện trong Terminal WSL này (không phải PowerShell).")
t(205, "Cách mở:")
t(206, "1 ")
t(207, "Trong menu Start tìm kiếm ")
t(208, "Ubuntu")
t(209, " , click mở")
t(210, "2 ")
t(211, "Hoặc trong PowerShell gõ ")
t(212, "wsl")
t(213, " nhấn Enter")
t(214, "Bạn sẽ thấy một cửa sổ tương tự Terminal Linux, hiển thị dấu nhắc tương tự ")
t(215, "user@tên-máy-tính:~$")
t(216, " .")
t(217, "Làm sao để paste lệnh trong Terminal WSL? ")
t(218, "Sau khi copy lệnh trên trang web, trong cửa sổ Terminal WSL ")
t(219, "click chuột phải ")
t(220, "là paste. Hoặc dùng ")
t(221, "Ctrl + Shift + V")
t(222, " (lưu ý: là Ctrl + Shift + V, không phải Ctrl + V).")
t(223, "Windows bước 4: Cài đặt Node.js")
t(224, "Trong Terminal WSL lần lượt nhập các lệnh sau (từng dòng một, mỗi dòng nhập xong nhấn Enter đợi chạy xong rồi nhập dòng tiếp theo):")
t(225, "Dòng 1: Cập nhật danh sách gói phần mềm hệ thống")
t(226, "Nếu yêu cầu nhập mật khẩu, nhập mật khẩu WSL bạn vừa thiết lập, nhấn Enter.")
t(227, "Dòng 2: Cài công cụ quản lý phiên bản Node.js")
t(228, "Dòng 3: Cài đặt Node.js")
t(229, "Dòng 4: Xác nhận cài đặt")
t(230, "Thấy ")
t(231, "v22.x.x")
t(232, " hoặc số phiên bản cao hơn là cài thành công.")
t(233, "Windows bước 5: Cài đặt OpenClaw bằng một lệnh")
t(234, "Copy paste dòng lệnh sau trong Terminal WSL, nhấn Enter:")
t(235, "Toàn bộ quá trình mất khoảng 2-5 phút ")
t(236, ", đợi nó chạy xong là được, đừng đóng cửa sổ.")
t(237, "Sau khi cài xong, nó sẽ tự động vào trình hướng dẫn cấu hình. → ")
t(238, "Tiếp tục xem phần \"Hướng dẫn cấu hình\" phía dưới.")
t(239, "⚙️ Hướng dẫn cấu hình (dùng chung cho Mac và Windows)")
t(240, "Sau khi cài xong, sẽ tự động vào trình hướng dẫn cấu hình tương tác. Nó sẽ hỏi bạn từng bước, bạn chỉ cần chọn theo hướng dẫn.")
t(241, "Nếu sau khi cài không tự động vào trình hướng dẫn cấu hình ")
t(242, ", nhập lệnh này để khởi chạy thủ công: ")
# 243 is empty newline
t(244, "openclaw onboard --install-daemon")
# 245 is whitespace
# 246 is empty newline
t(247, "( ")
t(248, "--install-daemon")
t(249, " sẽ đăng ký OpenClaw làm dịch vụ hệ thống, tự động khởi động khi bật máy)")
t(250, "Bước 1: Cảnh báo bảo mật")
t(251, "Màn hình đầu tiên sẽ nhắc bạn OpenClaw là phần mềm thử nghiệm, sẽ truy cập file và mạng của bạn, hỏi bạn có hiểu rủi ro không.")
t(252, "Thao tác: ")
t(253, "Dùng phím ")
t(254, "mũi tên trái ← ")
t(255, "chọn ")
t(256, "Yes ")
t(257, ", nhấn Enter để tiếp tục.")
t(258, "Về bảo mật: ")
t(259, "OpenClaw sẽ đọc file trên máy tính của bạn để giúp bạn làm việc, điều này cũng có nghĩa là nó có thể xem file cá nhân của bạn. Khuyến nghị không nên sử dụng trên máy tính có file nhạy cảm (thông tin ngân hàng, tài liệu mật khẩu, v.v.), hoặc chú ý giới hạn phạm vi truy cập khi sử dụng.")
t(260, "Bước 2: Chọn chế độ cài đặt")
t(261, "Sẽ hỏi bạn muốn QuickStart (bắt đầu nhanh) hay cài đặt tùy chỉnh.")
t(262, "Thao tác: ")
t(263, "Chọn ")
t(264, "QuickStart ")
t(265, ", nhấn Enter.")
t(266, "Chọn QuickStart là đúng rồi, nó sẽ thiết lập những thứ cơ bản nhất cho bạn. Khi bạn quen rồi, bất cứ lúc nào cũng có thể dùng ")
t(267, "openclaw onboard")
t(268, " để cấu hình lại.")
t(269, "Bước 3: Chọn nhà cung cấp mô hình AI (Quan trọng!)")
t(270, "Bước này là chọn \"bộ não AI\" dùng của hãng nào. Sẽ liệt kê vài lựa chọn, dùng phím mũi tên lên xuống để chọn, nhấn Enter để xác nhận.")
t(271, "Nhà cung cấp")
t(272, "Mức khuyến nghị")
t(273, "Giải thích")
t(274, "Tham khảo giá")
t(275, "ChatGPT")
t(276, "Ưu tiên")
t(277, "Không bị khóa tài khoản, chỉ cần đăng nhập ủy quyền")
t(278, "Hạn mức miễn phí lớn")
t(279, "Claude ")
t(280, "Lựa chọn dự phòng")
# 281 is empty newline
t(282, "Tính năng đầy đủ nhất, khả năng suy luận mạnh nhất (đừng đăng nhập ủy quyền sẽ bị khóa tài khoản)")
t(283, "Dùng API rất đắt")
t(284, "Gemini")
t(285, "Lựa chọn dự phòng")
t(286, "Hiệu suất/giá tốt, tiếng Trung ổn (đăng nhập ủy quyền cũng bị khóa tài khoản)")
t(287, "Khuyên dùng API")
t(288, "MiniMax")
t(289, "Lựa chọn tiết kiệm")
t(290, "Tiếng Trung mạnh, giá rẻ")
t(291, "Đăng ký tặng hạn mức miễn phí")
t(292, "Kim/Zhipu")
t(293, "Ưu tiên cho người dùng Trung Quốc")
t(294, "Kết nối trực tiếp trong nước, không cần VPN, giá rẻ")
t(295, "Đăng ký tặng hạn mức miễn phí")
t(296, "Ollama (mô hình cục bộ)")
t(297, "Lựa chọn miễn phí (không khuyến nghị)")
t(298, "Hoàn toàn miễn phí, không cần mạng, nhưng cần cấu hình máy tốt")
t(299, "Miễn phí")
t(300, "Gợi ý tiết kiệm: ")
# 301 is empty newline
t(302, "- Nếu bạn chỉ muốn thử → Chọn ")
t(303, "MiniMax ")
t(304, "hoặc ")
t(305, "Kim/Zhipu ")
t(306, ", đăng ký là có hạn mức miễn phí ")
# 307 is empty newline
t(308, "- Nếu bạn ở Trung Quốc, mạng không thuận tiện → Chọn họ là được ")
t(309, ", kết nối trực tiếp trong nước, không cần VPN ")
# 310 is empty newline
t(311, "- Nếu cấu hình máy tính tốt (ít nhất 32GB RAM) → Có thể thử ")
t(312, "Ollama ")
t(313, ", hoàn toàn miễn phí, nhưng cần cài thêm phần mềm Ollama ")
# 314 is empty newline
t(315, "- Nếu bạn muốn hiệu quả tốt nhất → Chọn ")
t(316, "Anthropic (Claude) nhưng cần dùng API")
t(317, "Bước 4: Kết nối mô hình AI (hai cách)")
t(318, "Sau khi chọn nhà cung cấp, bạn cần cho OpenClaw kết nối với dịch vụ AI. Có hai cách:")
t(319, "Cách 1: API Key (khuyến nghị, ổn định hơn)")
t(320, "API Key là một chuỗi ký tự tương tự mật khẩu, dùng để kết nối dịch vụ AI.")
t(321, "Lấy ví dụ Anthropic (Claude), các bước lấy API Key:")
t(322, "1 ")
t(323, "Mở trình duyệt, truy cập https://console.anthropic.com/")
t(324, "2 ")
t(325, "Đăng ký tài khoản (cần email)")
t(326, "3 ")
t(327, "Sau khi đăng nhập, click vào menu bên trái ")
t(328, "API Keys")
t(329, "4 ")
t(330, "Click ")
t(331, "Create Key ")
t(332, "(Tạo khóa)")
t(333, "5 ")
t(334, "Đặt tên cho khóa (gõ bất kỳ, ví dụ ")
t(335, "openclaw")
t(336, " ), click tạo")
t(337, "6 Sao chép chuỗi khóa vừa tạo")
t(338, "⚠️ ")
t(339, "Chuỗi khóa này chỉ hiển thị một lần! ")
t(340, "Nhất định phải sao chép và lưu lại. Nếu quên sao chép, cần xóa và tạo lại.")
t(341, "Nơi lấy API Key của các nhà cung cấp khác:")
t(342, "Nhà cung cấp")
t(343, "Địa chỉ đăng ký")
t(344, "Ghi chú")
t(345, "OpenAI")
t(346, "https://platform.openai.com/api-keys")
t(347, "Cần liên kết thẻ tín dụng")
t(348, "Google Gemini")
t(349, "https://aistudio.google.com/apikey")
t(350, "Có hạn mức miễn phí")
t(351, "MiniMax")
t(352, "https://platform.minimaxi.com/")
t(353, "Đăng ký tặng ¥15 hạn mức")
t(354, "DeepSeek")
t(355, "https://platform.deepseek.com/api_keys")
t(356, "Đăng ký tặng hạn mức, kết nối trực tiếp trong nước")
t(357, "KIMI (Moonshot)")
t(358, "https://platform.moonshot.cn/console/api-keys")
t(359, "Đăng ký tặng ¥15 hạn mức")
t(360, "Nhắc nhở: ")
t(361, "Nhà cung cấp bên thứ ba có thể rẻ hơn, có thể hỏi thêm, hoặc hỏi Tiểu Hỗ! Hehe")
t(362, "Cách 2: Đăng nhập ủy quyền OAuth (tiện hơn, nhưng có rủi ro)")
t(363, "Nếu bạn đã có tài khoản trả phí ChatGPT Plus hoặc Claude Pro ")
t(364, "đăng ký trả phí ")
t(365, ", OpenClaw hỗ trợ đăng nhập trực tiếp bằng tài khoản đăng ký của bạn, không cần mua API riêng.")
t(366, "Cách thao tác: ")
t(367, "Trong trình hướng dẫn cấu hình chọn tùy chọn OAuth tương ứng, nó sẽ tự động mở trình duyệt để bạn đăng nhập tài khoản, hoàn tất ủy quyền sẽ tự động kết nối.")
t(368, "⚠️ ")
t(369, "Cảnh báo quan trọng: Cách OAuth có rủi ro bị khóa tài khoản!")
t(370, "Tháng 2 năm 2026, nhiều người dùng báo cáo rằng sau khi sử dụng tài khoản OAuth Claude Pro/Max và Google để kết nối OpenClaw, ")
t(371, "tài khoản bị khóa ")
t(372, ". Nhiều trang báo như PCWorld, SecurityWeek đã đưa tin về vấn đề này.")
t(373, "Khuyến nghị: ")
t(374, "Dùng API Key độc lập, đừng dùng đăng nhập OAuth từ tài khoản trả phí cá nhân. Nếu nhất định muốn dùng OAuth, hãy dùng một tài khoản không quan trọng.")
t(375, "Bước 5: Chọn mô hình mặc định")
t(376, "Sẽ yêu cầu bạn chọn cụ thể dùng mô hình nào. Màn hình sẽ liệt kê các mô hình khả dụng của nhà cung cấp đó.")
t(377, "Mô hình khuyến nghị:")
t(378, "Nhà cung cấp")
t(379, "Mô hình khuyến nghị")
t(380, "Lý do")
t(381, "Anthropic")
t(382, "Claude Sonnet 4.5")
t(383, "Hiệu suất/giá tốt nhất")
t(384, "OpenAI")
t(385, "GPT-4o")
t(386, "Tốc độ nhanh, hiệu quả tốt")
t(387, "Google")
t(388, "Gemini 2.0 Flash")
t(389, "Nhanh và rẻ")
t(390, "MiniMax")
t(391, "M2.1")
t(392, "Tiếng Trung tốt nhất")
t(393, "DeepSeek")
t(394, "deepseek-chat")
t(395, "Kết nối trực tiếp trong nước, giá rẻ")
t(396, "KIMI")
t(397, "kimi-k2.5")
t(398, "Tiếng Trung tốt, có hạn mức miễn phí")
t(399, "Thao tác: ")
t(400, "Dùng phím mũi tên lên xuống để chọn mô hình, nhấn Enter để xác nhận.")
t(401, "Bước 6: Cấu hình kênh trò chuyện (có thể bỏ qua, sau này nhờ Tôm Hùm giúp)")
t(402, "Bước này quyết định sau này bạn nói chuyện với OpenClaw bằng cách nào. Có thể chọn:")
t(403, "• Telegram ")
t(404, ": Khuyến nghị cho người dùng nước ngoài, thiết lập đơn giản nhất")
t(405, "• WhatsApp ")
t(406, ": Quét mã QR là xong")
t(407, "• Feishu ")
t(408, ": Khuyến nghị cho người dùng Trung Quốc, nhưng cấu hình hơi phức tạp hơn (cần tạo ứng dụng trên nền tảng mở Feishu)")
t(409, "• Bảng điều khiển web ")
t(410, ": Không cần cấu hình thêm, cài xong là dùng được")
t(411, "Thao tác: ")
t(412, "Nếu bạn không chắc, dùng phím mũi tên lên xuống chọn, trước tiên chọn ")
t(413, "Bỏ qua ")
t(414, "(Skip). Bảng điều khiển web là có sẵn mặc định, không cần thiết lập thêm. Khi bạn quen rồi, bất cứ lúc nào cũng có thể dùng ")
t(415, "openclaw onboard")
t(416, " để cấu hình lại.")
t(417, "Bước 7: Kỹ năng (Skills) và các cấu hình khác")
t(418, "Sẽ hỏi bạn có muốn bật một số kỹ năng cài sẵn không (như duyệt web, quản lý file, quản lý lịch trình, v.v.).")
t(419, "Thao tác: ")
t(420, "Chọn ")
t(421, "Yes ")
t(422, "bật tất cả. Sau này không dùng đến thì tắt bất cứ lúc nào. Cũng có thể chọn bỏ qua, sau này cài qua trò chuyện, ")
t(423, "tôi khuyên nên bỏ qua》")
t(424, "Enter + Space rồi chọn bỏ qua")
t(425, "Sau đó tất cả phần tiếp theo trước tiên chọn ")
t(426, "NO")
t(427, "Bước này cũng chọn bỏ qua, đây là nơi thiết lập tính cách, bộ nhớ và cấu hình của Tôm Hùm, sau này chúng ta cũng thiết lập qua trò chuyện, tiện hơn.")
t(428, "Bước 8: Cài đặt hoàn tất!")
t(429, "Thấy thông báo tương tự ")
t(430, "\"OpenClaw is ready!\" ")
t(431, "hoặc ")
t(432, "\"Your AI assistant is now running\" ")
t(433, "thì có nghĩa là cài đặt và cấu hình đã hoàn tất!")
t(434, "Nó có thể hỏi bạn có muốn mở bảng điều khiển web (Web UI) không, chọn ")
t(435, "\"Open the web UI\" ")
t(436, "sẽ tự động mở trong trình duyệt.")
t(437, "Nhưng tôi khuyên chọn trò chuyện trong Terminal, vì sau này bạn sẽ dần quen với cách thao tác này, sẽ rất có ích cho bạn.")
t(438, "Vậy là quá trình cài đặt đã hoàn tất.")
t(439, "Cuối cùng bạn sẽ thấy màn hình như thế này ↓")
t(440, "Bạn đã có thể trò chuyện với nó rồi!")
t(441, "Xác nhận cài đặt thành công")
t(442, "Cài xong rồi, chúng ta hãy xác nhận mọi thứ hoạt động bình thường.")
t(443, "Kiểm tra trạng thái hoạt động")
t(444, "Nhập trong Terminal:")
t(445, "Nếu thấy hiển thị ")
t(446, "Running ")
t(447, "(đang chạy), là đúng rồi.")
t(448, "Nếu hiển thị không chạy ")
t(449, ", nhập ")
t(450, "openclaw gateway start")
t(451, " để khởi động.")
t(452, "Mở bảng điều khiển web")
t(453, "Nhập trong Terminal:")
t(454, "Hoặc nhập trực tiếp trong thanh địa chỉ trình duyệt:")
t(455, "127.0.0.1 là gì? ")
t(456, "Đây là một địa chỉ web đặc biệt, nghĩa là \"chính máy tính của bạn\". Vì OpenClaw được cài trên máy tính của bạn, nên truy cập qua địa chỉ này. 18789 là số cổng mà OpenClaw sử dụng.")
t(457, "Nếu thấy bảng điều khiển web của OpenClaw, chúc mừng bạn, cài đặt thành công!")
t(458, "Gửi một tin nhắn thử nghiệm")
t(459, "Trong hộp chat của bảng điều khiển, gửi thử một tin nhắn, ví dụ nhập:")
t(460, "Nếu nhận được phản hồi bình thường, nghĩa là bộ não AI đã kết nối thành công!")
t(461, "Kiểm tra sức khỏe (tùy chọn)")
t(462, "Nếu bạn muốn kiểm tra toàn diện hơn xem có vấn đề gì không, nhập:")
t(463, "Nó sẽ tự động kiểm tra các cấu hình có bình thường không, nếu có vấn đề sẽ đưa ra gợi ý sửa chữa.")
t(464, "Tất nhiên đây chỉ là cài đặt thành công, sau này còn nhiều cấu hình cần thực hiện. Bài hướng dẫn này có thể không viết chi tiết hết được, tôi sẽ tiếp tục viết các hướng dẫn chi tiết từng bước, hãy đón chờ nhé.")
t(465, "Dưới đây là một số thiết lập cấu hình cơ bản, cài đặt kỹ năng, v.v.")
t(466, "Bạn có thể xem thử!")
t(467, "Điểm khác biệt lớn nhất giữa Tôm Hùm và GPT là bạn có thể nhờ nó cài đặt và thao tác mọi thứ, không chỉ là trả lời câu hỏi.")
t(468, "Nhưng lưu ý mọi thao tác đều cần cẩn thận, nếu không nó sẽ xóa lung tung, lệnh của bạn nhất định phải rõ ràng, đừng quá mơ hồ.")
t(469, "Tất nhiên bạn cũng có thể chọn cài trên đám mây, ví dụ trong Coze ↓")
t(470, "Tết Nguyên Đán này chắc chắn thuộc về ByteDance: Sau Seedance 2.0, Doubao Seed 2.0 cũng ra mắt - Đánh giá chi tiết")
t(471, "Hẹn gặp lại!")
t(472, "Bảng tra cứu lệnh thường dùng")
t(473, "Sau khi cài xong, những lệnh sau bạn có thể sẽ dùng đến, đều nhập trong Terminal:")
t(474, "Lệnh")
t(475, "Tác dụng")
t(476, "Khi nào dùng")
t(477, "openclaw gateway start")
t(478, "Khởi động OpenClaw")
t(479, "Khi OpenClaw không tự khởi động sau khi khởi động lại máy")
t(480, "openclaw gateway stop")
t(481, "Dừng OpenClaw")
t(482, "Khi không dùng nữa muốn tắt")
t(483, "openclaw gateway restart")
t(484, "Khởi động lại OpenClaw")
t(485, "Sau khi thay đổi cấu hình")
t(486, "openclaw status")
t(487, "Xem trạng thái hoạt động")
t(488, "Khi muốn xem nó có đang chạy không")
t(489, "openclaw dashboard")
t(490, "Mở bảng điều khiển web")
t(491, "Khi muốn dùng web để trò chuyện")
t(492, "openclaw doctor")
t(493, "Tự động kiểm tra vấn đề cấu hình")
t(494, "Khi gặp sự cố không biết nguyên nhân")
t(495, "openclaw update")
t(496, "Cập nhật lên phiên bản mới nhất")
t(497, "Khi muốn trải nghiệm tính năng mới")
t(498, "openclaw onboard")
t(499, "Chạy lại trình hướng dẫn cấu hình")
t(500, "Khi muốn đổi mô hình AI hoặc cấu hình lại")
t(501, "openclaw logs")
t(502, "Xem nhật ký hoạt động")
t(503, "Khi gặp sự cố muốn xem thông báo lỗi chi tiết")
t(504, "Mẹo nhỏ: ")
t(505, "Nếu khi cài đặt bạn đã thêm ")
t(506, "--install-daemon")
t(507, " , OpenClaw sẽ tự khởi động khi bật máy, bạn không cần mỗi lần phải nhập ")
t(508, "openclaw gateway start")
t(509, " .")
t(510, "Nếu không, lần sau mở Terminal, nhập: openclaw tui là được")
t(511, "Khắc phục sự cố thường gặp")
t(512, "❓ Sau khi nhập ")
t(513, "openclaw")
t(514, " hiện thông báo \"command not found\"")
t(515, "Nguyên nhân: ")
t(516, "Terminal không tìm thấy chương trình OpenClaw, thường là biến môi trường chưa được cấu hình.")
t(517, "Cách giải quyết:")
t(518, "1 Trước tiên thử đóng Terminal, mở lại ")
t(519, ", rồi nhập ")
t(520, "openclaw status")
t(521, "2 ")
t(522, "Nếu vẫn không được, có thể đường dẫn toàn cục npm chưa cấu hình. Nhập lệnh sau: ")
t(523, "npm config get prefix")
# 524 is whitespace
# look at output path. Then add to PATH:
t(525, "echo 'export PATH=$(npm config get prefix)/bin:$PATH' >> ~/.zshrc source ~/.zshrc")
t(526, "3 ")
t(527, "Nếu tất cả đều không được, ")
t(528, "chạy lại lệnh cài đặt")
t(529, "❓ Không mở được bảng điều khiển web")
t(530, "1 ")
t(531, "Trước tiên xác nhận OpenClaw đang chạy: ")
t(532, "openclaw status")
t(533, "2 ")
t(534, "Nếu không chạy: ")
t(535, "openclaw gateway start")
t(536, "3 ")
t(537, "Thử truy cập lại http://127.0.0.1:18789/")
t(538, "4 ")
t(539, "Nếu cổng bị chương trình khác chiếm, có thể đổi cổng: ")
t(540, "openclaw gateway --port 18790")
# 541 is whitespace
t(542, "Sau đó truy cập http://127.0.0.1:18790/")
t(543, "❓ AI không phản hồi tin nhắn")
t(544, "1 Kiểm tra API Key có đúng không: ")
t(545, "Chạy ")
t(546, "openclaw doctor")
t(547, " , nó sẽ cho bạn biết đâu có vấn đề")
t(548, "2 Kiểm tra tài khoản API còn số dư không: ")
t(549, "Truy cập trang web của nhà cung cấp tương ứng để kiểm tra")
t(550, "3 Kiểm tra mạng: ")
t(551, "Nếu bạn dùng dịch vụ AI nước ngoài (như Claude, GPT), cần đảm bảo mạng có thể truy cập các dịch vụ này")
t(552, "4 Kiểm tra tên mô hình: ")
t(553, "Đảm bảo tên mô hình trong file cấu hình khớp với nhà cung cấp (ví dụ tên mô hình DeepSeek phải là ")
t(554, "deepseek-chat")
t(555, " )")
t(556, "❓ Cài đặt Homebrew thất bại trên Mac")
t(557, "Nguyên nhân có thể: ")
t(558, "Vấn đề mạng, tải về bị hết thời gian.")
t(559, "Cách giải quyết: ")
t(560, "Đổi sang nguồn mirror trong nước để cài:")
t(561, "Đây là script cài đặt Homebrew do người dùng Trung Quốc đại lục duy trì, tốc độ tải nhanh hơn nhiều.")
t(562, "❓ Cài đặt Node.js thất bại hoặc phiên bản quá thấp")
t(563, "Cách giải quyết 1: ")
t(564, "Tải trực tiếp gói cài đặt từ trang web chính thức: ")
# next few are list items with URLs - keep URLs
t(565, "- Người dùng Mac tải ")
t(566, ".pkg")
t(567, " gói cài đặt, nhấp đúp để cài ")
# 568
t(568, "- Cài xong đóng Terminal mở lại, rồi nhập ")
t(569, "node --version")
t(570, " để kiểm tra")
t(571, "Cách giải quyết 2 (Mac): ")
t(572, "Dùng công cụ quản lý phiên bản npm để nâng cấp:")
t(573, "❓ Cài đặt WSL thất bại trên Windows")
t(574, "1 Đảm bảo phiên bản Windows đủ mới: ")
t(575, "WSL2 cần Windows 10 phiên bản 2004 trở lên, hoặc Windows 11")
t(576, "2 Kiểm tra ảo hóa đã bật chưa: ")
t(577, "Mở Task Manager → Performance → CPU, xem \"Virtualization\" có hiển thị \"Enabled\" không. Nếu không, cần bật trong BIOS (cách cụ thể tùy theo thương hiệu máy tính, có thể tìm kiếm \"thương hiệu máy tính + bật ảo hóa\")")
t(578, "3 Nếu thông báo cần cập nhật nhân WSL:")
# 579 is empty newline
t(580, "wsl --update")
t(581, "❓ Muốn cấu hình lại")
t(582, "Nếu trước đó cấu hình chọn sai, không cần cài lại, chỉ cần chạy:")
t(583, "Sẽ vào lại trình hướng dẫn cấu hình, chọn lại mô hình AI, nhập lại khóa API, v.v.")
t(584, "❓ Muốn gỡ cài đặt hoàn toàn và cài lại")
t(585, "Sau đó bắt đầu lại từ lệnh cài đặt.")
t(586, "Sau khi cài xong có thể làm gì?")
t(587, "Cài xong OpenClaw chỉ là bước đầu. Sức mạnh thực sự của nó nằm ở việc bạn có thể cài \"kỹ năng\" cho nó, để nó biết làm nhiều việc hơn:")
t(588, "• Quản lý email: ")
t(589, "\"Giúp tôi xem email chưa đọc hôm nay, email quan trọng thì tóm tắt lại\"")
t(590, "• Quản lý lịch trình: ")
t(591, "\"Nhắc tôi họp lúc 3 giờ chiều ngày mai\"")
t(592, "• Thu thập web: ")
t(593, "\"Giúp tôi kiểm tra giá mới nhất của sản phẩm XXX\"")
t(594, "• Sắp xếp file: ")
t(595, "\"Phân loại ảnh trong thư mục tải xuống theo ngày\"")
t(596, "• Hỗ trợ viết: ")
t(597, "\"Giúp tôi soạn email phản hồi khách hàng\"")
t(598, "Nhiều kỹ năng hơn có thể duyệt và cài đặt trên ClawHub (https://clawhub.ai/). Hiện tại ClawHub đã có hơn 13.000 kỹ năng cộng đồng, nhưng mới bắt đầu đừng tham nhiều, ")
t(599, "cài vài cái thực dụng nhất là đủ ")
t(600, ".")
t(601, "Người mới nên cài (cài xong dùng được ngay)")
t(602, "Cách cài rất đơn giản, trong hộp chat nói với OpenClaw \"cài kỹ năng xxx\" là xong.")
t(603, "Kỹ năng")
t(604, "Dùng để làm gì")
t(605, "Lý do nên cài")
t(606, "Tavily Search")
t(607, "Tìm kiếm tin tức mới nhất trên mạng")
t(608, "Cho AI khả năng tra thông tin thời gian thực, không chỉ dựa vào dữ liệu huấn luyện. Không cần cấu hình, cài là dùng")
t(609, "Summarize")
t(610, "Nén bài viết dài/email dài thành tóm tắt")
t(611, "Mỗi ngày đọc tin tức tiết kiệm một nửa thời gian, người làm tri thức nhất định phải có")
t(612, "Firecrawl")
t(613, "Thu thập nội dung web, trích xuất nội dung chính")
t(614, "Cho AI một link, nó có thể đọc hiểu toàn bộ trang web và tóm tắt")
t(615, "Obsidian")
t(616, "Tự động sắp xếp thư viện ghi chú Obsidian")
t(617, "Ai dùng Obsidian ghi chú thì phải cài")
t(618, "Ngày đầu chỉ cài bốn cái này là đủ ")
t(619, ", dùng quen rồi hãy thêm.")
t(620, "Khuyến nghị cho người dùng Trung Quốc")
t(621, "Kỹ năng")
t(622, "Dùng để làm gì")
t(623, "Giải thích")
t(624, "openclaw-china")
t(625, "Kết nối một chạm với Feishu, DingTalk, WeCom, QQ")
t(626, "Trọn bộ nền tảng chat trong nước, không cần cấu hình từng cái. Tìm trên GitHub: ")
t(627, "BytePioneer-AI/openclaw-china")
t(628, "12306")
t(629, "Tra vé tàu, chuyến tàu, vé còn lại")
t(630, "Nói với AI \"giúp tôi tra tàu cao tốc ngày mai từ Bắc Kinh đi Thượng Hải\", kết quả hiện ngay")
t(631, "A-Share")
t(632, "Tra giá cổ phiếu A-Share thời gian thực")
t(633, "Ai chơi chứng khoán có thể nhờ AI giúp theo dõi, phân tích")
t(634, "Nhắc nhở: ")
t(635, "Nếu bạn chủ yếu dùng Feishu hoặc DingTalk để trò chuyện với AI, ")
t(636, "openclaw-china")
t(637, " kỹ năng này có thể tiết kiệm nhiều bước cấu hình. Feishu từ OpenClaw 2026.2.2 đã là kênh được hỗ trợ chính thức, ổn định nhất.")
t(638, "Khuyến nghị nâng cao (chơi quen rồi hãy cài)")
t(639, "Kỹ năng")
t(640, "Dùng để làm gì")
t(641, "Phù hợp với ai")
t(642, "GOG (Google Workspace)")
t(643, "Một kỹ năng kết nối Gmail, Calendar, Drive, Sheets")
t(644, "Người dùng nước ngoài dùng bộ Google")
t(645, "GitHub")
t(646, "Quản lý code repository, PR, Issue")
t(647, "Ai đang học lập trình hoặc làm dự án mã nguồn mở")
t(648, "n8n")
t(649, "Kết nối các ứng dụng khác nhau tạo quy trình tự động")
t(650, "Người chơi nâng cao muốn nối nhiều công cụ thành dây chuyền tự động")
t(651, "Browser")
t(652, "Điều khiển trình duyệt tự động thao tác trang web")
t(653, "Các tình huống cần tự động điền form, tự động mua vé, v.v.")
t(654, "Nhưng nếu bạn chỉ cài xong rồi dùng, nó chỉ là một chatbot AI bình thường - không khác gì ChatGPT. Điều thực sự làm OpenClaw khác biệt là ")
t(655, "hệ thống cấu hình nhân vật ")
t(656, "của nó.")
t(657, "Nâng cao: Tạo linh hồn cho trợ lý AI của bạn")
t(658, "Thư mục làm việc của OpenClaw (mặc định ở ")
t(659, "~/clawd/")
t(660, " ) có một bộ file ")
t(661, ".md")
t(662, " , chúng giống như \"hồ sơ tính cách\" của AI. Mỗi khi AI \"tỉnh dậy\", việc đầu tiên là đọc các file này để biết mình là ai, đang giúp ai, nên làm gì.")
t(663, "Bạn không cần cấu hình hết một lúc, ")
t(664, "bắt đầu từ SOUL.md và USER.md là đủ ")
t(665, ", cái khác dùng đến khi nào thêm khi đó.")
t(666, "SOUL.md: Nó là ai")
t(667, "Đây là file quan trọng nhất, quyết định ")
t(668, "tính cách, cách nói chuyện và quy tắc hành vi ")
t(669, "của trợ lý AI.")
t(670, "Mở Terminal, tạo file này:")
t(671, "Viết gì vào đó? Lấy ví dụ:")
t(672, "Viết xong nhấn ")
t(673, "Ctrl + X")
t(674, " , sau đó nhấn ")
t(675, "Y")
t(676, " để lưu, nhấn Enter để thoát.")
t(677, "Trọng điểm: ")
t(678, "File này bạn có thể sửa bất cứ lúc nào. Dùng vài ngày thấy nó nói nhiều quá? Sửa. Thấy nó không đủ chủ động? Sửa. Nó sẽ làm theo bản mới nhất bạn viết.")
t(679, "IDENTITY.md: Nó tên gì")
t(680, "Đơn giản hơn SOUL.md, chỉ là cho AI một \"danh thiếp\":")
t(681, "Tên đặt tùy ý, gọi là \"Jarvis\", \"Friday\", \"Tiểu Ái\" đều được.")
t(682, "USER.md: Bạn là ai")
t(683, "File này là để cho AI biết \"bạn đang giúp ai\", để nó hiểu thói quen và sở thích của bạn:")
t(684, "Viết xong file này, AI sẽ không mỗi lần hỏi \"Xin chào, tôi có thể giúp gì cho bạn?\", mà trực tiếp vào trạng thái, biết bạn là ai, bạn đang làm gì.")
t(685, "AGENTS.md: Quy tắc làm việc")
t(686, "File này định nghĩa ")
t(687, "quy trình làm việc và quy tắc ")
t(688, "của AI, ví dụ:")
t(689, "• ")
t(690, "Mỗi khi \"tỉnh dậy\" đọc file nào trước")
t(691, "• ")
t(692, "Thao tác nào có thể tự làm, thao tác nào phải hỏi bạn trước")
t(693, "• ")
t(694, "Trong nhóm chat nên ứng xử thế nào (đừng trả lời hết, như người bình thường)")
t(695, "• ")
t(696, "Cách quản lý file bộ nhớ")
t(697, "Bạn có thể viết đơn giản, cũng có thể viết rất chi tiết. OpenClaw khi cài sẽ tự tạo phiên bản mặc định, sau này từ từ sửa theo nhu cầu của mình.")
t(698, "HEARTBEAT.md: Tuần tra định kỳ")
t(699, "File này cho AI ")
t(700, "chủ động giúp bạn làm việc ")
t(701, ", thay vì đợi bạn gửi tin nhắn mới hành động.")
t(702, "Kết hợp với cơ chế heartbeat của OpenClaw (mặc định mỗi 30 phút thực thi một lần), nó sẽ như một trợ lý tận tâm, định kỳ kiểm tra, có việc mới gọi bạn.")
t(703, "MEMORY.md: Bộ nhớ dài hạn")
t(704, "Mỗi khi AI khởi động đều \"mất trí nhớ\", nhưng MEMORY.md giúp nó nhớ những việc quan trọng:")
t(705, "• ")
t(706, "Những quyết định quan trọng bạn đã đưa ra")
t(707, "• ")
t(708, "Sở thích và thói quen của bạn")
t(709, "• ")
t(710, "Những lỗi đã gặp trước đó")
t(711, "Nó sẽ tự động duy trì file này - trích xuất nội dung đáng nhớ từ nhật ký hội thoại hàng ngày ( ")
t(712, "memory/YYYY-MM-DD.md")
t(713, " ) vào đây, giống như một người chỉnh lý nhật ký, cập nhật nhận thức của mình.")
t(714, "Sáu file trong một bảng")
t(715, "File")
t(716, "Giải thích một câu")
t(717, "Bắt buộc không")
t(718, "SOUL.md")
t(719, "Tính cách và quy tắc hành vi của AI")
t(720, "Rất khuyến nghị")
t(721, "IDENTITY.md")
t(722, "Tên và danh tính của AI")
t(723, "Khuyến nghị")
t(724, "USER.md")
t(725, "Thông tin cá nhân và sở thích của bạn")
t(726, "Rất khuyến nghị")
t(727, "AGENTS.md")
t(728, "Quy trình làm việc và quy tắc an toàn")
t(729, "Tùy chọn (có giá trị mặc định)")
t(730, "HEARTBEAT.md")
t(731, "Nhiệm vụ tự động thực thi định kỳ")
t(732, "Tùy chọn")
t(733, "MEMORY.md")
t(734, "Bộ nhớ dài hạn của AI")
t(735, "Tự động tạo")
t(736, "Cấu hình tối thiểu: ")
t(737, "Chỉ viết SOUL.md + USER.md, mất 5 phút, trợ lý AI của bạn sẽ từ \"chatbot đa năng\" trở thành \"trợ lý cá nhân hiểu bạn\".")
t(738, "Tiểu Hỗ nói: ")
t(739, "OpenClaw là dự án thú vị nhất trong số các công cụ AI mã nguồn mở mà tôi đang theo dõi gần đây. Điểm khác biệt lớn nhất so với ChatGPT là: ChatGPT là bạn đến tìm nó trò chuyện, còn OpenClaw giống như một trợ lý trực tuyến 24 giờ, bạn chỉ cần @nó trong ứng dụng chat bất cứ lúc nào, nó còn có thể chủ động giúp bạn làm việc.")
t(740, "Quá trình cài đặt nhìn dài, nhưng thực ra chỉ có mấy bước: ")
t(741, "Cài môi trường (Homebrew + Node.js) → Một lệnh cài OpenClaw → Làm theo hướng dẫn cấu hình ")
t(742, ".")
t(743, "Nếu bạn bị kẹt ở đâu, hãy comment cho tôi biết, tôi sẽ giúp bạn xem.")
t(744, "Tham khảo thêm: ")
# 745 is empty newline
t(746, "- Tài liệu chính thức OpenClaw |")
t(747, "https://docs.openclaw.ai/install ")
t(748, "____________")
t(749, "End.")
t(750, "Cảm ơn đã đọc")
t(751, "Like, chia sẻ, theo dõi ↓↓")

# Now apply translations to the JSON
idx = 0
translated_count = 0
kept_count = 0
total_text = 0

for block in data['blocks']:
    for el in block['elements']:
        if el['type'] == 'text_run':
            total_text += 1
            if idx in CN_TO_VI:
                el['content'] = CN_TO_VI[idx]
                translated_count += 1
            else:
                kept_count += 1
            idx += 1
        # Other element types (mention_user, etc.) are not counted in idx

print(f"Total text_run elements: {total_text}")
print(f"Translated: {translated_count}")
print(f"Kept as-is: {kept_count}")

with open('_art30_trans.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved _art30_trans.json")
