# -*- coding: utf-8 -*-
"""Second pass: fix ALL remaining Chinese in art23_trans.json"""
import json, sys, re

sys.stdout.reconfigure(encoding='utf-8')

# Comprehensive Chinese word/phrase -> Vietnamese dictionary
# Sorted by length (longer first) to avoid partial matches
vocab = {
    # Common words appearing in meeting note titles
    "磁盘整理": "Dọn dẹp ổ đĩa",
    "资料搜集": "Thu thập tài liệu",
    "学习助手": "Trợ lý học tập",
    "三大办公场景实测": "thử nghiệm thực tế ba kịch bản văn phòng",
    "发起人": "Người khởi xướng",
    "硅谷最火": "hot nhất Silicon Valley",
    "方向": "hướng đi",
    "到赚钱": "đến kiếm tiền",
    "的完整路径": "con đường hoàn chỉnh",
    "全自动剪片流程": "Quy trình cắt phim tự động hoàn toàn",
    "从脚本": "từ kịch bản",
    "成片一步到位": "thành phẩm một bước",
    "爆款视频一键复刻，一只虾就是一个剪辑团队": "Nhân bản video hot một nút, một con tôm là cả một đội cắt ghép",
    "自媒体": "tự truyền thông",
    "老师": "Thầy",
    "文心": "Wenxin",
    "千帆": "Qianfan",
    "零门槛玩转": "chơi không rào cản",
    "开发": "phát triển",
    "手把手部署指南": "Hướng dẫn triển khai chi tiết",
    "打造一个真正的": "tạo một trợ lý AI thực sự",
    "打造一个真正": "tạo một trợ lý thực sự",
    "时代下": "thời đại",
    "如何快速开发": "cách phát triển nhanh",
    "游戏": "game",
    "小时极限开发实战复盘": "giờ phân tích lại thực chiến phát triển cực hạn",
    "后全流程游戏制作人": "nhà sản xuất game toàn quy trình",
    "手把手": "hướng dẫn chi tiết",
    "玩转开源版": "chơi phiên bản mã nguồn mở",
    "来新璐": "Tân Lộ",
    "开源版": "phiên bản mã nguồn mở",
    "开发者": "nhà phát triển",
    "深度解析": "Phân tích chuyên sâu",
    "原理": "nguyên lý",
    "机制设计": "thiết kế cơ chế",
    "以及教你从": "và dạy bạn từ",
    "到": "đến",
    "手搓一个迷你": "tự tay làm một mini",
    "分享人": "Người chia sẻ",
    "深度实测": "thử nghiệm chuyên sâu",
    "原生工作台如何解放双手": "bàn làm việc gốc giải phóng đôi tay như thế nào",
    "寻鹭": "Tầm Lộ",
    "负责人": "người phụ trách",
    "爆改训练营": "Training camp cải tạo đột phá",
    "两日连播": "phát liên tục hai ngày",
    "到底更新了什么": "cuối cùng đã cập nhật gì",
    "嘉宾": "Khách mời",
    "罗文": "La Văn",
    "二师兄": "Nhị Sư Huynh",
    "职场": "Nơi công sở",
    "就用扣子": "dùng Coze",
    "新功能": "tính năng mới",
    "上线": "ra mắt",
    "对话": "Đối thoại",
    "闪电说": "Sấm Điện Thuyết",
    "出海的实战指南": "chiến lược thực chiến ra nước ngoài",
    "龚震": "Cung Chấn",
    "闪电说联合": "Sấm Điện Thuyết đồng",
    "增长": "tăng trưởng",
    "商业化负责人": "người phụ trách thương mại hóa",
    "余猛": "Dư Mãnh",
    "姚全刚": "Diêu Toàn Cương",
    "尼克西": "Nikxi",
    "元子": "Nguyên Tử",
    "全球首个实时生成世界模型正式上线": "Mô hình thế giới tạo sinh thời gian thực đầu tiên toàn cầu chính thức ra mắt",
    "不只是": "không chỉ là",
    "而是": "mà còn là",
    "谭少卿": "Đàm Thiếu Khanh",
    "李俊": "Lý Tuấn",
    "增长负责人": "người phụ trách tăng trưởng",
    "开年重磅": "Sự kiện lớn đầu năm",
    "海辛": "Hải Tân",
    "阿文": "A Văn",
    "工作流分享": "chia sẻ workflow",
    "下午": "chiều",
    "情报速递，深度解读具身智能与无人驾驶两大赛道": "tin tức nóng, phân tích chuyên sâu hai đường đua trí tuệ thân thể và lái xe tự động",
    "王玮滢": "Vương Vĩ Doanh",
    "哈佛大学计算机博士": "Tiến sĩ Khoa học Máy tính Harvard",
    "具身智能研究科学家": "Nhà khoa học nghiên cứu trí tuệ thân thể",
    "连续创业者": "Nhà khởi nghiệp liên tục",
    "让创意变生意": "Biến sáng tạo thành kinh doanh",
    "应用变现第五期": "Kiếm tiền từ ứng dụng kỳ 5",
    "应用变现教学系列第一期来啦": "Kiếm tiền từ ứng dụng loạt dạy học kỳ 1 đây rồi",
    "应用变现教学讲解系列第一期来啦": "Kiếm tiền từ ứng dụng loạt giảng dạy kỳ 1 đây rồi",
    "应用变现教学系列第二期火爆来袭": "Kiếm tiền từ ứng dụng loạt dạy học kỳ 2 bùng nổ",
    "应用变现教学系列第三期来咯": "Kiếm tiền từ ứng dụng loạt dạy học kỳ 3 đây",
    "应用变现第四期超重磅登场": "Kiếm tiền từ ứng dụng kỳ 4 siêu nặng ký ra mắt",
    "开放麦圆桌会": "Bàn tròn micro mở",
    "揭秘": "Giải mã",
    "平台流量密码": "mật mã lưu lượng nền tảng",
    "周如何快速涨粉": "tuần cách tăng fan nhanh",
    "万": "vạn",
    "分享爆款提示词技巧": "chia sẻ mẹo prompt hot",
    "带你避开同质化": "dẫn bạn tránh đồng chất hóa",
    "今晚": "Tối nay",
    "短剧训练营": "Training camp phim ngắn",
    "加餐课": "bài học bổ sung",
    "视频工具实操技巧速学": "học nhanh mẹo thực hành công cụ video",
    "大鹏": "Đại Bằng",
    "数字艺术设计高级工程师": "Kỹ sư cao cấp thiết kế nghệ thuật số",
    "动画师": "Họa sĩ hoạt hình",
    "腾讯": "Tencent",
    "数字守艺人": "Người giữ nghệ thuật số",
    "实操课：批量出片": "Bài thực hành: Xuất phim hàng loạt",
    "动态分层全拿捏": "phân tầng động nắm vững hết",
    "周鹏": "Chu Bằng",
    "广告": "quảng cáo",
    "短剧": "phim ngắn",
    "动画导演": "đạo diễn hoạt hình",
    "万粉": "vạn fan",
    "解锁": "Mở khóa",
    "影视广告创作新玩法": "cách chơi mới sáng tạo quảng cáo điện ảnh",
    "丁一": "Đinh Nhất",
    "广告片": "Phim quảng cáo",
    "纪录片导演": "đạo diễn phim tài liệu",
    "艺术家": "Nghệ sĩ",
    "专为视频创作设计的": "được thiết kế chuyên cho sáng tạo video",
    "智能助手": "trợ lý thông minh",
    "今晚教你如何聊出一个好视频": "tối nay dạy bạn cách chat ra một video tốt",
    "深挖近两年": "đào sâu hai năm gần đây",
    "进化真相": "sự thật tiến hóa",
    "解锁常用": "mở khóa thường dùng",
    "工具清单": "danh sách công cụ",
    "千问": "Qianwen",
    "全新": "hoàn toàn mới",
    "小剧场": "Nhà hát nhỏ",
    "功能": "tính năng",
    "体验": "trải nghiệm",
    "同款玩法": "cùng cách chơi",
    "又双叒叕上新啦": "lại ra mắt mới rồi",
    "进阶教程": "Hướng dẫn nâng cao",
    "等工具": "và các công cụ khác",
    "安装配置全攻略": "Toàn bộ chiến lược cài đặt cấu hình",
    "的": " ",
    "和背后的故事，在社区里成长起来的": "và câu chuyện đằng sau, dự án",
    "项目": "dự án",
    "调香": "pha chế nước hoa",
    "从家庭主妇到": "Từ bà nội trợ đến",
    "公司": "công ty",
    "普通人真的可以逆袭吗": "Người bình thường thực sự có thể ngược dòng không",
    "每周四秒哒时间": "Thời gian Miaoda mỗi thứ Năm",
    "正式开启公测": "chính thức mở public beta",
    "限量邀请码发放": "Phát mã mời giới hạn",
    "小白版扣子": "Phiên bản Coze dành cho người mới",
    "自动化工作流，多场景方案直接复刻": "workflow tự động hóa, nhân bản trực tiếp phương án đa kịch bản",
    "如何用": "Cách dùng",
    "做": "làm",
    "形象": "hình ảnh nhân vật",
    "开营第": "Khai giảng bài ",
    "课": "",
    "短剧行业现状与爆款观片": "Hiện trạng ngành phim ngắn và xem phim hot",
    "主讲": "Giảng viên chính",
    "夜游榊": "Dạ Du Thần",
    "先看清这个行业在": "Trước tiên hãy hiểu rõ ngành này đang",
    "赚谁的钱": "kiếm tiền từ ai",
    "再决定你要不要进来": "rồi quyết định bạn có muốn tham gia không",
    "教育": "giáo dục",
    "少儿": "Thiếu nhi",
    "春晚": "Gala Tết",
    "绘本共学屋，孩子们的创意海报": "Nhà đọc sách tranh cùng nhau, poster sáng tạo của trẻ em",
    "音乐零基础入门之": "Nhập môn âm nhạc từ số 0 với",
    "实操": "thực hành",
    "百度": "Baidu",
    "数字角色选秀大赛创作指南": "Hướng dẫn sáng tạo cuộc thi tuyển chọn nhân vật số",
    "华腾杯全国": "Giải Hoa Đằng toàn quốc",
    "作品创新大奖赛全国金奖": "Giải vàng toàn quốc cuộc thi đổi mới tác phẩm",
    "社区": "cộng đồng",
    "插件召集令插件开发大赛冲刺倒计时": "Lệnh triệu tập plugin cuộc thi phát triển plugin đếm ngược nước rút",
    "天": "ngày",
    "百宝箱": "Hộp Bách Bảo",
    "通义灵码": "Tongyi Lingma",
    "分享": "chia sẻ",
    "吴昞": "Ngô Bỉnh",
    "国际知名房地产咨询外企高级财务经理": "Quản lý tài chính cao cấp doanh nghiệp nước ngoài tư vấn bất động sản quốc tế nổi tiếng",
    "赛事先锋官": "Quan tiên phong giải đấu",
    "孔立刚": "Khổng Lập Cương",
    "世界五百强": "Fortune 500",
    "乐华娱乐": "Nhạc Hoa Entertainment",
    "数字角色选秀大赛正式启动": "Cuộc thi tuyển chọn nhân vật số chính thức khởi động",
    "专为优质内容而生的": "được sinh ra cho nội dung chất lượng",
    "众测": "crowdtest",
    "插件召集令插件开发大赛攻略来袭": "Lệnh triệu tập plugin chiến lược cuộc thi phát triển plugin đến rồi",
    "奖金池丰富": "Giải thưởng phong phú",
    "解锁": "mở khóa",
    "巨额现金激励": "khuyến khích tiền mặt lớn",
    "保姆式教学": "dạy học kiểu bảo mẫu",
    "全流程系统讲解，直击痛点问题": "giảng giải hệ thống toàn quy trình, trực tiếp đánh vào vấn đề đau",
    "不写一行代码": "Không viết một dòng code",
    "基于": "dựa trên",
    "进阶冲刺": "Nước rút nâng cao",
    "豆包应用创作零门槛创作赛进阶攻略来袭": "Chiến lược nâng cao cuộc thi sáng tạo ứng dụng Doubao không rào cản đến rồi",
    "众测，重磅嘉宾": "crowdtest, khách mời nặng ký",
    "苍何": "Thương Hà",
    "梦飞": "Mộng Phi",
    "小歪": "Tiểu Oai",
    "和未来的生活": "và cuộc sống tương lai",
    "第二期，第八节": "Kỳ 2, Bài 8",
    "从": "Từ",
    "交付完整": "bàn giao hoàn chỉnh",
    "应用": "ứng dụng",
    "企业场景": "kịch bản doanh nghiệp",
    "启动": "khởi động",
    "第二期，第七节：精雕细琢": "Kỳ 2, Bài 7: Tinh chỉnh tỉ mỉ",
    "性能提速": "tăng tốc hiệu năng",
    "体验翻倍": "trải nghiệm nhân đôi",
    "千问app众测": "Crowdtest app Qianwen",
    "第二期，第六课：多元交互：卡片、图片、语音全覆盖": "Kỳ 2, Bài 6: Tương tác đa dạng: Thẻ, hình ảnh, giọng nói bao phủ toàn bộ",
    "第二期，第五课：知识库": "Kỳ 2, Bài 5: Kho tri thức",
    "记忆": "trí nhớ",
    "最强大脑": "bộ não mạnh nhất",
    "校园": "campus",
    "创投活动优秀项目全国展示": "Triển lãm toàn quốc dự án xuất sắc hoạt động đầu tư sáng tạo",
    "大学生创意秀": "Show sáng tạo sinh viên",
    "围观同龄人如何玩转飞书": "Xem cùng trang lứa chơi Feishu như thế nào",
    "校园场景": "kịch bản campus",
    "工具的奇妙碰撞，每一个项目都藏着惊喜": "va chạm kỳ diệu của công cụ, mỗi dự án đều ẩn chứa bất ngờ",
    "第二期，第四节：工作流进阶：分支、循环、意图识别、图像处理一把抓": "Kỳ 2, Bài 4: Workflow nâng cao: Nhánh, vòng lặp, nhận diện ý định, xử lý hình ảnh nắm hết",
    "带你冲": "Dẫn bạn chạy đua",
    "大奖": "giải lớn",
    "豆包应用创作挑战赛来袭": "Cuộc thi thử thách sáng tạo ứng dụng Doubao đến rồi",
    "不止冲奖，更能学硬核技巧": "Không chỉ chạy đua giải, còn học mẹo hardcore",
    "搞定投稿": "xong bài dự thi",
    "许键": "Hứa Kiện",
    "第二期，第三节：拖拉拽入门：零代码工作流拼出复杂逻辑": "Kỳ 2, Bài 3: Nhập môn kéo thả: Workflow không code ghép logic phức tạp",
    "也过双十一": "cũng mừng Ngày Độc thân 11/11",
    "藏师傅版": "phiên bản Tạng Sư Phụ",
    "福利大放送": "phát quà lớn",
    "第二期，第二节": "Kỳ 2, Bài 2",
    "魔法": "Ma thuật",
    "一句话让": "Một câu nói để",
    "听懂人话": "hiểu ngôn ngữ người",
    "畅谈": "Thoải mái nói về",
    "第三届": "Lần thứ 3",
    "全国路演": "roadshow toàn quốc",
    "第二期开营仪式": "Lễ khai giảng kỳ 2",
    "节直播课带你从": "bài livestream dẫn bạn từ",
    "打造可上线的": "tạo ra ứng dụng có thể ra mắt",
    "第一节": "Bài 1",
    "猫叔讲提示词": "Mèo Thúc giảng prompt",
    "剪映": "CapCut",
    "模板创想季": "Mùa sáng tạo template",
    "奖金": "giải thưởng",
    "千万流量": "hàng chục triệu lưu lượng",
    "手把手教你赢赛事": "hướng dẫn chi tiết để thắng cuộc thi",
    "训练营": "Training camp",
    "学习": "học tập",
    "工作流": "workflow",
    "智能体实战训练营": "Training camp thực chiến agent thông minh",
    "王磊": "Vương Lỗi",
    "从 0-1 聚焦校园场景搭建自己的": "Từ 0-1 tập trung kịch bản campus xây dựng",
    "搭子": "bạn đồng hành",
    "结营": "bế giảng",
    "第一期": "Kỳ 1",
    "智能体项目实战": "thực chiến dự án agent thông minh",
    "海外最大": "lớn nhất hải ngoại",
    "比赛": "cuộc thi",
    "解读": "giải đọc",
    "启动会": "Hội nghị khởi động",
    "编程实战技巧": "mẹo thực chiến lập trình",
    "从入门到沉迷": "từ nhập môn đến nghiện",
    "挑战赛教程": "hướng dẫn cuộc thi thử thách",
    "让声音更有温度": "Để giọng nói ấm hơn",
    "语音大模型首席算法专家": "Chuyên gia thuật toán trưởng mô hình giọng nói lớn",
    "紫泽": "Tử Trạch",
    "语音大模型产品运营专家": "Chuyên gia vận hành sản phẩm mô hình giọng nói lớn",
    "今晚 20:00 直播": "Livestream tối nay 20:00",
    "万美金": "triệu USD",
    "工具权益": "quyền lợi công cụ",
    "万奖金的": "nghìn USD giải thưởng",
    "创意竞赛": "cuộc thi sáng tạo",
    "编程": "lập trình",
    "避坑脱口秀": "talkshow tránh bẫy",
    "言大侠": "Ngôn Đại Hiệp",
    "年新媒体运营老兵": "năm cựu binh vận hành new media",
    "脱口秀吐槽小会": "Hội talkshow roast nhỏ",
    "天涨粉": "ngày tăng fan",
    "粉丝": "fan",
    "周开发": "tuần phát triển",
    "个小程序卖": "mini app bán được",
    "都踩了什么坑": "đã giẫm những bẫy gì",
    "赛事解读": "Giải đọc giải đấu",
    "社区第一本书": "cuốn sách đầu tiên của cộng đồng",
    "绘画极简入门与应用": "Nhập môn vẽ cực đơn giản và ứng dụng",
    "正式上线": "chính thức ra mắt",
    "主题赛": "cuộc thi chủ đề",
    "第一期 第三课": "Kỳ 1 Bài 3",
    "商单": "đơn hàng thương mại",
    "拆解": "phân tích",
    "带你搭建复杂工作流系统": "dẫn bạn xây dựng hệ thống workflow phức tạp",
    "第二课主题：常见": "Bài 2 chủ đề: Các",
    "自动化工作流案例": "case workflow tự động hóa thường gặp",
    "天吃透": "ngày nắm vững",
    "工作流！": "workflow!",
    "第一期开营": "Kỳ 1 khai giảng",
    "第四期": "Số 4",
    "时代，搜索不再为人而生": "thời đại, tìm kiếm không còn dành cho con người",
    "我的": "Của tôi",
    "创业收入清单和": "Danh sách thu nhập khởi nghiệp và",
    "创业故事": "câu chuyện khởi nghiệp",
    "拆解": "Phân tích",
    "时代的学习路径与信息差": "con đường học tập và khoảng cách thông tin thời đại",
    "极速入门": "nhập môn siêu tốc",
    "绘画篇": "phần vẽ",
    "如何和大语言模型进行对话": "Cách đối thoại với mô hình ngôn ngữ lớn",
    "基础小白极速入门版": "phiên bản nhập môn siêu tốc cho người mới hoàn toàn",
    "短剧大赛": "cuộc thi phim ngắn",
    "现场编写": "viết tại chỗ",
    "现场投稿": "nộp bài tại chỗ",
    "现场展示": "trình diễn tại chỗ",
    "实测": "thử nghiệm thực tế",
    "邀请码接力": "tiếp sức mã mời",
    "切磋大会全国会议": "Hội nghị giao lưu toàn quốc",
    "导演大赛创作": "sáng tạo cuộc thi đạo diễn",
    "冰鱼仔": "Băng Ngư Tử",
    "素语": "Tố Ngữ",
    "言带你解锁": "Ngôn dẫn bạn mở khóa",
    "智能创作平台": "nền tảng sáng tạo thông minh",
    "导演体验，干货满满": "trải nghiệm đạo diễn, đầy kiến thức thực tế",
    "万奖池比赛解说": "vạn giải thưởng giải thuyết cuộc thi",
    "追热季": "mùa theo trend",
    "生存": "sinh tồn",
    "宇宙故事创作视频挑战赛开启": "cuộc thi thử thách video sáng tạo câu chuyện vũ trụ bắt đầu",
    "编程赛火热开启": "cuộc thi lập trình bắt đầu sôi nổi",
    "大奖是": "Giải lớn là",
    "歸藏": "Quy Tạng",
    "向阳联合教学": "Hướng Dương cùng giảng dạy",
    "是一个无缝衔接多模态生成的": "là một",
    "工程师深度拆解": "Kỹ sư phân tích chuyên sâu",
    "智能视频创作": "sáng tạo video thông minh",
    "玩法": "cách chơi",
    "飞书多维表格接入即梦": "Bảng đa chiều Feishu kết nối Jimeng",
    "王大仙教你玩出花": "Vương Đại Tiên dạy bạn chơi hết mình",
    "世界": "Thế giới",
    "联合呈现秒哒黑客松大赛权威解读": "cùng trình bày giải đọc uy tín cuộc thi hackathon Miaoda",
    "从 0 到 1 部署正式网站": "Triển khai website chính thức từ 0 đến 1",
    "零基础也能玩转": "Không cơ sở cũng có thể chơi",
    "编程": "lập trình",
    "搭建": "xây dựng",
    "应用": "ứng dụng",
    "即刻变现": "biến thành tiền ngay lập tức",
    "智能体工作流设计模式教学": "Giảng dạy mô hình thiết kế workflow agent thông minh",
    "拆解": "Phân tích",
    "摆摊实验，提炼": "thí nghiệm bán hàng rong, tinh lọc",
    "商业落地金字塔": "Kim tự tháp thương mại hóa",
    "完整框架": "khung hoàn chỉnh",
    "食用说明书": "Hướng dẫn sử dụng",
    "从入门到惊艳": "từ nhập môn đến ấn tượng",
    "阿里云百炼": "Alibaba Cloud Bailian",
    "创客开发实战课": "Bài thực chiến phát triển maker",
    "百万流量，最全": "triệu lưu lượng, toàn bộ nhất",
    "指南": "hướng dẫn",
    "应用创作第一课": "Bài 1 sáng tạo ứng dụng",
    "一句话建应用": "Xây ứng dụng bằng một câu nói",
    "实战课": "Bài thực chiến",
    "玩转扣子空间 网页设计新功能上线": "Chơi không gian Coze tính năng mới thiết kế web ra mắt",
    "开源多模态": "đa phương thức mã nguồn mở",
    "工具首发": "công cụ ra mắt lần đầu",
    "助手带你玩转数据分析": "Trợ lý dẫn bạn chơi phân tích dữ liệu",
    "保姆级教学": "dạy học cấp bảo mẫu",
    "开源很可能带来": "mã nguồn mở rất có thể mang đến",
    "第二波商业化红利": "đợt cổ tức thương mại hóa thứ hai",
    "一起探讨，找到属于你的机遇": "cùng thảo luận, tìm cơ hội thuộc về bạn",
    "迷你黑客松": "mini hackathon",
    "奇思妙想秀": "Show ý tưởng kỳ diệu",
    "月入万刀的": "thu nhập hàng vạn đô mỗi tháng",
    "开发者经验": "kinh nghiệm nhà phát triển",
    "手把手搭建": "hướng dẫn chi tiết xây dựng",
    "一个人如何用": "Một người cách dùng",
    "完成一部动画": "hoàn thành một bộ hoạt hình",
    "瑞克和莫蒂勇闯刻板印象宇宙": "Rick và Morty dũng cảm phá vỡ vũ trụ định kiến",
    "伦敦亮相": "ra mắt London",
    "画布": "canvas",
    "能帮创作者赚钱的嘴替": "người thay miệng giúp nhà sáng tạo kiếm tiền",
    "娜乌斯佳": "Nausica",
    "最新教程": "hướng dẫn mới nhất",
    "我": "tôi",
    "北京大赛": "cuộc thi Bắc Kinh",
    "一句话让创意到变现的超级工具箱": "Hộp công cụ siêu cấp biến sáng tạo thành tiền bằng một câu nói",
    "秒哒使用指南": "hướng dẫn sử dụng Miaoda",
    "共学": "học chung",
}

with open('_art23_trans.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Apply vocab replacements (longest first)
sorted_vocab = sorted(vocab.items(), key=lambda x: -len(x[0]))

fixed = 0
for block in data['blocks']:
    for el in block['elements']:
        if el['type'] != 'text_run':
            continue
        if not re.search(r'[\u4e00-\u9fff]', el['content']):
            continue
        text = el['content']
        for cn, vi in sorted_vocab:
            text = text.replace(cn, vi)
        if text != el['content']:
            el['content'] = text
            fixed += 1

# Count remaining
remaining = 0
remaining_chars = set()
for block in data['blocks']:
    for el in block['elements']:
        if el['type'] == 'text_run' and re.search(r'[\u4e00-\u9fff]', el['content']):
            remaining += 1
            chars = re.findall(r'[\u4e00-\u9fff]+', el['content'])
            for c in chars:
                remaining_chars.add(c)

print(f"Fixed: {fixed}")
print(f"Still remaining: {remaining}")
if remaining_chars:
    print(f"Remaining CN words: {sorted(remaining_chars)[:30]}")

with open('_art23_trans.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved.")
