import json, re

def has_chinese(text):
    return bool(re.search(r'[\u4e00-\u9fff]', text))

with open('art3_original.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Common short translations used throughout tables
SHORT = {
    "低": "Thấp", "中": "Trung bình", "高": "Cao", "极高": "Rất cao",
    "笔记": "Ghi chú", "任务": "Nhiệm vụ", "工作": "Công việc", "聊天": "Chat",
    "社交": "Mạng xã hội", "开发": "Phát triển", "音乐": "Âm nhạc", "家居": "Nhà thông minh",
    "外卖": "Đặt đồ ăn", "创意": "Sáng tạo", "语音": "Giọng nói", "安全": "Bảo mật",
    "系统": "Hệ thống", "地点": "Địa điểm", "媒体": "Truyền thông", "新闻": "Tin tức",
    "文档": "Tài liệu", "监控": "Giám sát", "通讯": "Liên lạc",
}

translations = {
    "B0E0": "OpenClaw từ cài đặt đến thực chiến: Sổ tay cấu hình hoàn chỉnh của một nhà phát triển",
    "B1E0": "🔗 Link bài gốc: ",
    "B2E0": "Nguyên tác: Jason AI Ra Biển (杰森AI出海)",
    "B2E1": "27/02/2026 11:32 Thái Lan",
    "B3E0": "Sau khi cài xong OpenClaw, nhiều người đứng trước file cấu hình mà ngẩn người.",
    "B4E0": "Các công cụ nằm rải rác trong nhiều tài liệu khác nhau. Skill mặc định tự động tải hết, có cái đã kích hoạt rồi mà bạn không hề biết. Bật hết thì sợ rủi ro, tắt hết thì cảm thấy cài phí. Muốn ghép nối toàn cảnh từ tài liệu và mã nguồn, cần đầu tư rất nhiều thời gian và công sức.",
    "B5E0": "Bài viết này đến từ ghi chú thực chiến của một nhà phát triển. Anh đã dành rất nhiều thời gian nghiên cứu 25 công cụ và 53 Skill chính thức của OpenClaw, phân tích từng cái một về chức năng, rủi ro tiềm ẩn và gợi ý cấu hình. Cuối bài còn đính kèm file cấu hình hoàn chỉnh của anh, bạn có thể copy dùng luôn.",
    "B6E0": "(Trên ClawHub có hơn 3000 Skill bên thứ ba, không nằm trong phạm vi thảo luận của bài này.)",
    "B7E0": "Hiểu trước: Sự khác biệt giữa công cụ và Skill",
    "B8E0": "Nhiều người nhầm lẫn hai khái niệm này, thực ra sự khác biệt rất rõ ràng",
    "B9E0": 'Công cụ là cơ quan, quyết định OpenClaw "có thể" làm việc gì đó hay không',
    "B10E0": "read và write cho phép nó thao tác file, exec cho phép nó thực thi lệnh hệ thống, web_search cho phép nó tìm kiếm, web_fetch cho phép nó đọc trang web, browser cho phép nó điều khiển trình duyệt. Không bật công cụ tương ứng, OpenClaw giống như thiếu tay thiếu chân, không làm được gì cả.",
    "B11E0": 'Skill là sách giáo khoa, dạy OpenClaw "cách kết hợp công cụ" để hoàn thành nhiệm vụ',
    "B12E0": "gog dạy nó dùng Google Workspace xử lý email và lịch, obsidian dạy nó quản lý ghi chú, github dạy nó thao tác kho code, slack dạy nó gửi tin nhắn kênh. 53 Skill chính thức bao phủ nhiều lĩnh vực: ghi chú, email, mạng xã hội, phát triển, nhà thông minh.",
    "B13E0": "Cài Skill có thêm quyền mới cho OpenClaw không? Không.",
    "B14E0": "Ví dụ: bạn cài Skill obsidian, OpenClaw biết cách sắp xếp ghi chú. Nhưng nếu không bật công cụ write, nó không thể ghi file. Skill chỉ là hướng dẫn sử dụng, công tắc thực sự nằm ở công cụ.",
    "B15E0": 'Để OpenClaw thực thi thao tác qua Skill, phải đáp ứng ba điều kiện. Lấy ví dụ "đọc Gmail":',
    "B16E0": "Cấu hình: Bạn có cho phép OpenClaw thực thi lệnh không? (Không có exec, nó không thể khởi động chương trình)",
    "B17E0": "Cài đặt: Máy có cài công cụ bridge gog không? (Không có nó, OpenClaw biết phải làm gì nhưng kết nối không được với Google)",
    "B18E0": "Ủy quyền: Bạn có đăng nhập tài khoản Google và cấp quyền không? (Không ủy quyền, Google sẽ không cho qua)",
    "B19E0": "Ba điều kiện thiếu một không được.",
    "B20E0": "Skill là hướng dẫn sử dụng, thực tế dùng được hay không phụ thuộc ba điều kiện này.",
    "B21E0": "Kiến trúc vòng tròn đồng tâm: Từ lõi đến vòng ngoài",
    "B22E0": "Liệt kê phẳng 25 công cụ và 53 Skill sẽ khiến người ta choáng ngợp. Nhà phát triển này dùng cách vòng tròn đồng tâm để tổ chức:",
    "B23E0": "Kiến trúc vòng tròn đồng tâm OpenClaw:",
    "B24E0": "Tầng 1: Công cụ cốt lõi (read, write, exec)",
    "B25E0": "Tầng 2: Công cụ nâng cao (browser, memory, automation)",
    "B26E0": "Tầng 3: Tầng tri thức (53 Skill chính thức)",
    "B27E0": "Tầng 1: Năng lực cốt lõi (8 công cụ)",
    "B28E0": '8 công cụ này là nền tảng của OpenClaw. Chỉ bật những cái này, OpenClaw ở chế độ "phản hồi bị động": bạn hỏi, nó trả lời. Nó có thể đọc file, thực thi lệnh, tìm kiếm web, nhưng không nhớ sở thích của bạn qua các phiên, cũng không chủ động đẩy thông báo. Chìa khóa biến OpenClaw từ "chatbot" thành "trợ lý" nằm ở Tầng 2. Nhưng không có Tầng 1, Tầng 2 không thể vận hành.',
    "B29E0": "Thao tác file: read, write, edit, apply_patch",
    "B30E0": "read chỉ đọc. write và edit có thể sửa file, apply_patch dùng để áp dụng thay đổi code. Bốn công cụ này là nền tảng của nền tảng, hầu hết mọi người sẽ bật hết.",
    "B31E0": "Thực thi và quản lý tiến trình: exec, process",
    "B32E0": 'exec cho phép OpenClaw thực thi bất kỳ lệnh shell nào: cài gói, chạy script, quản lý hệ thống. "Bất kỳ" là từ khóa: nó có thể giúp bạn cài dependency, cũng có thể chạy rm -rf xóa sạch toàn bộ máy. Không có exec, hầu hết nhiệm vụ không thể hoàn thành. Bật exec mà không có bảo vệ, tương đương giao quyền root ra ngoài.',
    "B33E0": "Đây là lý do tại sao mạnh mẽ",
    "B33E1": "khuyến nghị bật chế độ phê duyệt cho exec: mỗi lệnh hiển thị cho bạn trước, xác nhận rồi mới thực thi:",
    "B34E0": "Phiền không? Nói thật, hơi phiền. Nhưng đây là lớp bảo vệ cơ bản nhất: nếu AI phán đoán sai, hoặc bị tấn công Prompt Injection, cánh cửa này là tuyến phòng thủ cuối cùng.",
    "B35E0": "process quản lý tiến trình nền: xem danh sách nhiệm vụ, kiểm tra output, dừng tiến trình bị treo. Thường bật cùng exec.",
    "B36E0": "Truy cập mạng: web_search, web_fetch",
    "B37E0": "web_search thực hiện tìm kiếm từ khóa, web_fetch đọc nội dung trang web. Hai cái phối hợp, cho OpenClaw khả năng duyệt internet lấy thông tin.",
    "B38E0": "Tầng 2: Năng lực nâng cao (17 công cụ)",
    "B39E0": 'Tầng 1 giải quyết "có dùng được không", Tầng 2 giải quyết "dùng có tốt không". Những công cụ này biến OpenClaw từ kẻ thực thi lệnh thành trợ lý thực sự: nó sẽ nhớ sở thích của bạn, điều khiển trình duyệt, gửi thông báo định kỳ. Nhưng mỗi khi thêm một công cụ, bề mặt tấn công mở rộng thêm, cần cân nhắc có đáng không.',
    "B40E0": "Trình duyệt: browser, canvas, image",
    "B41E0": "browser cho phép OpenClaw điều khiển Chrome: click nút, điền form, chụp trang web. Nhà phát triển này dùng nó để so sánh giá, nghiên cứu thông số, thêm vào giỏ hàng. Nhưng bước thanh toán luôn tự thao tác. \"Dặm cuối cùng\" liên quan đến thanh toán không bao giờ giao cho AI, đó là giới hạn của anh.",
    "B42E0": 'canvas là không gian làm việc trực quan, dùng để vẽ biểu đồ và sơ đồ quy trình. image cho OpenClaw khả năng "hiểu" hình ảnh.',
    "B43E0": "Bộ nhớ: memory_search, memory_get",
    "B44E0": "Cho OpenClaw nhớ thông tin xuyên phiên. Sau một tuần sử dụng, nó biết nhà phát triển này dùng Astro xây blog, deploy trên Azure, thói quen dùng tiếng Trung phồn thể. Không cần giải thích lại mỗi lần. Dùng càng lâu, nó càng hiểu bạn.",
    "B45E0": "Đa phiên: Bộ sessions (5 công cụ)",
    "B46E0": "Chạy đồng thời nhiều phiên xử lý các nhiệm vụ khác nhau: một cái thảo luận ý tưởng sản phẩm, cái khác nghiên cứu kế hoạch du lịch, không ảnh hưởng lẫn nhau.",
    "B47E0": "sessions_list và sessions_history xem phiên",
    "B48E0": "session_status kiểm tra trạng thái;",
    "B49E0": "sessions_send và sessions_spawn thực hiện giao tiếp giữa các phiên và tạo tác vụ con.",
    "B50E0": "Đẩy tin nhắn: message",
    "B51E0": "Cho phép OpenClaw gửi tin nhắn đến Discord, Slack, Telegram, WhatsApp, iMessage.",
    "B52E0": "Nhà phát triển này đã bật tính năng này, nhưng chỉ dùng để gửi tin nhắn cho chính mình, không bao giờ đại diện anh giao tiếp với người khác. Lý do đơn giản: tin nhắn AI gửi dưới tên bạn không thể thu hồi. Nếu nó hiểu sai ngữ cảnh, dùng sai giọng điệu, hoặc bị Prompt Injection dụ gửi nội dung không phù hợp, hậu quả bạn chịu.",
    "B53E0": "Trong hệ thống quản lý mục tiêu AI của anh, OpenClaw đóng vai trò tầng giao tiếp. Bật message, nó có thể chủ động đẩy thông báo: bản tin hàng ngày, nhắc nhở nhiệm vụ, cảnh báo công việc cần làm, tất cả gửi cho chính mình.",
    "B54E0": "Điều khiển phần cứng: nodes",
    "B55E0": "Điều khiển phần cứng xuyên thiết bị: chụp màn hình từ xa, định vị GPS, truy cập camera.",
    "B56E0": "Lần đầu thấy công cụ này, nhà phát triển tự hỏi: khi nào cần AI tự động mở camera? Anh nghĩ không ra. Còn chụp màn hình, anh có thể gửi thủ công qua Telegram, thêm một bước nhưng yên tâm hơn nhiều. Cuối cùng chọn tắt.",
    "B57E0": "Tự động hóa: cron, gateway",
    "B58E0": "cron thiết lập nhiệm vụ định kỳ",
    "B59E0": "gateway cho phép OpenClaw có thể khởi động lại chính nó.",
    "B60E0": "Mỗi sáng 6:47, Telegram của anh nhận được bản tin hàng ngày OpenClaw chuẩn bị: hôm nay làm gì, có tin nhắn nào cần trả lời, dự báo thời tiết. Đây là hiệu quả kết hợp cron + message, cũng là cốt lõi của hệ thống quản lý mục tiêu AI của anh.",
    "B61E0": "Giao tiếp đại lý: agents_list",
    "B62E0": "Liệt kê Agent ID khả dụng. OpenClaw hỗ trợ kiến trúc đa đại lý, nhưng tài liệu chính thức chưa mô tả chi tiết. Nếu chỉ chạy một instance OpenClaw, không cần công cụ này.",
    "B63E0": "Công cụ mở rộng: llm_task, lobster",
    "B64E0": "lobster là engine workflow, dùng để định nghĩa quy trình nhiều bước. llm_task chèn bước xử lý LLM vào workflow.",
    "B65E0": "Nếu bạn không dùng workflow engine, hai cái đều có thể bỏ qua.",
    "B66E0": "Tầng 3: Tầng tri thức (53 Skill chính thức)",
    "B67E0": "53 cái nghe có vẻ nhiều, nhưng lướt qua bạn sẽ thấy có lẽ chỉ mười mấy cái liên quan đến bạn. Các cái khác như đặt đồ ăn, nhà thông minh, gọi điện thoại - không phải chúng không tốt, chỉ là không phù hợp với kịch bản sử dụng của bạn.",
    "B68E0": 'Lưu ý quan trọng: Skill đi kèm mặc định tự động tải. Nếu máy đã cài công cụ CLI tương ứng, Skill sẽ tự kích hoạt. Đây không phải "không cài thì không có", mà là "không tắt thì bật hết". Để kiểm soát Skill nào hoạt động, dùng chế độ whitelist skills.allowBundled (ví dụ cấu hình xem phần "Cấu hình của tôi" cuối bài).',
    "B69E0": "Trên ClawHub có hơn 3000 Skill bên thứ ba, nhưng rủi ro bảo mật của chúng là một chủ đề khác.",
    "B70E0": "Dưới đây phân loại theo kịch bản sử dụng.",
    "B71E0": "1. Loại ghi chú",
    "B72E0": "4 Skill ghi chú: obsidian, notion, apple-notes, bear-notes. Có dùng được hay không phụ thuộc vào môi trường triển khai.",
    "B73E1": " và ",
    "B73E3": " chỉ dùng được trên Mac cục bộ. Nếu OpenClaw chạy trong máy ảo, hai cái này không có tác dụng.",
    "B74E1": " thao tác file cục bộ. Nhà phát triển này dùng Obsidian, nhưng kho của anh ở Mac, còn OpenClaw chạy trên Azure VM, nên anh chọn dùng Claude Code xử lý ghi chú cục bộ, thay vì qua OpenClaw.",
    "B75E0": "Nếu muốn OpenClaw quản lý ghi chú trực tiếp, và chạy trong máy ảo, ",
    "B75E2": " là trên cloud, không giới hạn triển khai, là phương án ít trở ngại nhất.",
    "B76E0": "2. Loại năng suất",
    "B77E0": "Hai Skill email: gog và himalaya.",
    "B78E0": "gog tích hợp toàn bộ Google Workspace (Gmail, Lịch, Tasks, Drive, Docs, Sheets).",
    "B79E0": "himalaya chỉ dùng IMAP/SMTP thu phát email. Nếu bạn dùng hệ sinh thái Google, chọn gog đầy đủ hơn, và luôn có thể thu hồi ủy quyền trong tài khoản Google.",
    "B80E0": "Quản lý nhiệm vụ có things-mac (Things 3), apple-reminders, trello. Nếu đã cài gog, Google Tasks đã bao gồm, không cần cài thêm.",
    "B82E0": "Những Skill này cho OpenClaw truy cập sâu vào các nền tảng, bao gồm tìm kiếm lịch sử tin nhắn, đồng bộ cuộc trò chuyện, quản lý kênh. Khác với công cụ message (chỉ gửi được tin nhắn), cài những cái này tương đương giao toàn bộ quyền truy cập dữ liệu của bạn trên nền tảng tương ứng cho nó.",
    "B83E0": "Nhà phát triển này không cài cái nào. Bước cuối cùng của giao tiếp đối ngoại luôn hoàn thành thủ công.",
    "B84E0": "3. Công cụ phát triển",
    "B85E0": "Anh cài github, tmux, session-logs. Anh dùng Claude Code viết code cục bộ, nhưng OpenClaw có thể liên lạc qua Telegram bất cứ lúc nào. Nếu ra ngoài mà CI/CD sập, anh hỏi trực tiếp trên điện thoại \"kiểm tra xem PR này build fail vì sao\", OpenClaw sẽ kéo log lỗi GitHub Actions và nói cho anh biết vấn đề.",
    "B86E0": "Anh chưa cài coding-agent, nhưng tiềm năng rất lớn: có thể cài Claude Code trên VM của OpenClaw, để nó điều phối nhiệm vụ coding chạy nền.",
    "B87E0": 'Hãy tưởng tượng, qua Telegram nói với OpenClaw: "Tôi tìm thấy một repo thú vị trên GitHub, clone về nghiên cứu, rồi dựng một site demo." Nó khởi động Claude Code, tự thực thi, xong thì đẩy thông báo. AI điều phối AI. Anh chưa khám phá sâu, nhưng đã nằm trong danh sách việc cần làm.',
    "B88E0": "4. Quản lý mật khẩu",
    "B89E0": '1password cho phép OpenClaw truy cập vault 1Password của bạn: tra mật khẩu, tự động đăng nhập, điền form. Kịch bản sử dụng như: "Giúp tôi đăng nhập AWS Console" hoặc "Mật khẩu trang web này là gì".',
    "B90E0": 'Nhưng mô hình quyền là toàn bộ hoặc không: một khi ủy quyền, toàn bộ vault mở ra cho nó. Bạn không thể giới hạn chỉ truy cập mục cụ thể, bạn lưu gì, nó đọc được hết. Nhà phát triển này chọn không cài. Nếu thực sự cần, khuyến nghị tạo một "vault chuyên dụng cho AI", chỉ đặt mật khẩu bạn sẵn sàng chia sẻ với AI.',
    "B91E0": "5. Các loại khác",
    "B92E0": "Trên đây là các loại anh chủ động sử dụng hoặc cân nhắc nghiêm túc.",
    "B93E0": "Còn lại như phát nhạc, nhà thông minh, tạo hình ảnh, chuyển giọng nói thành văn bản, đặt đồ ăn, anh đều không cài. Danh sách đầy đủ xem phụ lục cuối bài.",
    "B94E0": "Cấu hình OpenClaw của tôi: Logic chọn công cụ và Skill",
    "B95E0": "OpenClaw của nhà phát triển này chạy trên Azure VM, thao tác qua Telegram. Kết hợp với Claude Code trên desktop, tạo thành workflow song song mobile + desktop: mobile bất cứ lúc nào thảo luận, nghiên cứu, ghi ý tưởng (lịch sử hội thoại tự đồng bộ), desktop thực thi. Anh còn dùng nó xử lý email hàng ngày, lịch, nghiên cứu, và mỗi sáng nhận Daily Brief.",
    "B96E0": "Dưới đây là cấu hình hiện tại và logic lựa chọn:",
    "B97E0": "1. Công cụ (bật 21 trong 25)",
    "B98E0": "Nguyên tắc rất đơn giản: nghĩ không ra kịch bản sử dụng, tắt hết.",
    "B99E0": "Bật 21, tắt 4:",
    "B100E0": "nodes (nghĩ không ra kịch bản)",
    "B101E0": "canvas (không cần)",
    "B102E0": "llm_task/lobster (không dùng workflow engine)",
    "B103E0": "exec bật chế độ phê duyệt",
    "B104E0": "message chỉ gửi tin nhắn cho chính mình.",
    "B105E0": "2. Skill (bật 9 trong 53)",
    "B106E0": "Như đã nói, Skill đi kèm mặc định tự tải. Anh dùng allowBundled whitelist giới hạn chỉ tải những cái cần:",
    "B107E0": "Nói đơn giản: gog xử lý email và lịch, github quản lý repo, còn lại là Skill công cụ cho Daily Brief và quản lý hệ thống.",
    "B108E0": "Cách dùng AI Agent thực hiện tự động hóa nhiệm vụ",
    "B109E0": "Đến đây, OpenClaw bắt đầu chuyển từ chatbot thành hạ tầng.",
    "B110E0": "Kết hợp cron (lập lịch định kỳ) + message (đẩy thông báo), biến nó thành engine tự động hóa có thể làm việc khi bạn ngủ.",
    "B111E0": "Mô hình luôn giống nhau: điều kiện kích hoạt + hành động thực thi + giao kết quả. Định nghĩa khi nào chạy, làm gì, kết quả gửi đi đâu. Dưới đây là các kịch bản tự động hóa anh thực sự sử dụng:",
    "B112E0": "Bản tin hàng ngày: Mỗi sáng 6:47, Telegram nhận bản tin: lịch trình hôm nay, email chưa trả lời cần xử lý, dự báo thời tiết, và ban đêm có lỗi CI/CD nào không. Một automation này thay thế thói quen kiểm tra năm ứng dụng trước khi uống cà phê.",
    "B113E0": "Phân loại email: Hai lần mỗi ngày, OpenClaw quét hộp thư đến, phân loại theo mức độ khẩn cấp, gửi tóm tắt. Email newsletter lưu trữ luôn. Việc cần xử lý được đánh dấu kèm một dòng tóm tắt. Anh nén 30 phút quản lý hộp thư mỗi ngày xuống còn 5 phút.",
    "B114E0": "Giám sát CI/CD: Khi workflow GitHub Actions fail, OpenClaw đọc log lỗi, phán đoán nguyên nhân có thể, đẩy tin nhắn Telegram kèm kết quả chẩn đoán. Anh từng sửa lỗi production bằng điện thoại khi đang xếp hàng mua cà phê.",
    "B115E0": "Nghiên cứu nội dung: Hàng ngày, OpenClaw thu thập thảo luận hot trong các subreddit cụ thể, thread Hacker News, nguồn RSS anh theo dõi, tổng hợp thành tóm tắt chủ đề viết bài tiềm năng. Nó không viết thay anh, chỉ giúp anh tìm nội dung đáng viết.",
    "B116E0": "Thiết lập không phức tạp, mỗi automation là một cron entry kích hoạt một prompt, prompt nói cho OpenClaw dùng công cụ nào, kết quả gửi đi đâu.",
    "B117E0": "Khó không phải ở cấu hình, mà là nghĩ rõ quy trình hàng ngày nào đáng tự động hóa. Bắt đầu từ cái gây ma sát lớn nhất mỗi ngày, chạy thông nó, rồi từ từ thêm.",
    "B118E0": "Bắt đầu cấu hình OpenClaw của bạn",
    "B119E0": "Bạn không cần tất cả 25 công cụ. 53 Skill đi kèm mặc định bật hết, dùng allowBundled chỉ giữ những cái cần",
    "B120E0": "thiết.",
    "B121E0": "Mở openclaw.json của bạn, tuân thủ ba nguyên tắc:",
    "B122E0": "Nghĩ không ra kịch bản sử dụng, tắt trước",
    "B123E0": "Năng lực càng lớn, quản lý càng chặt: exec bật phê duyệt, message chỉ gửi cho chính mình",
    "B124E0": "Dặm cuối cùng luôn thủ công: thanh toán, gửi tin nhắn, phát ngôn công khai, mọi thao tác không thể hoàn tác để lại cho chính mình",
    "B125E0": "Cấu hình trên có thể làm điểm khởi đầu, copy nó, rồi tùy chỉnh theo nhu cầu của bạn.",
    "B126E0": "Câu hỏi thường gặp",
    "B127E0": "1. Skill có thay đổi quyền hạn của OpenClaw không?",
    "B128E0": "Không. Skill chỉ là hướng dẫn sử dụng, năng lực thực tế do tools.allow kiểm soát.",
    "B129E0": "2. Skill 1password có đọc được tất cả mật khẩu của tôi không?",
    "B130E0": "Có. Một khi ủy quyền, toàn bộ vault mở ra cho nó, bạn lưu gì, nó đọc được hết.",
    "B131E0": "3. Làm sao thu hồi quyền truy cập Google của OpenClaw?",
    "B132E0": "Tài khoản Google -> Bảo mật -> Ứng dụng bên thứ ba có quyền truy cập tài khoản -> Tìm gog -> Xóa quyền truy cập.",
    "B133E0": "4. Skill bên thứ ba trên ClawHub có an toàn không?",
    "B134E0": "Đừng mặc định cho là an toàn, trước khi cài nhất định phải xem GitHub repo, có thể dùng openclaw doctor kiểm tra",
    "B135E0": "5. Tại sao có 25 công cụ?",
    "B136E0": "Tài liệu chính thức liệt kê 18. Nhà phát triển này phát hiện 25 qua đọc mã nguồn. Thêm vào bao gồm công cụ liên quan phiên, agents_list, và công cụ workflow engine chưa được đề cập trong tài liệu (llm_task, lobster)",
    "B137E0": "6. OpenClaw và ChatGPT khác nhau ở đâu?",
    "B138E0": "ChatGPT là công cụ chat, OpenClaw là Agent, sự khác biệt nằm ở sau khi cuộc trò chuyện kết thúc chuyện gì xảy ra:",
    "B139E0": 'Thậm chí ý nghĩa của "đồng bộ" cũng khác nhau: Đồng bộ của ứng dụng LLM nghĩa là bạn xem được cùng một lịch sử hội thoại trên điện thoại và desktop.',
    "B140E0": 'Đồng bộ của OpenClaw nghĩa là cuộc trò chuyện trở thành file trong thư mục máy tính của bạn, các công cụ khác có thể trực tiếp đọc và tiếp tục xử lý. Một cái là "nhìn thấy được", một cái là "thao tác được".',
    "B141E0": "Nếu bạn chỉ muốn chat, ChatGPT đủ dùng; nếu bạn muốn AI tiếp tục làm việc sau khi cuộc trò chuyện kết thúc, bạn cần Agent như OpenClaw.",
    "B142E0": "7. Làm sao dùng OpenClaw thực hiện tự động hóa nhiệm vụ AI?",
    "B143E0": "Kết hợp cron (lập lịch định kỳ) và message (đẩy thông báo).",
    "B144E0": "OpenClaw thực hiện nhiệm vụ theo lịch, đẩy kết quả đến nền tảng nhắn tin của bạn. Mỗi sáng 6:47, nhà phát triển này nhận bản tin: nhiệm vụ hôm nay, việc cần trả lời, dự báo thời tiết.",
    "B145E0": "Ngoài đẩy định kỳ, các kịch bản tự động hóa phổ biến bao gồm: phân loại email và tóm tắt ưu tiên, giám sát lỗi CI/CD, thu thập tài liệu viết bài định kỳ, tóm tắt tin tức ngành.",
    "B146E0": 'Bản chất, bất kỳ nhiệm vụ nào có thể phân tách thành "điều kiện kích hoạt + bước thực thi" đều có thể tự động hóa.',
    "B147E0": "8. Sử dụng OpenClaw có cần biết lập trình không?",
    "B148E0": 'Sử dụng hàng ngày không cần lập trình, dùng ngôn ngữ tự nhiên trò chuyện là được, ví dụ: "Kiểm tra email hôm nay", "Đặt nhắc nhở sáng mai 9 giờ", nói trực tiếp là được.',
    "B149E0": "Nhưng OpenClaw là dự án mã nguồn mở, cài đặt và cấu hình có đường cong học tập, có thể triển khai lên VM cloud hoặc cài cục bộ.",
    "B150E0": "Vì lý do bảo mật, khuyến nghị dùng máy chuyên dụng thay vì máy chính hàng ngày. Nếu dùng công cụ AI CLI như Claude Code, nó có thể hỗ trợ hoàn thành quá trình thiết lập, tiết kiệm rất nhiều thời gian.",
    "B151E0": "Phụ lục: Tham khảo đầy đủ",
    "B152E0": "Toàn bộ 25 công cụ",
    "B153E0": "Tầng",
    "B154E0": "Công cụ",
    "B155E0": "Chức năng",
    "B156E0": "Rủi ro",
    "B159E0": "Đọc file",
    "B160E0": "Thấp",
    "B163E0": "Ghi file",
    "B164E0": "Trung bình",
    "B167E0": "Chỉnh sửa có cấu trúc",
    "B168E0": "Trung bình",
    "B171E0": "Áp dụng bản vá",
    "B172E0": "Trung bình",
    "B175E0": "Thực thi lệnh",
    "B176E0": "Rất cao",
    "B179E0": "Quản lý tiến trình",
    "B180E0": "Trung bình",
    "B183E0": "Tìm kiếm web",
    "B184E0": "Thấp",
    "B187E0": "Lấy trang web",
    "B188E0": "Trung bình",
    "B191E0": "Điều khiển trình duyệt",
    "B192E0": "Cao",
    "B195E0": "Không gian làm việc trực quan",
    "B196E0": "Thấp",
    "B199E0": "Phân tích hình ảnh",
    "B200E0": "Thấp",
    "B203E0": "Tìm kiếm bộ nhớ",
    "B204E0": "Trung bình",
    "B207E0": "Lấy bộ nhớ",
    "B208E0": "Trung bình",
    "B211E0": "Liệt kê phiên",
    "B212E0": "Thấp",
    "B215E0": "Lịch sử phiên",
    "B216E0": "Trung bình",
    "B219E0": "Gửi tin nhắn",
    "B220E0": "Cao",
    "B223E0": "Tạo agent con",
    "B224E0": "Cao",
    "B227E0": "Kiểm tra trạng thái",
    "B228E0": "Thấp",
    "B231E0": "Tin nhắn đa nền tảng",
    "B232E0": "Rất cao",
    "B235E0": "Điều khiển phần cứng",
    "B236E0": "Rất cao",
    "B239E0": "Nhiệm vụ định kỳ",
    "B240E0": "Cao",
    "B243E0": "Quản lý gateway",
    "B244E0": "Cao",
    "B247E0": "Liệt kê agent",
    "B248E0": "Thấp",
    "B249E0": "Mở rộng",
    "B251E0": "Bước LLM trong workflow",
    "B252E0": "Trung bình",
    "B253E0": "Mở rộng",
    "B255E0": "Engine workflow",
    "B256E0": "Trung bình",
    "B257E0": "Toàn bộ 53 Skill",
    "B258E0": "Loại",
    "B260E0": "Nền tảng/Chức năng",
    "B261E0": "Rủi ro",
    "B262E0": "Ghi chú",
    "B265E0": "Thấp",
    "B266E0": "Ghi chú",
    "B269E0": "Trung bình",
    "B270E0": "Ghi chú",
    "B273E0": "Thấp",
    "B274E0": "Ghi chú",
    "B277E0": "Thấp",
    "B278E0": "Nhiệm vụ",
    "B281E0": "Thấp",
    "B282E0": "Nhiệm vụ",
    "B284E0": "Nhắc nhở",
    "B285E0": "Thấp",
    "B286E0": "Nhiệm vụ",
    "B289E0": "Trung bình",
    "B290E0": "Công việc",
    "B293E0": "Trung bình",
    "B294E0": "Công việc",
    "B297E0": "Cao",
    "B298E0": "Chat",
    "B301E0": "Trung bình",
    "B302E0": "Chat",
    "B305E0": "Trung bình",
    "B306E0": "Chat",
    "B309E0": "Rất cao",
    "B310E0": "Chat",
    "B313E0": "Rất cao",
    "B314E0": "Chat",
    "B316E0": "iMessage (bên ngoài)",
    "B317E0": "Cao",
    "B318E0": "Mạng xã hội",
    "B321E0": "Rất cao",
    "B322E0": "Phát triển",
    "B325E0": "Trung bình",
    "B326E0": "Phát triển",
    "B328E0": "AI coding",
    "B329E0": "Trung bình",
    "B330E0": "Phát triển",
    "B332E0": "Terminal",
    "B333E0": "Thấp",
    "B334E0": "Phát triển",
    "B336E0": "Tìm kiếm log",
    "B337E0": "Thấp",
    "B338E0": "Âm nhạc",
    "B341E0": "Thấp",
    "B342E0": "Âm nhạc",
    "B345E0": "Thấp",
    "B346E0": "Âm nhạc",
    "B349E0": "Thấp",
    "B350E0": "Nhà thông minh",
    "B353E0": "Thấp",
    "B354E0": "Nhà thông minh",
    "B357E0": "Thấp",
    "B358E0": "Đặt đồ ăn",
    "B360E0": "Đa nền tảng",
    "B361E0": "Cao",
    "B362E0": "Đặt đồ ăn",
    "B365E0": "Trung bình",
    "B366E0": "Sáng tạo",
    "B368E0": "Hình ảnh OpenAI",
    "B369E0": "Thấp",
    "B370E0": "Sáng tạo",
    "B372E0": "Hình ảnh Gemini",
    "B373E0": "Thấp",
    "B374E0": "Sáng tạo",
    "B376E0": "Khung hình video",
    "B377E0": "Thấp",
    "B378E0": "Sáng tạo",
    "B380E0": "Tìm kiếm GIF",
    "B381E0": "Thấp",
    "B382E0": "Giọng nói",
    "B385E0": "Thấp",
    "B386E0": "Giọng nói",
    "B388E0": "Chuyển giọng nói thành văn bản",
    "B389E0": "Thấp",
    "B390E0": "Giọng nói",
    "B392E0": "Chuyển giọng nói thành văn bản (cloud)",
    "B393E0": "Thấp",
    "B394E0": "Giọng nói",
    "B396E0": "TTS offline",
    "B397E0": "Thấp",
    "B398E0": "Bảo mật",
    "B401E0": "Rất cao",
    "B405E0": "Thấp",
    "B409E0": "Thấp",
    "B412E0": "Tích hợp MCP",
    "B413E0": "Trung bình",
    "B414E0": "Hệ thống",
    "B416E0": "Quản lý Skill",
    "B417E0": "Thấp",
    "B418E0": "Hệ thống",
    "B420E0": "Tạo Skill",
    "B421E0": "Thấp",
    "B422E0": "Hệ thống",
    "B424E0": "Kiểm tra sức khỏe",
    "B425E0": "Thấp",
    "B426E0": "Hệ thống",
    "B428E0": "Tóm tắt",
    "B429E0": "Thấp",
    "B430E0": "Hệ thống",
    "B432E0": "Thời tiết",
    "B433E0": "Thấp",
    "B434E0": "Địa điểm",
    "B437E0": "Thấp",
    "B438E0": "Địa điểm",
    "B440E0": "Agent cục bộ",
    "B441E0": "Thấp",
    "B442E0": "Truyền thông",
    "B444E0": "Camera RTSP",
    "B445E0": "Trung bình",
    "B446E0": "Tin tức",
    "B448E0": "Giám sát RSS",
    "B449E0": "Thấp",
    "B450E0": "Tài liệu",
    "B452E0": "Chỉnh sửa PDF",
    "B453E0": "Thấp",
    "B454E0": "Giám sát",
    "B456E0": "Theo dõi sử dụng",
    "B457E0": "Thấp",
    "B458E0": "Hệ thống",
    "B461E0": "Cao",
    "B462E0": "Liên lạc",
    "B464E0": "Gọi thoại",
    "B465E0": "Cao",
    "B466E0": "Sáng tạo",
    "B468E0": "Thao tác Canvas",
    "B469E0": "Thấp",
    "B470E0": "Âm nhạc",
    "B472E0": "Trực quan hóa âm thanh",
    "B473E0": "Thấp",
    "B474E0": "Nhóm công cụ (phím tắt)",
    "B475E0": "Tên nhóm",
    "B476E0": "Bao gồm công cụ",
    "B493E0": "Muốn tìm hiểu thêm? Tham gia cộng đồng ra biển của chúng tôi, cùng đào vàng thị trường toàn cầu trong kỷ nguyên AI.",
    "B494E0": "Bài viết này dựa trên hướng dẫn của yuwenhao, đã tiến hành nghiên cứu sâu và tổng hợp",
    "B496E0": "Nếu thấy có giá trị, hoan nghênh chia sẻ cho nhiều bạn bè cần thiết hơn.",
}

# Apply
stats = {"total_blocks": len(data["blocks"]), "translated": 0, "kept": 0, "total_text": 0, "errors": []}
for i, block in enumerate(data["blocks"]):
    for j, elem in enumerate(block.get("elements", [])):
        content = elem.get("content", "")
        if not content.strip():
            continue
        stats["total_text"] += 1
        key = f"B{i}E{j}"
        if key in translations:
            elem["content"] = translations[key]
            stats["translated"] += 1
        elif not has_chinese(content):
            stats["kept"] += 1
        else:
            stats["errors"].append(key)

with open("art3_translated.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Stats: translated={stats['translated']}, kept={stats['kept']}, errors={len(stats['errors'])}, total={stats['total_text']}")
if stats["errors"]:
    for key in stats["errors"][:10]:
        parts = key.split("E")
        i, j = int(parts[0][1:]), int(parts[1])
        c = data["blocks"][i]["elements"][j].get("content", "")
        print(f"  MISSING {key}: {repr(c[:80])}")
    if len(stats["errors"]) > 10:
        print(f"  ... and {len(stats['errors'])-10} more")
