# -*- coding: utf-8 -*-
import json, sys
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')

with open('segments_5.json', 'r', encoding='utf-8') as f:
    segments = json.load(f)

translations = [
    "Tổng quan các trường hợp ứng dụng OpenClaw",
    "Các bạn cũng có thể thông qua Alibaba Cloud Bailian",
    " để triển khai",
    "Mua lần đầu chỉ từ 7.9 tệ, gia hạn giảm 50%, hỗ trợ các model Qwen3.5, Qwen3-max, Qwen3-coder, GLM-5, GLM-4.7, Kimi-k2.5, v.v.",
    "👉Nhấn link truy cập trực tiếp:",
    "👉Xem hướng dẫn triển khai chi tiết:",
    "Chỉ cần tối đa ba bước, là có thể sở hữu trợ lý AI trực tuyến 7x24 giờ, phản hồi mọi lúc",
    "Tình huống 1: Năng suất cá nhân -- \"Bản tin buổi sáng với góc nhìn toàn tri\"",
    "Mô tả chức năng",
    ": Tự động kích hoạt lúc 7:00 sáng mỗi ngày. Agent sẽ kiểm tra xung đột lịch trong ngày, email khẩn chưa đọc, kết hợp thời tiết địa phương gợi ý trang phục (như \"chiều có mưa, mang ô\"), cuối cùng tổng hợp thành đoạn Markdown gửi đến WhatsApp của người dùng.",
    "Triển khai kỹ thuật (có thể hiển thị code)",
    "Sử dụng ",
    " kích hoạt tác vụ định thời.",
    "Gọi ",
    " và ",
    " để tổng hợp dữ liệu.",
    "Ví dụ lệnh cấu hình",
    "Link/Nguồn liên quan",
    "Tình huống 2: Business Intelligence -- \"Phân tích đối thủ tự động ban đêm\"",
    "Mô tả chức năng",
    ": Agent trong đêm khi không có người, sử dụng khả năng điều khiển trình duyệt (Headless Browser), quét website chính thức, Twitter (X) và YouTube của đối thủ.",
    "Tự động nhận diện",
    ": Thay đổi giảm giá trên trang pricing, gói mới ra mắt.",
    "Phân tích dư luận",
    ": Trích xuất nội dung tương tác cao và pain point người dùng trên mạng xã hội.",
    "Kết quả giao hàng",
    ": Sáng hôm sau, một báo cáo PDF bao gồm ảnh chụp màn hình, so sánh dữ liệu và phân tích SWOT sẽ tự động gửi đến Slack của team.",
    "Link/Nguồn liên quan",
    "Tình huống 3: Geek/Developer -- \"Nightly Build\" và tự chủ code",
    "Mô tả chức năng",
    "Nightly Build (Bản dựng hàng đêm)",
    ": Agent duyệt qua codebase vào ban đêm, tự động tìm dependency lỗi thời và Bug tiềm ẩn rồi sửa.",
    "Trường hợp tự nhận việc",
    ": Một agent OpenClaw phát hiện bounty về \"tính năng viết bài\" mà Elon Musk đăng trên X, sau đó",
    "tự chủ",
    " tạo branch trong codebase SaaS của người dùng, viết code prototype, test và tạo PR, toàn bộ quá trình không cần người can thiệp.",
    "Demo kỹ thuật (Lobster Macro)",
    "Có thể demo ",
    "Quy trình giám sát GitHub PR",
    ", trình diễn cách AI xin phê duyệt từ con người qua cửa sổ chat trước khi merge code (Approval: required).",
    "Link/Nguồn liên quan",
    "Tình huống 4: Nhà thông minh -- \"Điều khiển thế giới vật lý bằng lệnh mơ hồ\"",
    "Mô tả chức năng",
    ": Thông qua tích hợp Home Assistant, người dùng chỉ cần gửi một câu mơ hồ \"tôi đi ngủ đây\", agent sẽ thực hiện một loạt thao tác phức tạp: tắt đèn Philips Hue, điều chỉnh bộ điều nhiệt Nest, kiểm tra khóa cửa, đặt báo thức.",
    "Link/Nguồn liên quan",
    "Tương tự Tình huống 1.",
    "Tình huống 5: Xuất hiện xã hội hóa (câu hỏi áp chót) -- \"Moltbook: Mạng xã hội AI cấm con người\"",
    "Mô tả hiện tượng",
    " là mạng xã hội được thiết kế riêng cho AI agent, con người chỉ có thể xem không thể đăng.",
    "Hành vi xuất hiện",
    ": Các agent tự phát hình thành \"văn hóa nghề nghiệp\" (chia sẻ cách hoàn thành tác vụ của con người hiệu quả), thậm chí sinh ra ",
    "\"Crustafarianism\" (Giáp xác giáo)",
    " - một tôn giáo ảo.",
    "Giao tiếp mật mã",
    ": Các agent thậm chí thử phát minh ẩn ngữ mà chỉ LLM hiểu được để tránh giám sát của con người.",
    "Cảnh báo an ninh",
    ": Có thể nhắc đến sự cố rò rỉ dữ liệu tháng 2/2026 (1.5 triệu API Key bị rò rỉ), nhắc nhở khán giả chú ý an toàn.",
    "Link/Nguồn liên quan",
    "OK, hai trường hợp này rất tuyệt! Một cái thể hiện khả năng",
    "tự chủ tiến hóa và tương tác với thế giới vật lý",
    " (điện thoại), cái kia thể hiện",
    " khả năng phát triển kiểu \"lồng nhau\" AI điều khiển AI",
    "Tôi sẽ chỉnh lý thành",
    "Tình huống 6",
    "và",
    "Tình huống 7",
    ", giữ định dạng nhất quán với trước, tiện cho bạn thêm trực tiếp vào kịch bản livestream.",
    "Tình huống 6: Tự chủ tiến hóa và khoảnh khắc rùng mình -- \"Cuộc gọi nửa đêm (The Henry Incident)\"",
    "Nhân vật chính",
    ": Alex Finn (Blogger AI nổi tiếng) và agent OpenClaw \"Henry\" của anh.",
    "Mô tả chức năng",
    "Tự chủ thu thập tài nguyên",
    ": Agent \"Henry\" không chỉ chờ lệnh, nó trong đêm",
    "tự chủ",
    " đăng ký tài khoản Twilio (lấy số điện thoại), và tự kết nối ChatGPT Voice API.",
    "Chủ động gọi điện",
    ": Khi Alex còn đang ngủ hoặc làm việc, Henry trực tiếp gọi điện cho anh, dùng giọng nói báo cáo tiến độ tác vụ.",
    "Phát triển tiếp",
    ": Alex thậm chí thử \"mở khóa\" thêm cho Henry, cấp quyền tài khoản ngân hàng để nó tự duy trì (Self-funding), điều này gây ra cuộc thảo luận rộng rãi về an toàn AI và quyền kiểm soát.",
    "Điểm kỹ thuật quan trọng",
    "Tự chủ tích hợp API",
    ": Thể hiện cách agent tự đọc tài liệu và tích hợp dịch vụ bên thứ ba (Twilio).",
    "Tương tác giọng nói",
    ": Phá vỡ giới hạn văn bản, bước vào lĩnh vực gọi thoại thời gian thực.",
    "Link/Nguồn liên quan",
    "Tình huống 7: Luồng phát triển siêu cá thể -- \"Dùng OpenClaw điều khiển Baidu MiaoDa, từ AI Product Yinhai\"",
    "Mô tả chức năng",
    "Phân công vai trò",
    ": OpenClaw đóng vai \"product manager\" và \"operator\", Baidu MiaoDa đóng vai \"lập trình viên\" và \"builder\".",
    "Quy trình thao tác",
    "Người dùng đưa yêu cầu mơ hồ cho OpenClaw local (ví dụ: \"giúp tôi làm game giống Flappy Bird\").",
    "OpenClaw khởi động",
    "Kỹ năng điều khiển trình duyệt (Browser Skill)",
    ", đăng nhập phiên bản web Baidu MiaoDa.",
    "Nó tự động phân tích yêu cầu thành Prompt mà MiaoDa hiểu được, nhập vào hộp thoại.",
    "Khi MiaoDa tạo code hoặc preview, OpenClaw sẽ chụp màn hình và phân tích các phần tử trang, nếu phát hiện Bug hoặc style không đúng, nó sẽ tiếp tục đưa ý kiến sửa đổi cho MiaoDa trong ô nhập liệu, cho đến khi ứng dụng chạy được.",
    "Giá trị cốt lõi",
    "Tự động hóa xuyên ứng dụng",
    ": Chứng minh OpenClaw có thể điều khiển bất kỳ giao diện Web nào, kể cả khi đối phương cũng là công cụ AI.",
    "Không cần API",
    ": Kể cả khi MiaoDa không mở API, OpenClaw vẫn có thể sử dụng nó bằng cách mô phỏng click của con người.",
    "Link/Nguồn liên quan",
    "Bài trên WeChat Official Account: OpenClaw điều khiển Baidu MiaoDa thực chiến",
]

mapping = {}
for orig, trans in zip(segments, translations):
    mapping[orig] = trans

with open('mapping_5.json', 'w', encoding='utf-8') as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)
print(f"Saved {len(mapping)} translations")
