# -*- coding: utf-8 -*-
import json, sys
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')

mapping = {
    "自然环境下部署 OpenClaw & 畅享 Codex 5.3 新手保姆级教程": "Hướng dẫn chi tiết cho người mới: Triển khai OpenClaw & Tận hưởng Codex 5.3 trong môi trường tự nhiên",
    "🔗 原文链接： ": "🔗 Link bài gốc: ",
    "原创 赛博进化手记2077 赛博进化手记2077 赛博进化手记2077": "Nguyên bản: Nhật ký tiến hóa Cyber 2077 Nhật ký tiến hóa Cyber 2077 Nhật ký tiến hóa Cyber 2077",
    "2026年3月10日 10:51  安徽": "Ngày 10 tháng 3 năm 2026 10:51  An Huy",
    "有很多小伙伴私信问：怎么在\u201c海鲜市场\u201d上买 GPT 的 Team 账号？如何才能享受一个月10块钱的\u201c小龙虾 (OpenClaw) + Codex \u201d的服务？所以专门写了一篇稿子，说一说我的经验。": "Có rất nhiều bạn nhắn tin hỏi: Làm sao mua tài khoản Team GPT trên \u201cchợ hải sản\u201d? Làm sao để tận hưởng dịch vụ \u201ctôm hùm (OpenClaw) + Codex\u201d chỉ 10 tệ/tháng? Vì vậy mình viết riêng một bài để chia sẻ kinh nghiệm.",
    "首先，要明白一件事情，在这里最复杂的其实不是弄到 Team 或者是 ChatGPT 的账号，而是 ": "Trước hết, cần hiểu một điều, ở đây phần phức tạp nhất thực ra không phải là lấy tài khoản Team hay ChatGPT, mà là ",
    "如何才能在自然环境下流畅地使用你想要的模型 ": "làm sao để sử dụng mượt mà model bạn muốn trong môi trường tự nhiên ",
    "。（优先推荐 ChatGPT，毕竟小龙虾之父现在就是 OpenAI 的人）": ". (Ưu tiên khuyên dùng ChatGPT, vì cha đẻ của tôm hùm hiện đang là người của OpenAI)",
    "课前准备：我们需要什么？": "Chuẩn bị trước: Chúng ta cần gì?",
    "在此之前，让我们先弄清楚，想要做到直接使用\u201c小龙虾 + GPT 5.4\u201d，需要做哪些准备：": "Trước đó, hãy cùng tìm hiểu, để sử dụng trực tiếp \u201ctôm hùm + GPT 5.4\u201d, cần chuẩn bị những gì:",
    "加入 Team 的 ChatGPT 账号": "Tài khoản ChatGPT đã tham gia Team",
    "VPS 服务器": "Máy chủ VPS",
    "以上两个都可以在\u201c海鲜市场\u201d获取。具体如何搜索获取就只能开动脑筋了。": "Cả hai thứ trên đều có thể lấy được trên \u201cchợ hải sản\u201d. Cách tìm kiếm cụ thể thì phải tự suy nghĩ nhé.",
    "关于 Team 账号 ": "Về tài khoản Team ",
    "：一般加入别人 Team 的价格在 10 块钱左右/月，超过 15 块的建议换家店。这里的 Team 账号就是有一个号主，他把自己的账号开通 Team 座位，然后把你拉到他的 Team 里。理论上你们的对话记录是彼此隔离的，互不干扰。": ": Thông thường giá tham gia Team của người khác khoảng 10 tệ/tháng, nếu quá 15 tệ thì nên đổi cửa hàng. Tài khoản Team ở đây nghĩa là có một chủ tài khoản, họ mở chỗ ngồi Team trên tài khoản của mình, rồi kéo bạn vào Team. Về lý thuyết, lịch sử trò chuyện của các bạn được cách ly với nhau, không ảnh hưởng lẫn nhau.",
    "新手避坑提示 ": "Mẹo tránh bẫy cho người mới ",
    "：建议 ": ": Khuyến nghị ",
    "不要 ": "không nên ",
    "用自己的 ChatGPT 主账号去申请加入 Team，而是用小号。我自己是用 Google 的小号注册了 ChatGPT 的账号，然后再提交的 Team 申请，这样更安全。": "dùng tài khoản ChatGPT chính của mình để đăng ký tham gia Team, mà hãy dùng tài khoản phụ. Bản thân mình dùng tài khoản phụ Google để đăng ký tài khoản ChatGPT, sau đó mới gửi yêu cầu tham gia Team, như vậy an toàn hơn.",
    "关于 VPS 服务器 ": "Về máy chủ VPS ",
    "：建议购买海外云服务器（如阿里云海外节点等），可以选择离大陆较近的节点（例如香港、新加坡等），延迟更低。": ": Khuyến nghị mua máy chủ cloud nước ngoài (như node nước ngoài của Alibaba Cloud, v.v.), có thể chọn node gần Trung Quốc đại lục (ví dụ Hong Kong, Singapore, v.v.), độ trễ sẽ thấp hơn.",
    "第一步：连上服务器 & 安装宝塔面板": "Bước 1: Kết nối máy chủ & Cài đặt BT Panel (Bảo tháp)",
    "背景交代清楚了，我们正式开始！首先我们要连上刚才买的 VPS 服务器，并安装宝塔面板。": "Đã giải thích xong bối cảnh, chúng ta chính thức bắt đầu! Đầu tiên cần kết nối tới máy chủ VPS vừa mua, và cài đặt BT Panel.",
    "从店家那里拿到的服务器信息一般是： ": "Thông tin máy chủ lấy từ cửa hàng thường là: ",
    "IP地址 + 用户名（通常是 root）+ 密码 ": "Địa chỉ IP + Tên người dùng (thường là root) + Mật khẩu ",
    "1. SSH 登录服务器": "1. Đăng nhập máy chủ bằng SSH",
    "打开你电脑自带的\u201c终端\u201d（Mac）或\u201c命令提示符/PowerShell\u201d（Windows），使用 SSH 登录：": "Mở \u201cTerminal\u201d có sẵn trên máy tính (Mac) hoặc \u201cCommand Prompt/PowerShell\u201d (Windows), đăng nhập bằng SSH:",
    "接着会提示输入密码。 ": "Tiếp theo sẽ yêu cầu nhập mật khẩu. ",
    "注意：在终端里输入的密码是不显示的 ": "Lưu ý: Mật khẩu nhập trong terminal sẽ không hiển thị ",
    "，不要以为没输进去！": ", đừng tưởng là chưa nhập vào nhé!",
    "建议直接复制密码，按鼠标右键或者 ": "Khuyến nghị copy mật khẩu trực tiếp, nhấn chuột phải hoặc ",
    " 粘贴，然后回车。": " để dán, rồi nhấn Enter.",
    "这里可能会提示你没有指纹，问你要不要继续登录，输入 ": "Ở đây có thể sẽ thông báo bạn chưa có fingerprint, hỏi bạn có muốn tiếp tục đăng nhập không, nhập ",
    "，回车": ", nhấn Enter",
    "当你发现终端最后面的提示符变成 ": "Khi bạn thấy dấu nhắc ở cuối terminal chuyển thành ",
    " 的时候，就意味着连上了。": " thì có nghĩa là đã kết nối thành công.",
    "就像这样： ": "Giống như thế này: ",
    "2. 安装宝塔面板（非必要，但推荐新手安装）": "2. Cài đặt BT Panel (không bắt buộc, nhưng khuyến nghị cho người mới)",
    "为什么推荐安装宝塔面板？因为我们需要一个图形化的界面去直观监测服务器的运行情况。老手可以跳过这一步，直接进入第二步环境配置。": "Tại sao khuyến nghị cài BT Panel? Vì chúng ta cần một giao diện đồ họa để theo dõi trực quan tình trạng hoạt động của máy chủ. Người có kinh nghiệm có thể bỏ qua bước này, đi thẳng tới Bước 2 cấu hình môi trường.",
    "在终端中输入以下安装宝塔面板的命令并回车：": "Nhập lệnh cài đặt BT Panel sau vào terminal và nhấn Enter:",
    "期间会提示你要不要安装，输入 ": "Trong quá trình sẽ hỏi bạn có muốn cài đặt không, nhập ",
    " 然后回车。 宝塔面板的安装时间大概是 5-8 分钟。安装完成后，终端会显示 ": " rồi nhấn Enter. Thời gian cài đặt BT Panel khoảng 5-8 phút. Sau khi cài xong, terminal sẽ hiển thị ",
    "宝塔运行的网址、用户名和密码 ": "URL chạy BT Panel, tên người dùng và mật khẩu ",
    "强烈建议 ": "Rất khuyến nghị ",
    "：用一个 txt 文本把这段网址、账号和密码记下来，或者发给自己的微信\u201c文件传输助手\u201d。": ": Dùng một file txt ghi lại URL, tài khoản và mật khẩu này, hoặc gửi cho chính mình qua \u201cTrợ lý truyền file\u201d của WeChat.",
    "3. 登录宝塔面板": "3. Đăng nhập BT Panel",
    "在本地电脑的浏览器中，会询问是否同意进入宝塔面板，点同意，然后输入刚才保存的宝塔网址，粘贴用户名和密码登录。": "Trên trình duyệt của máy tính local, sẽ hỏi có đồng ý vào BT Panel không, nhấn đồng ý, sau đó nhập URL BT Panel vừa lưu, dán tên người dùng và mật khẩu để đăng nhập.",
    "第一次进入宝塔面板，会提示是否要一键初始化安装推荐配置环境。如果你的服务器像我一样是配置较低的\u201c弱机\u201d， ": "Lần đầu vào BT Panel, sẽ hỏi có muốn khởi tạo và cài đặt cấu hình môi trường khuyến nghị bằng một click không. Nếu máy chủ của bạn giống mình là \u201cmáy yếu\u201d cấu hình thấp, ",
    "暂时先不装 ": "tạm thời chưa cài ",
    "，直接关掉弹窗。": ", đóng popup trực tiếp.",
    "第二步：配置环境 (Homebrew 与 Node.js)": "Bước 2: Cấu hình môi trường (Homebrew và Node.js)",
    "接下来我们要给服务器安装 OpenClaw 所需的基础环境。回到刚才连接着服务器的终端。": "Tiếp theo chúng ta cần cài đặt môi trường cơ bản mà OpenClaw yêu cầu cho máy chủ. Quay lại terminal đang kết nối tới máy chủ.",
    "1. 尝试安装 Homebrew 与新建用户": "1. Thử cài đặt Homebrew và tạo user mới",
    "简介：Homebrew 是 macOS 和 Linux 上缺失的软件包管理器，能让我们极其方便地安装各种依赖。": "Giới thiệu: Homebrew là trình quản lý gói phần mềm còn thiếu trên macOS và Linux, cho phép chúng ta cài đặt các dependency cực kỳ tiện lợi.",
    "（这里有几张图忘了截了，但按照步骤来应该问题不大orz）": "(Ở đây có mấy hình quên chụp, nhưng làm theo các bước thì không vấn đề gì lớn orz)",
    "首先我们需要安装 Homebrew。 ": "Đầu tiên chúng ta cần cài đặt Homebrew. ",
    "但是，当你尝试安装时 ": "Nhưng khi bạn thử cài đặt ",
    "，系统会提示当前是 root 用户，而 Homebrew 的安装脚本不允许直接以 root 用户运行。": ", hệ thống sẽ thông báo hiện tại đang là user root, mà script cài đặt Homebrew không cho phép chạy trực tiếp bằng user root.",
    "没关系，我们新建一个普通用户，这里叫它 ": "Không sao, chúng ta tạo một user thường, ở đây gọi nó là ",
    "中间会让你设置密码（输入密码的时候你看不到，建议用简单一点的密码，后期也能改），剩下的几个选项直接一直回车确认即可。": "Giữa chừng sẽ yêu cầu bạn đặt mật khẩu (khi nhập mật khẩu sẽ không hiển thị, khuyến nghị dùng mật khẩu đơn giản, sau này có thể đổi), các tùy chọn còn lại cứ nhấn Enter xác nhận là được.",
    "接着，把 ": "Tiếp theo, thêm ",
    " 用户加入 ": " user vào nhóm ",
    " （管理员权限）组：": " (quyền quản trị viên):",
    "然后切换到这个小龙虾账号下：": "Sau đó chuyển sang tài khoản tôm hùm này:",
    "2. 正式安装与配置 Homebrew 环境变量": "2. Chính thức cài đặt và cấu hình biến môi trường Homebrew",
    "在当前 ": "Trong user ",
    " 用户下，正式运行 Homebrew 的安装命令（按照系统提示操作）：": " hiện tại, chính thức chạy lệnh cài đặt Homebrew (làm theo hướng dẫn của hệ thống):",
    "安装完成后，终端会显示安装成功，但提示 ": "Sau khi cài xong, terminal sẽ hiển thị cài đặt thành công, nhưng thông báo ",
    "还没有被添加到你的环境变量（PATH）中 ": "chưa được thêm vào biến môi trường (PATH) của bạn ",
    "。系统还不知道 ": ". Hệ thống vẫn chưa biết ",
    " 命令在哪里。 依次运行以下两条命令把它加进去并让其立即生效：": " lệnh ở đâu. Chạy lần lượt hai lệnh sau để thêm nó vào và có hiệu lực ngay:",
    "好的，生效了。我们来验证一下，输入 ": "OK, đã có hiệu lực. Hãy kiểm tra lại, nhập ",
    " 。 如果提示类似 ": ". Nếu thông báo tương tự ",
    " ，说明 Homebrew 已经安装并完成配置！": ", có nghĩa là Homebrew đã được cài đặt và cấu hình xong!",
    "3. 安装 Node.js": "3. Cài đặt Node.js",
    "有了 Homebrew 环境，安装 Node.js 就简单多了。 输入：": "Đã có môi trường Homebrew, cài đặt Node.js đơn giản hơn nhiều. Nhập:",
    "（⚠️ 注意：代码前后面不要有空格，我第一次安装就因此失败了。）": "(⚠️ Lưu ý: Không để khoảng trắng trước và sau code, lần đầu mình cài đã bị lỗi vì điều này.)",
    "好的，到这里 Node.js 也安装成功了。那么，剩下的是不是直接安装 OpenClaw 就行了？ ": "OK, đến đây Node.js cũng đã cài đặt thành công. Vậy còn lại chỉ cần cài trực tiếp OpenClaw là xong? ",
    "并没有这么简单！": "Không đơn giản như vậy đâu!",
    "第三步：安装 VPS 远程桌面": "Bước 3: Cài đặt Remote Desktop cho VPS",
    "如果你的网络环境是通畅的，此时确实可以直接安装 OpenClaw 了。 但我默认你使用的是 ": "Nếu môi trường mạng của bạn thông suốt, lúc này thực sự có thể cài trực tiếp OpenClaw. Nhưng mình mặc định bạn đang sử dụng ",
    "自然环境 ": "môi trường tự nhiên ",
    "。那么，有一关就横亘在这一步之前—— ": ". Vậy thì, có một rào cản nằm trước bước này—— ",
    "Codex 的 Auth（授权）认证 ": "Xác thực Auth (ủy quyền) của Codex ",
    "一般来说，在安装 OpenClaw 时，会需要认证服务商。此时，如果你选择了 ": "Thông thường, khi cài đặt OpenClaw, sẽ cần xác thực nhà cung cấp dịch vụ. Lúc này, nếu bạn chọn ",
    " 认证，会要求你填回环地址（Callback URL）。但这个地址如果你本地的电脑无法打开 ChatGPT，是无法完成回调并获取该地址的，而且这里已经被官方写死了。": " xác thực, sẽ yêu cầu bạn điền địa chỉ callback (Callback URL). Nhưng địa chỉ này nếu máy tính local của bạn không thể mở ChatGPT, thì không thể hoàn thành callback và lấy được địa chỉ này, hơn nữa phần này đã bị phía chính thức cố định rồi.",
    "所以我们就要另辟蹊径。": "Vì vậy chúng ta phải tìm cách khác.",
    "好了，我们另辟蹊径的方式就是： ": "OK, cách khác của chúng ta là: ",
    "用 VPS 搭建远程桌面，在服务器上打开浏览器完成认证！": "Dùng VPS dựng remote desktop, mở trình duyệt trên máy chủ để hoàn thành xác thực!",
    "1. 在 VPS 上安装轻量桌面": "1. Cài đặt desktop nhẹ trên VPS",
    "（这里又忘截图了，但按照步骤来应该问题不大，滑跪orz） ": "(Ở đây lại quên chụp hình, nhưng làm theo các bước thì không vấn đề gì lớn, xin lỗi orz) ",
    "先回到服务器的终端，把下面这整段命令复制进去执行：": "Trước tiên quay lại terminal máy chủ, copy toàn bộ đoạn lệnh sau vào để thực thi:",
    "这一步做的事是用来安装：": "Bước này dùng để cài đặt:",
    " ：轻量桌面环境": " : Môi trường desktop nhẹ",
    " ：让你能从 Mac 或 Windows 远程连接进这个服务器桌面": " : Cho phép bạn kết nối từ xa từ Mac hoặc Windows vào desktop máy chủ này",
    " ：轻量浏览器，一会用来打开 OpenAI 登录页": " : Trình duyệt nhẹ, lát nữa dùng để mở trang đăng nhập OpenAI",
    "2. 确认远程桌面服务起来了": "2. Xác nhận dịch vụ remote desktop đã khởi động",
    "执行这两条命令检查状态：": "Chạy hai lệnh sau để kiểm tra trạng thái:",
    "你需要关注的重点是，第二条命令输出里有类似 ": "Điều bạn cần chú ý là, trong output của lệnh thứ hai có dạng tương tự ",
    " 或者 ": " hoặc ",
    " 。如果有，就说明远程桌面服务已经在正常监听了。": ". Nếu có, nghĩa là dịch vụ remote desktop đã đang lắng nghe bình thường.",
    "3. 在本地电脑安装\u201c微软远程桌面\u201d": "3. Cài \u201cMicrosoft Remote Desktop\u201d trên máy tính local",
    "如果你本地的 Mac 电脑上有 Homebrew 环境，那就非常简单了，直接在 ": "Nếu máy Mac local của bạn đã có môi trường Homebrew, thì rất đơn giản, trực tiếp trên ",
    "本地电脑的终端 ": "terminal máy tính local ",
    "执行：": "chạy lệnh:",
    "如果没有也没关系，直接去 App Store 下载安装 ": "Nếu không có cũng không sao, trực tiếp vào App Store tải và cài ",
    " ，流程省略，一路\u201c下一步\u201d就行。": ", bỏ qua các bước, cứ nhấn \u201cNext\u201d là được.",
    "好了，安装完成后我们打开它：": "OK, sau khi cài xong chúng ta mở nó lên:",
    "会问我们要不要更好的用户体验，点 ": "Sẽ hỏi chúng ta có muốn trải nghiệm người dùng tốt hơn không, nhấn ",
    " 2.点 击上方 的  ": " 2. Nhấn vào dấu ",
    "  加号，选择添加电脑  ( ": "  cộng ở phía trên, chọn thêm máy tính ( ",
    " 3.其他的都不要动，只要把VPS 服务器 IP 地址 填到电脑名称里（如果有端口需求填 ": " 3. Không cần thay đổi gì khác, chỉ cần điền địa chỉ IP máy chủ VPS vào tên máy tính (nếu cần port thì điền ",
    "4.点击添加 ( ": "4. Nhấn thêm ( ",
    " )，然后双击卡片连上去。 好的，成功连上了我们服务器的桌面了！": " ), sau đó double-click vào thẻ để kết nối. OK, đã kết nối thành công tới desktop máy chủ!",
    "5.双击刚在添加的那个电脑，也就是上面出现的小屏幕，输入我们在\u201c配置环境 (Homebrew 与 Node.js)\u201d这里添加的用户名（比如xiaolongxia）和密码": "5. Double-click vào máy tính vừa thêm, tức là màn hình nhỏ xuất hiện ở trên, nhập tên người dùng (ví dụ xiaolongxia) và mật khẩu mà chúng ta đã tạo ở phần \u201cCấu hình môi trường (Homebrew và Node.js)\u201d",
    "6.在短暂的黑屏之后就会来到远程vps的桌面": "6. Sau một khoảng màn hình đen ngắn sẽ đến desktop VPS từ xa",
    "第四步：登录账号与安装 OpenClaw": "Bước 4: Đăng nhập tài khoản và cài đặt OpenClaw",
    "1. 在服务器的浏览器中登录 Google/ChatGPT": "1. Đăng nhập Google/ChatGPT trên trình duyệt máy chủ",
    "首先在这里 ": "Trước hết ở đây ",
    "先不要急着在远程服务器的终端里安装 OpenClaw ": "đừng vội cài đặt OpenClaw trong terminal máy chủ từ xa ",
    "我们要先登录你用来验证 ChatGPT 的账号（我用的是 Google 小号）。": "Chúng ta cần đăng nhập tài khoản dùng để xác thực ChatGPT trước (mình dùng tài khoản phụ Google).",
    "点开桌面上的浏览器（Epiphany Browser），直接在地址栏输入Google和 ChatGPT 登录 Google 和 ChatGPT。": "Mở trình duyệt trên desktop (Epiphany Browser), nhập trực tiếp vào thanh địa chỉ để đăng nhập Google và ChatGPT.",
    "个人信息实在是太多，就不贴截图了。网页登录都不会的话，那我也只能摊摊手了 🤷\u200d♂️ ": "Thông tin cá nhân quá nhiều nên không đăng ảnh chụp màn hình. Nếu đăng nhập web cũng không biết thì mình cũng chịu thôi 🤷\u200d♂️ ",
    "确认你的 Team 账号已经成功登录之后 ": "Sau khi xác nhận tài khoản Team của bạn đã đăng nhập thành công ",
    "，我们开搞下一步。": ", chúng ta bắt đầu bước tiếp theo.",
    "2. 终于可以安装 OpenClaw 了": "2. Cuối cùng cũng có thể cài đặt OpenClaw rồi",
    "在远程服务器桌面里打开一个终端界面（Terminal Emulator）": "Mở một cửa sổ terminal (Terminal Emulator) trong desktop máy chủ từ xa",
    "验证之前步骤都很简单， 相信大家都看烂了，就是提醒你 OpenClaw 是实验性软件，会访问你的文件和网络，问你是否了解风险，然后用键盘上的箭头选择  Yes ，按回车继续。以及选择是 要 QuickStart（快速开始）还是自定义安装。": "Các bước trước xác thực rất đơn giản, chắc mọi người đã quen thuộc rồi, chỉ là nhắc bạn OpenClaw là phần mềm thử nghiệm, sẽ truy cập file và mạng của bạn, hỏi bạn có hiểu rủi ro không, rồi dùng phím mũi tên trên bàn phím chọn Yes, nhấn Enter để tiếp tục. Và chọn muốn QuickStart (bắt đầu nhanh) hay cài đặt tùy chỉnh.",
    "好了，要验证了": "OK, đến bước xác thực rồi",
    "🔥 重点来了：": "🔥 Điểm quan trọng:",
    "到了验证环节，选择第一个 ": "Đến bước xác thực, chọn cái đầu tiên ",
    " 验证。": " xác thực.",
    "这里会直接弹开我们刚才在 VPS 上打开的浏览器，请按照正常程序验证登录。": "Ở đây sẽ tự động mở trình duyệt chúng ta vừa mở trên VPS, hãy xác thực đăng nhập theo quy trình bình thường.",
    "因为我们之前已经完成了 Google/ChatGPT的登录，这里会非常顺利，当认证完成时，你的 VPS 网页会提示验证已经完成（Success）。": "Vì trước đó chúng ta đã hoàn thành đăng nhập Google/ChatGPT, nên ở đây sẽ rất thuận lợi, khi xác thực hoàn thành, trang web VPS của bạn sẽ thông báo xác thực đã hoàn thành (Success).",
    "千万别关掉网页 ": "Tuyệt đối đừng đóng trang web ",
    "！到浏览器地址栏，把最新的那一长串链接（这就是回环地址）完整复制下来。": "! Vào thanh địa chỉ trình duyệt, copy toàn bộ chuỗi link dài nhất (đây chính là địa chỉ callback) ra.",
    "然后回到 VPS 上的安装终端，把它粘贴到要求输入链接的位置，回车！": "Sau đó quay lại terminal cài đặt trên VPS, dán nó vào vị trí yêu cầu nhập link, nhấn Enter!",
    "这里是图片步骤：": "Đây là các bước theo hình ảnh:",
    "图片步骤1: ": "Bước hình ảnh 1: ",
    "首先是等待弹出openai的验证网页，如果没有弹出的话点击截图中的网址。": "Đầu tiên là chờ trang xác thực OpenAI bật lên, nếu không bật lên thì nhấn vào URL trong hình chụp.",
    "图片步骤2:": "Bước hình ảnh 2:",
    "在远程桌面的浏览器中复制用来验证的回环地址": "Copy địa chỉ callback dùng để xác thực trong trình duyệt remote desktop",
    "图片步骤3:": "Bước hình ảnh 3:",
    "然后，你就会看到： ": "Sau đó, bạn sẽ thấy: ",
    "验证成功了。 ": "Xác thực thành công. ",
    "剩下的就非常简单了，一路敲回车默认设置，反正到后来可以自己改。": "Phần còn lại rất đơn giản, cứ nhấn Enter mặc định, dù sao sau này có thể tự thay đổi.",
    "搞定！测试运行": "Xong! Chạy thử",
    "安装成功后，我们可以先退出 Remote 的远程桌面界面，关掉它。 回到最初宝塔的那个终端，输入命令进入界面：": "Sau khi cài đặt thành công, chúng ta có thể thoát giao diện Remote Desktop trước, đóng nó đi. Quay lại terminal BT Panel ban đầu, nhập lệnh để vào giao diện:",
    "（如果提示 openclaw: command not found 的话，那大概率是没有在xiaolongxia的账户下运行，输入su - xiaolongxia）": "(Nếu thông báo openclaw: command not found, thì khả năng cao là không chạy trong tài khoản xiaolongxia, nhập su - xiaolongxia)",
    "切换到xiaolongxia的登录，然后再输入命令进入界面，就像下面这样": "Chuyển sang đăng nhập xiaolongxia, rồi nhập lại lệnh để vào giao diện, giống như thế này",
    "如然后在终端控制台里问它一句：\u201c你是什么模型驱动的？\u201d 如果它的答复正常回复了你。": "Sau đó hỏi nó một câu trong console terminal: \u201cBạn được điều khiển bởi model nào?\u201d Nếu nó trả lời bạn bình thường.",
    "至此，我们的小龙虾 (OpenClaw) 安装成功！ 全程都是借助自然环境，没有在服务器上做额外复杂的网络代理配置。": "Đến đây, tôm hùm (OpenClaw) của chúng ta đã cài đặt thành công! Toàn bộ quá trình đều dựa vào môi trường tự nhiên, không cần cấu hình proxy mạng phức tạp thêm trên máy chủ.",
    "下一步，就可以让小龙虾连飞书、QQ什么的了，这期教程暂时告一段落！": "Bước tiếp theo, có thể cho tôm hùm kết nối Lark, QQ, v.v., bài hướng dẫn kỳ này tạm kết thúc tại đây!",
    "。": "."
}

with open("mapping_1.json", "w", encoding="utf-8") as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)
print(f"Saved {len(mapping)} translations")
