# -*- coding: utf-8 -*-
import json, sys
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')

with open('segs_7.json', 'r', encoding='utf-8') as f:
    segs = json.load(f)

t = [
"Nham Phong: OpenClaw Khải Thị Lục: Tiêm \"linh hồn\" vào \"thể xác\" nhà thông minh",
"Các bạn cũng có thể thông qua Alibaba Cloud Bailian",
" để triển khai",
"Mua lần đầu chỉ từ 7.9 tệ, gia hạn giảm 50%, hỗ trợ các model Qwen3.5, Qwen3-max, Qwen3-coder, GLM-5, GLM-4.7, Kimi-k2.5, v.v.",
"👉Nhấn link truy cập trực tiếp:",
"👉Xem hướng dẫn triển khai chi tiết:",
"Chỉ cần tối đa ba bước, là có thể sở hữu trợ lý AI trực tuyến 7x24 giờ, phản hồi mọi lúc",
"1. Nguồn cảm hứng bất ngờ từ OpenClaw",
"Nói thật, sau khi xem các cách chơi đa dạng của cộng đồng mạng với OpenClaw, tôi không quá hứng thú. Vì tôi thực sự không có nhu cầu cấp thiết với một \"trợ lý văn phòng\" On Call 24 giờ. Nhưng vì tò mò kỹ thuật với dự án đang hot này, tôi vẫn nghiên cứu kỹ nguyên lý của nó.",
"Nhưng khi tôi đi sâu vào ba cơ chế cốt lõi của nó, tôi bị chấn động sâu sắc:",
"Cơ chế nhịp tim (Heartbeat)",
": Nó không chỉ là \"đồng hồ báo thức\" định thời, mà là cho Agent chủ động \"thức dậy\" vài phút một lần, đọc trạng thái hiện tại và ghi chú. Điều này phá vỡ thế bị động \"ngồi chờ kích hoạt\" của tự động hóa truyền thống, thực hiện ",
"cảm nhận chủ động",
"Bộ nhớ vĩnh cửu (Memory)",
": OpenClaw không chỉ có context tạm thời, mà còn có hệ thống file Markdown hoàn chỉnh (như ",
"). Nó ghi lại cuộc trò chuyện, thói quen thậm chí cảm xúc lúc đó của người dùng, tích lũy thành bộ nhớ dài hạn. Điều này nghĩa là AI không còn nhớ như cá vàng, mà có thể",
"càng dùng càng hiểu bạn như bạn cũ",
"Tự lặp lại (Self-Iteration)",
": Đây là điểm \"bùng nổ\" nhất. Agent được ủy quyền sửa đổi prompt và danh sách tác vụ của chính mình. Khi phát hiện thói quen mới của bạn, nó có thể tự viết lại logic vận hành để thích nghi. Đây không phải cấu hình thủ công, đây là",
"tự tiến hóa hệ thống",
"Là người khám phá lĩnh vực AI + Nhà thông minh, tôi bỗng nhận ra:",
"Tại sao trước đây chúng ta mãi không vượt qua được nút thắt thông minh.",
"2. Nhà thông minh hiện tại chỉ là \"công tắc hẹn giờ\" bản cao cấp",
"Tại sao chúng ta đã có Home Assistant (HA), Mi Home và các nền tảng nhà thông minh mạnh mẽ, nhưng vẫn cảm thấy nhà chưa đủ thông minh?",
"Nguyên nhân là: chúng ta cố dùng",
"quy tắc rời rạc",
"để bao quát",
"cuộc sống liên tục",
". Đây chắc chắn là trận chiến thua cuộc,",
"vì bạn không bao giờ có thể nhét tâm trạng và tình huống biến hóa khôn lường vào vài dòng code If-Else cố định.",
"Trong các nền tảng này, cái gọi là \"thông minh\" bản chất là viết logic cứng nhắc:",
"\"Nếu 18:00, và có người, thì bật đèn.\"",
"Nhưng điều này thực sự thông minh sao? Hãy xem",
"quy tắc điều khiển",
"bất lực thế nào trước cuộc sống thực:",
"Tình huống 1: Chế độ \"về nhà\" lúng túng",
"Quy tắc",
": Phát hiện khóa cửa mở -> Phát playlist về nhà + Bật toàn bộ đèn.",
"Hiện thực",
": Hôm nay bạn thất tình, hoặc vừa từ bệnh viện về, chỉ muốn yên tĩnh trong bóng tối. Nhưng tự động hóa ",
"không đọc được không khí",
", nó như một thằng ngố không biết đọc ý, lập tức biến nhà thành vũ trường. Bạn phải tự tay tắt những công tắc \"tiện lợi\" đó.",
"Tình huống 2: Logic \"điều nhiệt\" lạnh lùng",
"Quy tắc",
": Nhiệt độ phòng > 26 độ -> Bật điều hòa làm lạnh.",
"Hiện thực",
": Hôm nay bạn bị mưa ướt, hơi sốt lạnh run. Nhưng cảm biến lạnh lùng, nó chỉ đọc 26.5 độ, nên cần mẫn thổi gió lạnh vào bạn đang run rẩy.",
"Tất cả nền tảng nhà thông minh đều chứa vô số công tắc thực thi hoàn hảo, nhưng tất cả đều thiếu một \"bộ não\" có thể đọc hiểu trạng thái hiện tại của bạn. Đó là lý do cuộc sống của chúng ta mãi dừng ở \"tự động hóa\" chứ không phải \"thông minh hóa\".",
"3. Ba khả năng đột phá của quản gia AI tương lai",
"OpenClaw cho tôi thấy, quản gia AI tương lai không còn là script thực thi lạnh lùng, mà là thành viên gia đình sống động.",
"① Nhịp tim thông minh: Đừng đợi tôi gọi, tự mình \"nhìn\" đi",
"Nhà thông minh hiện tại là",
"bị động",
" (người đi qua kích hoạt cảm biến), tương lai phải là",
"chủ động",
".",
"Tình huống",
": Đi làm về, bạn nằm bẹp trên giường như bùn.",
"HA truyền thống",
": Cảm biến phát hiện có người + ánh sáng tối -> ",
"Bụp! Bật đèn lớn!",
" Giật mình.",
"Quản gia AI",
": Vài phút một lần nó lặng lẽ \"nhìn quanh\" nhà (tuần tra nhịp tim).",
"Nó thấy",
": Tư thế bạn là \"nằm bẹp\", biểu cảm là \"chán đời\".",
"Vì biết phép tắc",
": Nó",
"tuyệt đối không bật đèn lớn",
", mà lặng lẽ bật chiếc đèn ngủ ấm nhất ở đầu giường.",
"Nó còn",
": Thông báo cho bạn: \"Chủ nhân trông rất mệt, cần tôi mở nhạc nhẹ thư giãn không?\" -- Đây chính là",
"biết phép tắc",
". Đây gọi là mắt tinh tường, chứ không chỉ biết bấm công tắc.**",
"② Bộ nhớ vĩnh cửu: Đừng làm robot \"nhớ như cá vàng\"",
"Mi Home cũng có nhật ký, nhưng đó chỉ gọi là",
"sổ ghi chép",
" (thời gian xx thiết bị xx bật). Đối với AI, đó là",
"dữ liệu thô thiếu ngữ cảnh",
"OpenClaw cho chúng ta biết, phải biến dữ liệu thành",
"ký ức",
"Tình huống",
": Đi làm về, bạn nằm bẹp trên giường như bùn.",
"Tình huống",
": Thứ Ba tuần sau, bạn lại mệt mỏi về nhà.",
"Quản gia AI",
": Tìm kiếm kho ký ức (",
"), phát hiện lần trước bạn rất mệt, uống sữa nóng thì tâm trạng tốt hơn.",
"Chủ động đề xuất",
": \"Lần trước uống cốc sữa nóng có vẻ hiệu quả, hôm nay lại như cũ nhé?\"",
"Đây mới là nguồn gốc của sự ấm áp --",
"nó nhớ mỗi lần vui buồn của bạn, chứ không chỉ có nhật ký bật tắt.",
"③ Tự tiến hóa: Nếu không thông minh, thì tự cố gắng thêm",
"Đây là điểm khiến tôi nổi da gà nhất.",
"Quy tắc HA viết chết là chết, trừ khi bạn tự sửa code. Nhưng quản gia AI tự \"ngộ\" ra quy tắc từ hành vi của bạn.",
"Tình huống: Sự ăn ý của điều hòa",
"Hôm qua",
": 9 giờ tối, bạn vào phòng ngủ, thấy ngột ngạt, tiện tay bật điều hòa. Bạn không nói một lời.",
"Tâm sự nội tâm AI",
"\"Chú ý! Chủ nhân có nhu cầu bật điều hòa ở nhiệt độ này lúc 21:00. Ghi lại, viết vào danh sách việc cần làm.\"",
"Hôm nay",
": 9 giờ tối, bạn vừa vào phòng ngủ.",
"AI chủ động lên tiếng",
": \"Chủ nhân, thấy bạn vừa vào phòng, theo thói quen hôm qua, cần tôi bật điều hòa không?\"",
"Bạn chưa bao giờ viết một quy tắc \"nếu 9 giờ tối thì thế nào\". Một hành động vô ý của bạn đã dạy cho nó một thói quen mới.",
"Nó không cần bạn biết lập trình, cũng không cần bạn viết YAML phức tạp. Nó qua quan sát bạn, bắt chước bạn, cuối cùng",
"ngày càng hiểu bạn hơn",
"4. Thể xác và Linh hồn: Không phải thay thế, mà là cộng sinh",
"Đọc đến đây, bạn có thể hỏi: Lẽ nào chúng ta phải phủ nhận hoàn toàn hệ thống tự động hóa hiện có, để mù quáng sùng bái AI?",
"Tất nhiên không.",
"AI không đến để thay thế tự động hóa, mà là để lắp bộ não cho nó.",
"Tự động hóa",
"là \"thể xác\". Nó chịu trách nhiệm năng lực thực thi hoàn hảo: độ ổn định vững như bàn thạch, phản hồi mili giây, thao tác chính xác không sai.",
"là \"linh hồn\". Nó chịu trách nhiệm năng lực quyết định phức tạp: cảm nhận cảm xúc, hiểu ngữ cảnh, đánh giá thời điểm.",
"Nhà thông minh tương lai nên là sự hòa hợp hoàn hảo của cả hai.",
"Điểm quyết định thực sự là:",
"Liệu chúng ta có thể tiêm một linh hồn có nhịp tim cảm nhận, ký ức dài lâu, và tự trưởng thành vào ngôi nhà thông minh chất đầy thiết bị lạnh lùng này.",
"Cùng trao đổi",
"Tôi là Nham Phong, một người khám phá lĩnh vực AI + Nhà thông minh.",
"Nếu bạn quan tâm đến quan điểm của tôi, hoặc có thêm ý tưởng vui về AI + Nhà thông minh, hoan nghênh đến tìm tôi!",
]

mapping = {}
for orig, trans in zip(segs, t):
    mapping[orig] = trans

with open('map_7.json', 'w', encoding='utf-8') as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)
print(f"Saved {len(mapping)} translations for {len(segs)} segments")
