# -*- coding: utf-8 -*-
import json, sys
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')

with open('segs_15.json', 'r', encoding='utf-8') as f:
    segs = json.load(f)

t = [
"Tổng hợp trường hợp ứng dụng thực tế OpenClaw",
"🔗 Link bài gốc: ",
"Giải quyết nút thắt thích nghi OpenClaw: Không phải kỹ năng, mà là tìm ra cách nó có thể cải thiện cuộc sống của bạn. Đây là một",
"tổng hợp các trường hợp ứng dụng thực tế từ cộng đồng.",
"Cảnh báo: Các kỹ năng OpenClaw và phụ thuộc bên thứ ba được đề cập ở đây có thể tồn tại lỗ hổng bảo mật nghiêm trọng. Nhiều use case liên kết đến kỹ năng, plugin và kho mã nguồn bên ngoài do cộng đồng xây dựng, chưa được người duy trì danh sách này kiểm tra. Hãy luôn kiểm tra mã nguồn kỹ năng, xem xét quyền yêu cầu, tránh hardcode API key hoặc thông tin xác thực. Bạn hoàn toàn chịu trách nhiệm về bảo mật của mình.",
"Mạng xã hội",
"Tên",
"Mô tả",
"Tóm tắt Reddit hàng ngày",
"Theo sở thích của bạn, sắp xếp một bản tóm tắt tuyển chọn từ các subreddit bạn thích.",
"Tóm tắt YouTube hàng ngày",
"Mỗi ngày nhận tóm tắt video mới từ các kênh bạn thích -- không bao giờ bỏ lỡ nội dung của creator bạn theo dõi.",
"Phân tích tài khoản X",
"Phân tích định tính tài khoản X của bạn.",
"Tóm tắt tin công nghệ đa nguồn",
"Tự động tổng hợp và cung cấp tin công nghệ chấm điểm chất lượng cao từ 109+ nguồn (RSS, Twitter/X, GitHub, tìm kiếm web) bằng ngôn ngữ tự nhiên.",
"Sáng tạo & Xây dựng",
"Tên",
"Mô tả",
"Tác vụ tự động hướng mục tiêu",
"Đặt mục tiêu vào đầu, để agent tự tạo, lên lịch và hoàn thành tác vụ hàng ngày -- bao gồm cả xây dựng ứng dụng nhỏ bất ngờ qua đêm.",
"Pipeline nội dung YouTube",
"Tự động hóa việc tìm ý tưởng video, nghiên cứu và theo dõi cho kênh YouTube.",
"Nhà máy nội dung đa agent",
"Chạy pipeline nội dung đa agent trong Discord -- agent nghiên cứu, viết và làm thumbnail hoạt động trong các kênh chuyên biệt.",
"Quy trình phát triển game tự chủ",
"Quản lý toàn bộ vòng đời phát triển game giáo dục: từ chọn todo đến triển khai, đăng ký, tài liệu và git commit. Thực hiện chính sách \"lỗi trước\".",
"Hạ tầng & DevOps",
"Tên",
"Mô tả",
"Điều phối workflow n8n",
"Ủy quyền lệnh API cho workflow n8n qua webhook -- agent không bao giờ chạm vào thông tin xác thực, mỗi tích hợp đều trực quan và có thể khóa.",
"Server nhà tự phục hồi",
"Chạy một agent hạ tầng luôn online trong mạng nhà của bạn, hỗ trợ truy cập SSH, Cron job tự động và khả năng tự phục hồi.",
"Năng suất",
"Tên",
"Mô tả",
"Quản lý dự án tự chủ",
"Sử dụng mô hình STATE.yaml điều phối dự án đa agent -- sub-agent làm việc song song, không cần overhead điều phối.",
"Dịch vụ khách hàng AI đa kênh",
"Hợp nhất WhatsApp, Instagram, email và đánh giá Google trong một hộp thư AI, tự động trả lời 24/7.",
"Trợ lý cá nhân qua điện thoại",
"Truy cập agent AI qua cuộc gọi điện thoại, bất kỳ điện thoại nào cũng có thể trợ giúp bằng giọng nói rảnh tay.",
"Sắp xếp hộp thư",
"Tóm tắt bản tin và gửi bản tóm tắt dưới dạng email.",
"CRM cá nhân",
"Tự động phát hiện và theo dõi liên hệ trong email và lịch của bạn thông qua truy vấn ngôn ngữ tự nhiên.",
"Theo dõi sức khỏe & triệu chứng",
"Theo dõi lượng thức ăn và triệu chứng để xác định tác nhân thông qua nhắc nhở check-in định kỳ.",
"Trợ lý cá nhân đa kênh",
"Định tuyến tác vụ đến Telegram, Slack, email và lịch thông qua một trợ lý AI duy nhất.",
"Quản lý trạng thái dự án",
"Theo dõi dự án hướng sự kiện, tự động nắm bắt ngữ cảnh, thay thế kanban tĩnh.",
"Dashboard động",
"Dashboard thời gian thực, song song lấy dữ liệu từ API, database và mạng xã hội.",
"Quản lý tác vụ Todoist",
"Tối đa hóa sự minh bạch của agent bằng cách đồng bộ nhật ký suy luận và tiến độ vào Todoist.",
"Trợ lý cá nhân qua điện thoại",
"Truy cập OpenClaw qua cuộc gọi hoặc tin nhắn từ bất kỳ điện thoại nào. Nhận cập nhật lịch, vé Jira và kết quả tìm kiếm web rảnh tay.",
"Lịch gia đình & Trợ lý gia đình",
"Tổng hợp tất cả lịch gia đình thành bản tin buổi sáng, giám sát thông tin cuộc hẹn, quản lý kho gia đình.",
"Nhóm chuyên biệt đa agent",
"Vận hành nhiều agent chuyên biệt (chiến lược, dev, marketing, kinh doanh) như một đội phối hợp thông qua một chat Telegram duy nhất.",
"Bản tin buổi sáng tùy chỉnh",
"Mỗi sáng nhận bản tin hàng ngày hoàn toàn tùy chỉnh -- tin tức, tác vụ, bản thảo nội dung và đề xuất AI.",
"Bộ não thứ hai",
"Nhắn tin cho bot để ghi chép, sau đó tìm kiếm tất cả ký ức trong dashboard Next.js tùy chỉnh.",
"Xác nhận khách mời sự kiện",
"Liên hệ từng khách mời sự kiện để xác nhận tham dự, thu thập ghi chú, và tự động sắp xếp tóm tắt hoàn toàn bằng giọng nói AI.",
"Nghiên cứu & Học tập",
"Tên",
"Mô tả",
"Theo dõi doanh thu AI",
"Theo dõi báo cáo thu nhập công nghệ/AI với preview tự động, nhắc nhở và tóm tắt chi tiết.",
"Kho kiến thức cá nhân (RAG)",
"Xây dựng kho kiến thức có thể tìm kiếm bằng cách gửi URL, tweet và bài viết vào chat.",
"Nghiên cứu thị trường & Nhà máy sản phẩm",
"Dùng kỹ năng Last 30 Days đào pain point thực trên Reddit và X, sau đó để OpenClaw xây MVP giải quyết chúng.",
"Tìm kiếm ký ức ngữ nghĩa",
"Thêm tìm kiếm ngữ nghĩa vector vào các file đánh dấu OpenClaw, hỗ trợ tìm kiếm hybrid và đồng bộ tự động.",
"Tài chính & Giao dịch",
"Tên",
"Mô tả",
"Tự lái đa thị trường",
"Giao dịch giấy tự động trên thị trường dự đoán, bao gồm backtest, phân tích chiến lược và báo cáo hiệu suất hàng ngày.",
]

mapping = {}
for orig, trans in zip(segs, t):
    mapping[orig] = trans

with open('map_15.json', 'w', encoding='utf-8') as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)
print(f"Saved {len(mapping)} / {len(segs)} segments")
