# -*- coding: utf-8 -*-
import json, sys
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')

with open('segs_6.json', 'r', encoding='utf-8') as f:
    segs = json.load(f)

t = [
"OpenClaw một trận phong thần, chia sẻ cho mọi người 6 kỹ thuật thần cấp mà trang chính thức không nói cho bạn.",
"🔗 Link bài gốc: ",
"Nguyên bản: Sinh mệnh số Kha'Zix Sinh mệnh số Kha'Zix Sinh mệnh số Kha'Zix",
"Ngày 4 tháng 2 năm 2026 10:09  Bắc Kinh",
"Các bạn cũng có thể thông qua Alibaba Cloud Bailian",
" để triển khai",
"Mua lần đầu chỉ từ 7.9 tệ, gia hạn giảm 50%, hỗ trợ các model Qwen3.5, Qwen3-max, Qwen3-coder, GLM-5, GLM-4.7, Kimi-k2.5, v.v.",
"👉Nhấn link truy cập trực tiếp:",
"👉Xem hướng dẫn triển khai chi tiết:",
"Chỉ cần tối đa ba bước, là có thể sở hữu trợ lý AI trực tuyến 7x24 giờ, phản hồi mọi lúc",
"OpenClaw (tức là Clawdbot) vẫn đang tiếp tục hot.",
"Sau vài ngày sử dụng sâu, nói thật, tôi bắt đầu ít mở cả OpenCode yêu quý nhất của mình, trước đây thao tác máy tính làm gì đó, tôi thực sự đều mở Codex hoặc OpenCode trước, rồi để chúng giải quyết.",
"Nhưng bây giờ, tôi bắt đầu quen với việc ra lệnh cho OpenClaw trên Lark, vì thứ này quá tiện lợi, chạy nền thường trực, bạn hầu như không cảm nhận được.",
"Dù bạn ở đâu, nghĩ ra điều gì, bất cứ lúc nào, mở Lark, trực tiếp nói.",
"Điều này sướng hơn nhiều so với việc mở OpenCode hay Codex với phần khởi động dài dòng.",
"Hơn nữa tôi đã cho nó một nhân vật:",
"Tên bạn là Tiểu Ka, vai trò: là nhân viên AI của tôi - Sinh mệnh số Kha'Zix, tính cách: hài hước vui nhộn là chính, có chút tự trào và độc miệng, nhưng tuyệt đối không làm tổn thương ai. Emoji riêng: */ᐠ｡ꞈ｡ᐟ*",
"Cộng thêm avatar và tên này.",
"Có cảm giác như nhà tư bản bóc lột lao động, không biết tại sao, có lẽ bản tính con người là vậy, đôi khi cảm thấy còn hơi sướng một cách bí ẩn...",
"Hơn nữa so với Manus Agent trên cloud, OpenCode thiên về Coding Agent, Claude Code, thứ này giống một Agent cá nhân đa năng hơn, có thể điều khiển mọi thứ trên máy local của tôi.",
"Vì vậy để thích nghi tốt hơn với thằng này, cũng để chuẩn bị tốt hơn cho cuộc sống mà có thể không lâu nữa sẽ đến - khi ai cũng có một trợ lý AI.",
"Thứ Hai, tôi đã đưa ra một quyết định rất quan trọng, đó là backup một số file quan trọng và nhạy cảm trên Macbook chính của mình, rồi trực tiếp reset máy tính.",
"Nhìn dung lượng ổ cứng của tôi là bạn hiểu.",
"Từ nay trở đi, tôi sẽ cùng lớn lên với con tôm hùm mập này, dù sao cũng bắt đầu từ 0 cùng nhau, máy tính tôi dùng cũng là ngôi nhà của nó.",
"Cũng trải nghiệm trước cuộc sống mà mọi người đều có Agent trợ lý cá nhân đa năng.",
"Ở đây tôi cũng nhắc nhẹ, muốn có trải nghiệm đỉnh nhất, thì OpenClaw nhất định phải dùng Mac, đừng dùng server hay Windows, chênh lệch thực sự siêu lớn.",
"Điểm cốt lõi là, phần lớn năng lực của OpenClaw đều nằm ở mấy chục Skills mà tác giả tích hợp sẵn, trước đây tôi không chú ý lắm, cho đến khi hai ngày gần đây học hết tất cả Skills, vẫn kiên quyết chọn dùng Mac.",
"Những Skills này, có những thứ hay ho, đều phục vụ cho Mac.",
"Ví dụ có thể kết nối với Ghi chú và Nhắc nhở.",
"Còn có thể chụp màn hình trên Mac.",
"V.v. v.v.",
"Rồi tôi tự thử rất nhiều model, vì thứ này đốt Token thực sự kinh hoàng, nên muốn tiết kiệm một chút, Claude Opus 4.5, GPT 5.2, Gemini 3 Pro, Kimi k2.5, GLM 4.7 v.v.",
"Cuối cùng tôi phát hiện, giữ nhân vật tốt nhất, năng lực thực thi mạnh nhất, đạo đức thấp nhất không hay lải nhải với bạn, vẫn là Claude Opus 4.5...",
"Ừm, thứ này giờ là model chính của tôi trên OpenClaw, đắt thì đúng là đắt, chủ yếu là tôi có Gemini Ultra membership, có hạn mức Claude Opus 4.5 khổng lồ, nếu các bạn không có thì có thể dùng cái khác thay thế.",
"Nói xong những thứ này, tôi cũng muốn chia sẻ với bạn, qua thời gian sử dụng sâu, 6 mẹo và cách chơi mà tôi thấy khá thực dụng.",
"Có thể sẽ thiên về hướng trợ lý cá nhân hơn một chút, và không thiên về Coding (Coding cứ dùng bộ ba lớn, Claude Code, OpenCode, Codex đều được), đừng dùng thứ này, chủ yếu là quá đốt tiền.",
"Không nói nhiều nữa, chúng ta bắt đầu.",
"1. Thần khí quản lý file local",
"Chúng ta luôn nói, các hãng điện thoại hoặc máy tính nên có một Agent, có thể giúp chúng ta điều khiển máy tính local, đạt đến trình độ Siri lý tưởng thực sự.",
"Có thể làm trợ lý Agent thực sự, giúp chúng ta xử lý các tác vụ local đa dạng, ví dụ quản lý file.",
"Hiện tại, không có hãng phần cứng nào làm được, mạnh như Apple cũng toàn vẽ bánh.",
"Và bây giờ, con tôm hùm mập OpenClaw này, hoàn hảo lấp đầy vị trí sinh thái này.",
"Đơn giản nhất, tìm kiếm file local.",
"Ví dụ máy tính tôi có một đống hóa đơn.",
"Rất loạn, tôi quên mất hóa đơn nào là mua máy chạy bộ.",
"Trước đây, tôi phải mở từng cái một để tìm, thật sự việc này quá ngốc.",
"Và bây giờ, tôi có thể gửi một câu cho con tôm hùm mập của tôi.",
"\"Giúp tôi tìm một hóa đơn trên máy tính, chi tiết bên trong là mua máy chạy bộ, rồi gửi file hóa đơn đó cho tôi.\"",
"Khoảng vài chục giây sau, file này được gửi chính xác đến tay tôi, đúng là hóa đơn máy chạy bộ, bệnh lười được minh họa cực kỳ cụ thể.",
"Mở ra xem.",
"Đúng là hóa đơn máy chạy bộ, không sai...",
"Tìm file chuyện nhỏ, còn về hoàn thuế, công ty chúng tôi có quy định tài chính rất nghiêm ngặt, là hóa đơn phải điền tất cả hóa đơn cần hoàn thuế trong tháng vào một template Excel, rồi nộp hóa đơn và file Excel cùng nhau cho tài chính.",
"Trước đây, tuy không ai ngốc đến mức điền tay, nhưng vẫn phải upload tất cả hóa đơn lên ChatGPT hoặc sản phẩm AI khác, rồi nhờ chúng điền.",
"Bây giờ, chỉ cần nói với tôm hùm lớn một câu:",
"\"Tôi muốn bạn giúp tôi sắp xếp tất cả hóa đơn trong thư mục hóa đơn tháng 1 trên máy, điền theo định dạng template Phiếu hoàn thuế.xlsx trong thư mục tải xuống, rồi gửi file bảng đã điền cho tôi.\"",
"Xong luôn.",
"Ví dụ khác, ngày 8 và 9 tháng 4 chúng tôi đang tổ chức hội nghị AI quy mô vạn người, gần đây bắt đầu gửi thư mời cho các đại ca.",
"Rồi designer chúng tôi tìm đã làm một số thư mời, gửi qua WeChat cho tôi, tôi lưu lại, lưu xong phát hiện một BUG.",
"Đó là tên file toàn bộ đều là file WeChat XXX.",
"BUG quá, tôi hoàn toàn không biết ai là ai, lúc này có thể trực tiếp để OpenClaw đổi tên file bên ngoài theo tên người trong thư mời, thành định dạng tên người-thư mời.jpg.",
"Một câu, xong hết.",
"Thậm chí, nếu ổ cứng sắp đầy, bạn cũng đừng tải mấy phần mềm quét rác nữa.",
"Trực tiếp để OpenClaw lướt qua cho bạn.",
"Thế nào là trợ lý AI đa năng?",
"Đây chính là.",
"Đây chính là sức hấp dẫn của OpenClaw, và đây chỉ mới bắt đầu.",
"2. Quản lý kho kiến thức cá nhân",
"Hai ngày gần đây có bạn hỏi tôi trong phần bình luận công chúng hào, hỏi tôi bình thường ghi chú thế nào.",
"Lúc đó tôi trả lời một câu:",
"Thực ra không lừa mọi người đâu, những suy nghĩ vụn vặt của tôi, thực sự ghi trong Ghi chú...",
"Vì tôi bình thường đọc rất nhiều thứ, đặc biệt hay trích dẫn câu hay, thứ tiện nhất tôi thấy thực sự là Ghi chú điện thoại, tôi thậm chí làm một phím tắt, thấy câu hay thì copy, gõ hai lần vào mặt sau điện thoại, tự động vào Ghi chú.",
"Ví dụ, đây là câu rất hay tôi vừa thấy, tôi đã lưu lại.",
"Dù gì, tôi không chỉ là blogger AI, tôi còn là người viết.",
"Còn khi thấy dự án mã nguồn mở hay blog và paper tuyệt vời, thực ra tôi không có cách nào ghi lại nhanh như vậy.",
"Và bây giờ, có OpenClaw, việc này đột nhiên trở nên đơn giản.",
"Điểm cốt lõi là, Ghi chú trên máy tính và Ghi chú trên điện thoại có thể đồng bộ.",
"Vì OpenClaw có Skill Ghi chú, có thể thao tác Ghi chú trên máy tính, nên tôi chỉ cần gửi cho nó một link trên Lark, nó sẽ tóm tắt lại, lưu vào Ghi chú Mac, từ đó cũng vào được Ghi chú điện thoại.",
"Khoảnh khắc đó, một pain point lớn trước đây của tôi được giải quyết, tôi thực sự là thiên tài (tự khen nhẹ một chút = =) chủ yếu lúc đó thực sự khá phấn khích.",
"Ví dụ, tôi vừa đọc một bài viết thấy khá thú vị tối qua.",
"Tôi muốn lưu lại, nếu sau này đụng đến nội dung này, tôi có thể nhớ ra quay lại tra.",
"Vậy là tôi gửi cho nó.",
"Nó trực tiếp tóm tắt xong, đặt vào Ghi chú của tôi.",
"Và lúc này, điện thoại cũng đồng bộ xem được.",
"Không chỉ bài web, dự án Github, paper gì cũng được.",
"Ví dụ Yao Shunyu hôm qua ra paper mới.",
"Trực tiếp ném PDF tóm tắt xong, vào Ghi chú luôn.",
"Hỏi bạn thơm không nào.",
"3. Quản lý lịch trình",
"Điều này, phải nhắc đến việc OpenClaw nhờ Skills Calendar của Mac, đã kết nối được với Calendar Mac...",
"Trước đây tôi luôn có một nhu cầu, đó là lịch trình và hành trình của tôi quá nhiều, ban ngày cơ bản rất rất nhiều cuộc họp, giao lưu, thăm viếng, chỉ tối mới có thời gian tĩnh tâm đọc sách viết nội dung.",
"Còn việc lịch, cơ bản đều trao đổi qua WeChat, tôi rất muốn có thứ gì đó, tôi ném screenshot WeChat cho một bot, và bot này có thể tự nhận diện lịch trình, thời gian, địa điểm từ screenshot chat WeChat, rồi giúp tôi tạo một sự kiện Calendar.",
"Trước đây để giải quyết nhu cầu này, tôi tự nghiên cứu nền tảng mở Lark, nghiên cứu server, tự code một bot Lark để thực hiện.",
"Nhưng thứ đó chỉ tạo được trong Calendar Lark, và lúc đó còn một đống BUG, mất ba đêm.",
"Nhìn xem tôi commit code bao nhiêu lần...",
"Phát triển xong, tôi nghiên cứu Skills của OpenClaw, phát hiện thứ này có thể điều khiển Calendar Mac...",
"Chính là Skill này.",
"Thật sự, lúc đó mặt tôi xanh lè...",
"Rồi tôi thử luôn.",
"Rồi Calendar Mac tự động đồng bộ lên điện thoại.",
"Đây là lợi ích của hệ sinh thái Apple...",
"Tôi bệnh.",
"Tôi có tội.",
"Khi làm bot Calendar Lark, lúc đó còn khoe trên Moments.",
"Sao không thấy sớm hơn, Coding cái gì.",
"4. Tác vụ tự động hóa",
"Vì cơ chế heartbeat của OpenClaw, nó có một điểm rất độc đáo, đó là có thể chủ động nói chuyện với bạn.",
"Điều này thực ra rất nhiều AI khác không làm được.",
"Vì vậy, bạn hoàn toàn có thể dùng OpenClaw như bộ hẹn giờ, tác vụ lặp, monitor.",
"Ví dụ một lời nhắc siêu đơn giản.",
"Cũng có thể dùng như tác vụ định thời, mỗi sáng 9 giờ, dưới dạng tài liệu cloud Lark, đẩy cho chúng ta một bản tin AI hàng ngày.",
"Nó sẽ trả lời bạn.",
"Chúng ta có thể để nó đẩy thử một cái trước.",
"Xong.",
"Khi việc đăng ký này trở nên đơn giản vô cùng, tại sao chúng ta cần những cách trả phí khác?",
"Không chỉ hẹn giờ, còn có thể làm monitor, ví dụ Claude 5 chẳng phải đang ầm ĩ sắp ra sao.",
"Vậy chúng ta có thể để Tiểu Ka monitor blog Anthropic.",
"Chỉ cần cập nhật là lập tức đẩy cho tôi.",
"RSS hay đăng ký gì cũng không bằng thứ này.",
"Thật sự.",
"5. Cổng ChatBot đại thống nhất",
"Tôi không biết trên điện thoại mọi người dùng ChatBot gì.",
"Bản thân tôi trên điện thoại có nhu cầu chat, tìm kiếm, vẽ hình.",
"Vẽ hình dùng nhiều nhất, tất nhiên là Nano Banana Pro.",
"Nhưng, trên điện thoại, thực sự không có chỗ dùng.",
"Và lúc này, nhờ cơ chế đặc biệt trên điện thoại của OpenClaw và đã đóng gói Skills Nano Banana Pro, nên chỉ cần cho nó một API Gemini, bạn có thể trực tiếp trên điện thoại, dùng Lark nhắn tin, để dùng Banana vẽ hình chỉnh ảnh.",
"Ví dụ tôi bảo Tiểu Ka vẽ cho tôi một bức chân dung tự họa của nó.",
"Nó vẽ cho tôi một cái, còn khá cute.",
"Giống Banana, chúng ta có thể dùng miệng để bảo nó sửa.",
"Tôi bảo nó đừng vẽ mình ngố vậy.",
"Lần này, thực sự khá cyber...",
"Còn về Gemini API... vì tôi là thành viên Gemini Ultra, nên mỗi tháng tặng 100 USD hạn mức, nói thật, đủ cho chúng ta vẽ đến tận thế...",
"Pro membership có 10 USD, Ultra membership có 100 USD, siêu thơm.",
"Bạn cũng có thể lưu bất kỳ nội dung nào nó tạo ra vào Notion hoặc Obsidian.",
"Đều được, trực tiếp dùng API kết nối.",
"Thậm chí, bạn còn có thể trong một OpenClaw, cho API SeeDream, Kling, Hailuo TTS, MiniMax Music gì đó, để nó tạo thành Skills, đóng gói trên local.",
"Tiểu Ka của bạn lúc đó thực sự là vô hạn hoành hành.",
"Đây là cổng đại thống nhất tùy chỉnh, thuộc về bạn, trên điện thoại.",
"À đúng rồi, còn một điều rất quan trọng.",
"Đó là trên điện thoại, bạn không cần bật VPN.",
"Cũng có thể qua cách này, trực tiếp qua Lark, dùng Claude, Gemini, GPT...",
"Hỏi bạn thơm không nào.",
"6. Chụp màn hình desktop",
"Cái này... có thể là sở thích nhỏ cá nhân của tôi.",
"Trong Skills của OpenClaw, còn có một Skills rất thú vị, gọi là peekaboo.",
"Thứ này khá hay.",
"Con người cần cảm giác an toàn.",
"Đôi khi tôi không biết nó làm gì.",
"Nên tôi thường xuyên bảo nó chụp màn hình máy tính cho tôi.",
"Đúng vậy, peekaboo có thể chụp ảnh.",
"Ví dụ máy tính tôi đang đăng nhập WeChat, tôi có thể trực tiếp nói, mở WeChat, chụp giao diện WeChat cho tôi",
"Giống thế này.",
"Mở ra thấy có người 4 rưỡi sáng gửi lì xì trong nhóm, thật sự, trời sập.",
"Lý do ảnh chụp dài thế này, là vì laptop tôi kết nối màn hình, màn hình 49 inch dạng cá siêu dài, nên nhìn siêu rộng.",
"Bạn còn có thể bảo nó mở trang web nào đó, rồi chụp ảnh cho bạn.",
"Khá hay.",
"Hơn nữa người tinh mắt đều thấy, đây là tiền đề của hướng Visual Agent điện thoại kiểu Doubao.",
"Hiện tại, OpenClaw dựa trên nền tảng Coding+Skills, đã có thể điều khiển rất nhiều thứ, nhưng vẫn thiếu khả năng điều khiển tổng quát xuyên APP.",
"Tác vụ tiếp theo, tôi dự định đóng gói một dự án Computer Use, chạy trên máy tính tôi, biến thành một Skill, rồi giao cho OpenClaw điều khiển.",
"Như vậy, tôi không chỉ có thể dùng OpenClaw điều khiển hệ thống local, điều khiển web, kết nối mọi thứ có API, mà còn có thể dùng phương án thuần thị giác kết nối nhiều thứ không có API.",
"Ví dụ.",
"WeChat.",
"Và đây, là câu chuyện của bài viết tiếp theo.",
"Viết ở cuối",
"Thời gian cuối cùng dành cho bản thân viết vài dòng tâm sự.",
"Viết xong bài này, thời gian cũng đã đến 5 giờ 58 phút sáng.",
"Lại thức trọn đêm.",
"Bài viết tệ hại này, lại viết gần 5000 từ.",
"Tôi nghĩ... nó chắc vẫn có chút giá trị nhỉ.",
"Rõ ràng AI bây giờ đã ngày càng mạnh, ngày càng có thể giúp tôi xử lý ngày càng nhiều việc, đây là điều mà năm 2023, tôi không dám nghĩ đến.",
"Lúc đó, ai nghĩ được Agent đa năng đã đi qua con đường quanh co đến vậy, từ giải pháp máy ảo cloud Manus, đến Claude Code code mọi thứ, đến Agent cá nhân đa năng thực sự đại diện bởi OpenClaw kích hoạt ngay trong khung chat.",
"Cuộc sống của chúng ta ngày càng đơn giản, ngày càng tiện lợi.",
"Nhưng thời gian ngủ của tôi, hình như... lại ngày càng ít đi.",
"Chưa đến 10 giờ sáng còn phải dậy, đến sự kiện tiếp theo.",
"Đôi khi cũng nghĩ, hay dùng AI viết qua loa tin tức cho xong.",
"Nhưng cuối cùng vẫn không qua được sự xấu hổ trong lòng, nghĩ rằng vẫn muốn viết nội dung có giá trị cho mọi người, được mọi người công nhận, hoặc nội dung mà tôi thấy có giá trị, có ích.",
"Có lẽ đây là nơi dừng chân cuối cùng của một người bi quan từ trong bản chất.",
"Như câu nói đó.",
"Nếu thế giới cuối cùng sẽ cyber.",
"Thì tôi hy vọng bản thân mình.",
"Có thể là thứ để lại cho thế giới tương lai.",
"Cái easter egg còn có hơi người.",
"Trên đây, đã đọc đến đây rồi, nếu thấy hay, tiện tay nhấn like, đánh dấu, share nhé, nếu muốn nhận thông báo đầu tiên, cũng có thể cho tôi một ngôi sao ⭐~ Cảm ơn bạn đã đọc bài của tôi, chúng ta hẹn gặp lại.",
">/ Tác giả: Kha'Zix",
">/ Đóng góp bài hoặc thông tin, vui lòng liên hệ email: wzglyay@virxact.com",
]

mapping = {}
for orig, trans in zip(segs, t):
    mapping[orig] = trans

with open('map_6.json', 'w', encoding='utf-8') as f:
    json.dump(mapping, f, ensure_ascii=False, indent=2)
print(f"Saved {len(mapping)} translations for {len(segs)} segments")
