#!/usr/bin/env python3
"""Translate article 4 for batch chunk 2"""
import json, sys, re, copy

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

def has_chinese(t):
    return bool(re.search(r'[\u4e00-\u9fff\u3400-\u4dbf]', t))

d = json.load(open('art4_orig_c2.json', 'r', encoding='utf-8'))

vn = [
    "Lộc Đạo: Hướng dẫn triển khai đầy đủ OpenClaw + Gemini 3 Flash + Feishu",
    "Các bạn cũng có thể thông qua Alibaba Cloud Bailian",
    "để triển khai",
    "Mua lần đầu chỉ từ 7,9 tệ, gia hạn giảm từ 50%, hỗ trợ các mô hình Qwen3.5, Qwen3-max, Qwen3-coder, GLM-5, GLM-4.7, Kimi-k2.5",
    "👉Nhấn link truy cập trực tiếp:",
    "👉Xem hướng dẫn triển khai chi tiết:",
    "Chỉ cần tối đa ba bước, bạn sẽ có trợ lý AI trực tuyến 7x24 giờ, phản hồi mọi lúc",
    "Lời nói đầu",
    "Tuần qua tôi đã trải nghiệm sâu OpenClaw, thử hết các model có thể kết nối: Kimi 2.5 hoạt động khá tốt, các model đỉnh như Opus 4.6, Gemini trải nghiệm thật sự tốt hơn. Cân nhắc tổng hợp hiệu quả và tính giá, cuối cùng tôi chọn Gemini 3 Flash (thông qua reverse proxy Antigravity của thành viên Google One, hạn mức API reset mỗi 5 giờ, cơ bản không tốn tiền).",
    "OpenClaw triển khai một chạm trên Alibaba Cloud bản thân đã hỗ trợ khá đầy đủ model trong nước, nhưng nhiều người muốn dùng Gemini hoặc model nước ngoài khác + Feishu lại bị kẹt ở reverse proxy, cấu hình và triển khai cloud. Nên tôi chỉnh lý toàn bộ giải pháp của mình thành hướng dẫn, từ cloud server đến kết nối Feishu, viết rõ từng bước, tiện cho mọi người làm theo. Nếu bạn:",
    "Muốn tự triển khai → cứ theo hướng dẫn từng bước;",
    "Không muốn vọc vạch, hoặc gặp vấn đề khi triển khai → có thể + Ludao112, tôi có thể giúp triển khai từ xa hoặc debug, tiết kiệm thời gian.",
    "Hướng dẫn ở bên dưới, cần thì liên hệ tôi.",
    "Kiến trúc tổng thể như sau:",
    "Mua cấu hình server Alibaba Cloud theo nhu cầu",
    "Đăng nhập Alibaba Cloud",
    " , nhấn Triển khai nhanh trên trang chủ để trải nghiệm ngay",
    "Sau khi mua xong quay lại Service Console",
    "Thông tin server",
    "Đây là",
    "Cấu hình đã mua tại đây",
    "Hệ thống: Ubuntu",
    "IP công cộng: xx.xxx.xx.xxx",
    "Cấu hình: 2 vCPU / 2 GiB RAM / 40 GiB ESSD",
    "Khu vực: Mỹ (Virginia)",
    "Giai đoạn 1: Chuẩn bị môi trường cơ bản server",
    "SSH đăng nhập server Alibaba Cloud (",
    "#Nếu trong quá trình thao tác sau server tự ngắt kết nối, quay lại bước này ssh lại",
    "Cập nhật hệ thống và cài công cụ cần thiết",
    " Bật phân vùng Swap (bắt buộc với 2GB RAM)",
    "Cài Node.js 22+",
    "Cài pnpm (tùy chọn, cần khi build từ source)",
    "Nếu xuất hiện thông báo xung đột file cấu hình openssh-server, chọn \"keep the local version currently installed\".",
    "Đây là thông báo xung đột file cấu hình openssh-server xuất hiện trong quá trình apt upgrade. Chọn mục thứ hai: keep the local version currently installed. Lý do: sshd_config của server Alibaba Cloud đã được Alibaba Cloud tùy chỉnh (ví dụ port, cài đặt bảo mật...), nếu chọn mục đầu \"install the package maintainer's version\" có thể ghi đè cấu hình tùy chỉnh của Alibaba Cloud, nghiêm trọng thì có thể mất kết nối SSH, không đăng nhập lại được. Cách thao tác:",
    "Dùng phím mũi tên ↓ di chuyển đến keep the local version currently installed",
    "Nhấn Enter xác nhận",
    "Giai đoạn 2: Cài đặt OpenClaw",
    "Cách 1: Cài một chạm (khuyến nghị)",
    "Thêm --no-onboard vì chúng ta cần dùng reverse proxy Antigravity cho openclaw, nên cần cấu hình model provider trước rồi mới onboard.",
    "Xác minh cài đặt",
    "Giai đoạn 3: Cấu hình Antigravity Proxy",
    "openclaw tiêu thụ token rất cao, nên ai có Google One membership có thể lấy hạn mức Gemini miễn phí trong Antigravity cho openclaw dùng, nếu dùng API riêng có thể bỏ qua bước này, trực tiếp nhập openclaw onboard trong terminal để cấu hình",
    "Cài toàn cục",
    " Thêm tài khoản Google ủy quyền (chế độ headless)",
    "Nếu báo lỗi:",
    "Thao tác theo thứ tự sau:",
    "1. Dừng process proxy trước. Nếu bạn khởi động bằng & chạy nền:",
    "Hoặc nếu bạn đã thiết lập systemd service:",
    "Sau đó thêm tài khoản",
    "Lúc này nó sẽ cho bạn một URL Google OAuth, copy vào trình duyệt local mở, hoàn thành ủy quyền rồi dán mã ủy quyền trở lại.",
    "Thêm thành công, khởi động lại proxy",
    "Copy URL ủy quyền Google OAuth đã xuất",
    "Mở URL đó trong trình duyệt máy tính local",
    "Đăng nhập ủy quyền bằng tài khoản Google",
    "Sau khi nhận được mã ủy quyền URL, dán lại terminal server (đừng đóng trang web bên phải)",
    "Xem hình lớn bên phải👉",
    "Khởi động proxy chạy nền ",
    " Xác minh proxy",
    "Thiết lập systemd chạy liên tục",
    "Tạo file /etc/systemd/system/antigravity-proxy.service:",
    "Kích hoạt và khởi động:",
    "Giai đoạn 4: Cấu hình OpenClaw sử dụng Gemini 3 Flash",
    "1. Chạy onboard wizard",
    "2. Chỉnh sửa file cấu hình",
    "Quay lại terminal chỉnh sửa ~/.openclaw/openclaw.json:",
    "Xóa nội dung cũ (tiện cho việc dán cả đoạn)",
    "Di chuyển con trỏ đến ký tự đầu tiên dòng đầu (dùng phím mũi tên).",
    "Giữ Option (Mac) hoặc Alt (Windows), nhấn G, rồi nhấn 1 và Enter, sẽ nhảy đến dòng 1.",
    "Hoặc không cần nhảy dòng, trực tiếp thao tác từ đầu cũng được.",
    "Chọn tất cả và xóa:",
    "Trên Mac: Cmd + A chọn tất cả (trong terminal SSH có thể không hoạt động, dùng cách bên dưới).",
    "Cách chung: Nhấn Ctrl + 6 (hoặc Ctrl + ^) đặt \"marker\", rồi di chuyển con trỏ đến sau ký tự cuối dòng cuối, sau đó Ctrl + K sẽ cắt từ marker đến con trỏ, cắt vài lần đến khi xóa hết toàn bộ;",
    "Hoặc: Giữ Ctrl + K, mỗi lần nhấn xóa một dòng, xóa hết nội dung cũ từng dòng, đến khi file trống.",
    "Cách tiện hơn: Không xóa cũng được, trực tiếp đến bước ba, chọn từ { và dán, đè lên nội dung cũ (xem hướng dẫn bước ba).",
    "Ghi nội dung sau:",
    "Giải thích quan trọng:",
    "apiKey đặt \"test\" là được, Antigravity Proxy tự xử lý Google OAuth",
    "baseUrl dùng 127.0.0.1 thay vì localhost",
    "primary đặt antigravity-proxy/gemini-3-flash",
    "3. Xác minh cấu hình model",
    "4. Khởi động Gateway",
    "5. Kiểm tra trạng thái",
    "6. Thiết lập systemd chạy liên tục (nếu onboard chưa tạo tự động)",
    "Tạo file /etc/systemd/system/openclaw-gateway.service:",
    "Kích hoạt và khởi động:",
    "Giai đoạn 5: Cấu hình kênh Feishu",
    "Cài cầu nối Feishu",
    "Tạo bot trên Feishu Open Platform",
    "Mở https://open.feishu.cn/app và đăng nhập",
    "Nhấn \"Tạo ứng dụng tự xây\"",
    "Điền tên ứng dụng (ví dụ \"AI Trợ lý\")",
    "Vào ứng dụng → Thêm khả năng ứng dụng → Chọn \"Bot\"",
    "Vào \"Quản lý quyền\", mở các quyền sau:",
    "3. Quay lại terminal tạo cầu nối Feishu",
    "Sau khi lấy chứng chỉ, quay lại terminal tạo cầu nối Feishu trước, nếu không thiết lập long connection sẽ thất bại!!!!",
    "Phần màu xanh",
    "Thay thế bằng App_ID và AppSecret của bạn",
    "Đến bước này có thể quay lại Feishu tiếp tục cấu hình bot",
    "Thêm quyền Feishu",
    "Có thể theo tình hình của mình mở các quyền tương ứng, có thể chọn cách import",
    "Nhấn Import hàng loạt",
    "Sau khi mở xong như sau",
    "Cấu hình sự kiện: Chọn long connection",
    "Thêm sự kiện: Lần lượt thêm theo lệnh",
    "Nhấn Tạo phiên bản",
    "Điền xong các mục bắt buộc rồi phát hành",
    "Test chat Feishu",
    "Hướng dẫn xử lý lỗi",
    "Gặp vấn đề sau triển khai, tự kiểm tra theo các trường hợp dưới",
    "Kiểm tra trạng thái ba service",
    "Cầu nối Feishu bị ngắt",
    "Tạo lại systemd service cho cầu nối Feishu",
    "Thực thi trên server (thay cli_AppID_của_bạn bằng App ID bạn thấy trên Feishu Open Platform):",
    "Kiểm tra sức khỏe proxy",
    "Kiểm tra trạng thái OpenClaw",
    "Test phía Feishu",
    "Tìm bot trên Feishu, gửi \"Xin chào\" hoặc tin nhắn khác để xác minh phản hồi.",
    "Vấn đề",
    "Cách kiểm tra",
    "Feishu gửi tin không có phản hồi",
    "Gọi model thất bại",
    "Gateway không phản hồi",
    "Google OAuth hết hạn",
    "Quyền Feishu không đủ",
    "Quay lại Feishu Open Platform kiểm tra quyền, đảm bảo im:resource... đã được mở",
    "Một số cảm ngộ về Vibecoding công ty một người & Mẹo sử dụng OpenClaw",
    "Tôi là Lộc Đạo.",
    "Một developer không có nền tảng lập trình, bắt đầu Vibe Coding từ số 0.",
    "Một tháng rưỡi qua, một mình tôi, thông qua Vibe Coding đã thực hiện ",
    "3 dự án cấp độ production đi vào hoạt động",
    ". Hôm nay muốn nhân dịp hướng dẫn triển khai OpenClaw này, chia sẻ tại sao tôi lại dành nhiều thời gian đến thế để kiên trì với triển khai AI, cùng một số cảm ngộ về mô hình \"công ty một người\".",
    "Một, Tại sao chúng ta phải All in AI?",
    "Câu chuyện phải quay lại 3 năm trước. Khi ChatGPT 3.5 mới ra, 90% mọi người còn coi nó là đồ chơi chat, tôi đã dẫn team All in AI.",
    "Lúc đó chúng tôi ép LLM vào business, kết quả kinh ngạc —",
    "3 tháng đạt tăng trưởng doanh thu cấp triệu",
    ". Việc này hoàn toàn củng cố quyết tâm của tôi đào sâu vào AI. Từ đó, tôi chạy không ngừng, từ thử nghiệm các LLM đến xây dựng workflow n8n, Coze, Dify.",
    "Nguyên tắc của tôi chỉ có một:",
    "Cái mới ra, lập tức nghĩ cách áp dụng vào thực tế.",
    " Không phải học công nghệ vì công nghệ, mà để AI thực sự tạo ra giá trị kinh doanh, giảm chi phí tăng hiệu quả.",
    "Mấy tháng qua, các ông lớn đánh nhau kinh thiên, công nghệ thay đổi từng ngày. Mỗi ngày tôi ngồi trước máy tính hơn chục tiếng, quên ăn quên ngủ, không những không thấy mệt, mà còn cảm thấy một sự phấn khích bị năng suất đập liên hồi.",
    "Hai, Vibe Coding: Biến \"cửa một chiều\" thành \"cửa hai chiều\"",
    "Đầu năm 2026, OpenClaw open source là một cột mốc.",
    "Nó đánh dấu AI không còn chỉ là một hộp thoại thông minh, mà là một ",
    "\"nhân viên số\"",
    "chỉ cần gắn não vào là có thể làm việc trong các tình huống cụ thể. Có người phàn nàn Token đắt, nhưng theo tôi, so với chi phí nhân sự, đây đúng là giá rẻ bèo. Chỉ cần nó chạy thông một vòng kinh doanh khép kín 7x24 giờ, đã tiết kiệm hơn tuyển người rất nhiều.",
    "Quan trọng hơn, Vibe Coding đã thay đổi hoàn toàn cách tôi ra quyết định.",
    "Phát triển truyền thống là quyết định \"cửa một chiều\":",
    " Năm ngoái tôi tốn vài chục vạn thuê team outsource, quy trình cực kỳ rườm rà: PRD → Figma → Frontend → Backend → Test → Nghiệm thu. Ma sát giao tiếp cực lớn, thất thoát thông tin cực cao, cuối cùng thứ bàn giao lại không đạt kỳ vọng. Tiền đã tiêu không phải bài học lớn nhất với tôi, nhưng",
    "thời gian, công sức và chi phí cơ hội",
    "đầu tư vào dự án này, là điều tôi đã suy ngẫm rất lâu.",
    "Thời đại Vibe Coding, quyết định là \"cửa hai chiều\":",
    " Bây giờ, thông qua giao diện cực kỳ thân thiện như Codex, Claude Code (đúng là may đo cho Vibe Coder như chúng ta), tôi chỉ cần có ý tưởng kinh doanh, giao tiếp trực tiếp bằng ngôn ngữ tự nhiên, lập tức tạo ra công cụ, SaaS, trang web. Sai? Làm lại. Không tốt? Sửa ngay. ",
    "Phát triển trở thành một tương tác hai chiều chi phí thấp, tần suất cao.",
    " (Thậm chí làm ra đống rác, lập tức có thể review lại prompt và kiến trúc, rồi lập tức khởi đầu dự án mới từ 0) Tôi có thể coi OpenClaw như \"đối tác kỹ thuật\" hoặc \"PR team phát triển\" của mình, để nó chỉ huy Codex làm việc.",
    "Ba, Cảnh giác: Khi sản phẩm thừa mứa, chỉ có traffic mới là vua",
    "Sự bùng nổ của Vibe Coding sắp mang đến một thực tế khắc nghiệt:",
    "Sản phẩm internet sẽ cực kỳ dư thừa.",
    "Ai cũng có thể dùng ngôn ngữ tự nhiên làm ra một App, một website. Phía cung cực kỳ bão hòa, nhưng hiệu quả truyền tải thông tin vẫn là nút thắt. Bạn làm ra sản phẩm tốt, nhưng không ai biết, không có user, vẫn là đường cụt.",
    "Đây cũng là lý do tôi muốn viết bài này.",
    "Trong thời đại ai cũng là developer,",
    "Vòng khép kín thực sự không nằm ở \"làm ra\", mà ở \"bán được\".",
    " Chúng ta phải xuất giá trị ở phía traffic, nắm bắt sự chú ý của user, nỗ lực ở phía marketing. Sản phẩm chỉ là hạ tầng, marketing mới là vòng khép kín.",
    "Bốn, Tâm pháp thực chiến OpenClaw: Lắp \"tay chân\" cho nhân viên số",
    "Với các bạn không có nền tảng lập trình, muốn dùng tốt OpenClaw, tôi có vài lời khuyên:",
    "1. Khuyến nghị phần cứng: Mac mini + trực quan hóa",
    "Hướng dẫn này viết nhân tiện lúc giúp đồng nghiệp công ty triển khai, nhưng cá nhân tôi rất khuyến nghị",
    "Triển khai trên Mac mini",
    "Lợi thế hệ sinh thái:",
    " Có thể kết nối liền mạch hệ sinh thái Apple (iMessage, Keychain...).",
    "Cảm giác an toàn:",
    " Với người không chuyên kỹ thuật, giao diện trực quan (thấy được nó đang làm gì) an tâm hơn nhiều so với terminal đen ngòm.",
    "2. Cấu hình cốt lõi: API chính là cơ quan của nó",
    "Đừng dùng OpenClaw như chatbot, đó là phí phạm. Bạn phải kết nối tất cả API cho nó, để nó đầy đủ tay chân, trở thành siêu cá thể thực sự.",
    "Dưới đây là",
    "Danh sách cấu hình đầy đủ của tôi hiện tại",
    "(khuyến nghị toàn bộ dùng môi trường sandbox hoặc tạo tài khoản độc lập mới, an toàn trên hết):",
    "👁️ Loại tìm kiếm & tình báo (lưu trữ Keychain)",
    "Khả năng:",
    " Công cụ tăng cường tìm kiếm AI chuyên nghiệp.",
    "Giá trị:",
    " Chuyên dùng cho",
    "Nghiên cứu tech stack nước ngoài, phân tích thị trường",
    "(như giám sát đối thủ toàn cầu cho dự án PixPaw của tôi). Dữ liệu nó trả về có cấu trúc, phù hợp cho AI hơn Google.",
    "Bocha API:",
    "Khả năng:",
    " Tối ưu sâu cho internet tiếng Trung.",
    "Giá trị:",
    " Chuyên xử lý",
    "Tình báo trong nước",
    ". Ví dụ giám sát động thái ngành nội thất B2B, tin tức chuỗi cung ứng trong nước, mảng này nó là chuyên gia.",
    "🧠 Loại engine model",
    "Khả năng:",
    " Đồng thời cao, độ trễ cực thấp, ngữ cảnh siêu dài.",
    "Giá trị:",
    "Bộ não chủ điều khiển",
    ". Chịu trách nhiệm hiểu ý định của tôi, điều phối các công cụ khác.",
    "Khả năng:",
    " Node model open source logic chặt chẽ.",
    "Giá trị:",
    "Dự phòng chiến thuật",
    ". Khi cần logic suy luận tối đa, hoặc khi model chính \"phát điên\", đảm bảo mạch tư duy không bị đứt.",
    "🗣️ Loại liên lạc & tự động hóa",
    "Khả năng:",
    " Quyền ứng dụng tự xây, gửi nhận tin nhắn.",
    "Giá trị:",
    "Kênh liên lạc chính",
    ". Đẩy bản tin buổi sáng, cảnh báo hệ thống, phản hồi cảm hứng, đều dựa vào nó.",
    "Khả năng:",
    " Gọi SMS native của Mac mini.",
    "Giá trị:",
    "Kênh khẩn cấp",
    ". Khi tôi không xem Feishu, SMS có thể trực tiếp bắn đến điện thoại.",
    "🦾 Tự động hóa thị giác & Điều khiển Mac (Peekaboo & Nodes API)",
    "Khả năng:",
    " Thông qua điều khiển Peekaboo và Browser trên Mac mini, OpenClaw có thể \"nhìn thấy\" màn hình, mô phỏng click chuột.",
    "Giá trị:",
    " Đây là chìa khóa thực hiện **\"tuần tra đêm\"**. Nó có thể giúp tôi giám sát trạng thái hoạt động của n8n, thậm chí thao tác những backend không có API (như backend dự án hoặc hệ thống chạy quảng cáo).",
    "Năm, Cách dùng tối thượng: Bộ não ngoài & Workflow \"Memo\"",
    "Thời đại AI, thứ thật sự khan hiếm không phải công nghệ, mà là",
    "sự chú ý của bạn",
    "và",
    "tư duy sâu",
    "Để bảo vệ sự chú ý, tôi đã thiết lập cho OpenClaw một tác vụ CRON (định kỳ) quan trọng nhất:",
    "Review cảm hứng",
    "Workflow của tôi như sau:",
    "Bắt giữ phân mảnh:",
    " Ban ngày dù đang làm gì, hễ có cảm hứng, tôi lập tức gửi cho OpenClaw một tin nhắn bắt đầu bằng ",
    " .",
    "Mở rộng tức thì:",
    " OpenClaw nhận được ",
    " sẽ lập tức theo Prompt đã cài sẵn, giúp tôi mở rộng logic ý tưởng phân mảnh, ghi lại hồ sơ.",
    "Tiếp tục tập trung:",
    " Gửi xong tôi không quan tâm nữa, quăng điện thoại, tiếp tục Vibe Coding, không phá vỡ trạng thái flow.",
    "Review ban đêm:",
    " Đến giờ cố định buổi tối, OpenClaw sẽ chủ động tìm tôi, lấy tất cả ",
    " trong ngày ra review, thảo luận với tôi, rồi phân tách thành kế hoạch công việc cụ thể ngày hôm sau.",
    "Thói quen này tôi đã có từ trước, nhưng sau khi OpenClaw xuất hiện, trở nên nhẹ nhàng vô cùng.",
    "Điều này tương đương tôi tự thêm cho mình một thanh RAM.",
    " Tôi đưa tất cả process \"quan trọng nhưng không gấp\" trong não ra ",
    " cho OpenClaw, giải phóng RAM não mình để xử lý tác vụ cốt lõi hiện tại.",
    "OpenClaw không chỉ là công cụ, nó là",
    "Bộ não thứ hai",
    "của tôi, cũng là một tầng quản lý quan trọng trong bầy agent tương lai, giúp tôi ra lệnh, gọi agent.",
    "Trên đây là một số cảm ngộ thực chiến gần đây của tôi về Vibe Coding và OpenClaw. Hy vọng mang lại một số cảm hứng cho bạn đang khám phá mô hình \"công ty một người\". Hoan nghênh kết nối + Ludao112, trao đổi kinh nghiệm thực chiến và use case Vibe Coding.",
]

translated = copy.deepcopy(d)
total_seg = 0
trans_count = 0
kept_count = 0
cn_idx = 0

for block in translated['blocks']:
    for el in block.get('elements', []):
        if el.get('type') != 'text_run':
            continue
        c = el.get('content', '')
        if not c.strip():
            continue
        total_seg += 1
        if has_chinese(c):
            if cn_idx < len(vn):
                el['content'] = vn[cn_idx]
                trans_count += 1
            else:
                kept_count += 1
                print(f'OUT OF RANGE [{cn_idx}]: {c[:60]}', file=sys.stderr)
            cn_idx += 1
        else:
            kept_count += 1

with open('art4_translated_c2.json', 'w', encoding='utf-8') as f:
    json.dump(translated, f, ensure_ascii=False, indent=2)

print(f'Total segments: {total_seg}, Translated: {trans_count}, Kept: {kept_count}')
print(f'Chinese segments found: {cn_idx}, Vietnamese translations: {len(vn)}')
print(f'Total blocks: {len(translated["blocks"])}')
